# Generated by Django 4.2 on 2026-05-14 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_email', models.EmailField(max_length=254)),
                ('destinatario_nombre', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('ABIERTO', 'Abierto'), ('REBOTADO', 'Rebotado'), ('ERROR', 'Error')], default='ENVIADO', max_length=15)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('intentos', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Enviado',
                'verbose_name_plural': 'Emails Enviados',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALDO_BAJO', 'Saldo bajo'), ('RECARGA', 'Recarga exitosa'), ('CONSUMO', 'Consumo registrado'), ('VENCIMIENTO', 'Vencimiento de tarjeta'), ('ALMUERZO', 'Cuenta de almuerzo'), ('SISTEMA', 'Alerta del sistema')], max_length=15)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('destino', models.CharField(choices=[('EMAIL', 'Email'), ('SISTEMA', 'En sistema')], default='SISTEMA', max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo_html', models.TextField()),
                ('cuerpo_texto', models.TextField(blank=True, null=True)),
                ('variables', models.JSONField(default=list, help_text='Variables disponibles en la plantilla')),
                ('categoria', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Emails',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(max_length=50)),
                ('email_activo', models.BooleanField(default=True)),
                ('sistema_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='SolicitudNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=255)),
                ('destino', models.CharField(choices=[('EMAIL', 'Email'), ('SISTEMA', 'En sistema')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_notificacion', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Solicitud de Notificación',
                'verbose_name_plural': 'Solicitudes de Notificaciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
