# Generated by Django 6.0.2 on 2026-03-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaDestinatarios',
            fields=[
                ('id_destinatario', models.AutoField(primary_key=True, serialize=False)),
                ('via_email', models.IntegerField()),
                ('via_sistema', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'alerta_destinatarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlertasAutomaticas',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('condicion', models.TextField()),
                ('tipo_alerta', models.CharField(max_length=20)),
                ('criticidad', models.CharField(max_length=10)),
                ('frecuencia_min', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alertas_automaticas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlertasSistema',
            fields=[
                ('id_alerta', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('mensaje', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=9, null=True)),
                ('id_empleado_resuelve', models.IntegerField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alertas_sistema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnomaliasDetectadas',
            fields=[
                ('id_anomalia', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('tipo_anomalia', models.CharField(max_length=30)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_deteccion', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_riesgo', models.CharField(max_length=10)),
                ('notificado', models.IntegerField()),
            ],
            options={
                'db_table': 'anomalias_detectadas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CampanasComunicacion',
            fields=[
                ('id_campana', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
                ('segmentacion', models.TextField()),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_enviada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('total_destinatarios', models.IntegerField()),
                ('total_enviados', models.IntegerField()),
                ('total_entregados', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'campanas_comunicacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmailsEnviados',
            fields=[
                ('id_email', models.AutoField(primary_key=True, serialize=False)),
                ('email_destinatario', models.CharField(max_length=254)),
                ('nombre_destinatario', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('estado', models.CharField(max_length=20)),
                ('fecha_envio', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('intentos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Email Enviado',
                'verbose_name_plural': 'Emails Enviados',
                'db_table': 'emails_enviados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialAlertas',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_disparada', models.DateTimeField()),
                ('mensaje', models.TextField()),
                ('datos_contexto', models.JSONField()),
                ('resuelto', models.IntegerField()),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_alertas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotificacionesPortal',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.IntegerField()),
                ('fecha_envio', models.DateTimeField()),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'notificaciones_portal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotificacionesSaldo',
            fields=[
                ('id_notificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(max_length=50)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mensaje', models.TextField()),
                ('enviada_email', models.IntegerField()),
                ('enviada_sms', models.IntegerField()),
                ('leida', models.IntegerField()),
                ('email_destinatario', models.CharField(blank=True, max_length=254, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificaciones_saldo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantillasEmail',
            fields=[
                ('id_template', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo_html', models.TextField()),
                ('cuerpo_texto', models.TextField(blank=True, null=True)),
                ('variables', models.JSONField()),
                ('categoria', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Emails',
                'db_table': 'plantillas_email',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantillasSms',
            fields=[
                ('id_template', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=160)),
                ('variables', models.JSONField()),
                ('categoria', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'plantillas_sms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreferenciasNotificacion',
            fields=[
                ('id_preferencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(max_length=50)),
                ('email_activo', models.IntegerField()),
                ('push_activo', models.IntegerField()),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
                'db_table': 'preferencias_notificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RestriccionesHorarias',
            fields=[
                ('id_restriccion', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'restricciones_horarias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmsEnviados',
            fields=[
                ('id_sms', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=160)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_envio', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'sms_enviados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolicitudesNotificacion',
            fields=[
                ('id_solicitud', models.BigAutoField(primary_key=True, serialize=False)),
                ('saldo_alerta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mensaje', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=8)),
                ('estado', models.CharField(blank=True, max_length=9, null=True)),
                ('fecha_solicitud', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitudes_notificacion',
                'managed': True,
            },
        ),
    ]
