# Generated by Django 6.0.2 on 2026-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0002_initial'),
        ('notificaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertadestinatarios',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='alertadestinatarios',
            name='id_alerta',
            field=models.ForeignKey(db_column='id_alerta', on_delete=django.db.models.deletion.DO_NOTHING, to='notificaciones.alertasautomaticas'),
        ),
        migrations.AddField(
            model_name='campanascomunicacion',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='emailsenviados',
            name='enviado_por',
            field=models.ForeignKey(blank=True, db_column='enviado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='emailsenviados',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='historialalertas',
            name='id_alerta',
            field=models.ForeignKey(db_column='id_alerta', on_delete=django.db.models.deletion.DO_NOTHING, to='notificaciones.alertasautomaticas'),
        ),
        migrations.AddField(
            model_name='historialalertas',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, db_column='resuelto_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='notificacionesportal',
            name='id_usuario_portal',
            field=models.ForeignKey(db_column='id_usuario_portal', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuariosportal'),
        ),
        migrations.AddField(
            model_name='notificacionessaldo',
            name='nro_tarjeta',
            field=models.ForeignKey(db_column='nro_tarjeta', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tarjetas'),
        ),
        migrations.AddField(
            model_name='plantillasemail',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='emailsenviados',
            name='id_template',
            field=models.ForeignKey(blank=True, db_column='id_template', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notificaciones.plantillasemail'),
        ),
        migrations.AddField(
            model_name='campanascomunicacion',
            name='id_email_template',
            field=models.ForeignKey(blank=True, db_column='id_email_template', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notificaciones.plantillasemail'),
        ),
        migrations.AddField(
            model_name='campanascomunicacion',
            name='id_sms_template',
            field=models.ForeignKey(blank=True, db_column='id_sms_template', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notificaciones.plantillassms'),
        ),
        migrations.AddField(
            model_name='preferenciasnotificacion',
            name='id_usuario_portal',
            field=models.ForeignKey(db_column='id_usuario_portal', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuariosportal'),
        ),
        migrations.AddField(
            model_name='smsenviados',
            name='enviado_por',
            field=models.ForeignKey(blank=True, db_column='enviado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='smsenviados',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='smsenviados',
            name='id_template',
            field=models.ForeignKey(blank=True, db_column='id_template', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notificaciones.plantillassms'),
        ),
        migrations.AddField(
            model_name='solicitudesnotificacion',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='solicitudesnotificacion',
            name='nro_tarjeta',
            field=models.ForeignKey(db_column='nro_tarjeta', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tarjetas'),
        ),
        migrations.AlterUniqueTogether(
            name='alertadestinatarios',
            unique_together={('id_alerta', 'id_empleado')},
        ),
        migrations.AlterUniqueTogether(
            name='preferenciasnotificacion',
            unique_together={('id_usuario_portal', 'tipo_notificacion')},
        ),
    ]
