# Generated by Django 6.0.2 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertadestinatarios',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='alertasautomaticas',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='plantillasemail',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='plantillassms',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='restriccioneshorarias',
            name='activo',
        ),
        migrations.AddField(
            model_name='alertadestinatarios',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertasautomaticas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plantillasemail',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plantillassms',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restriccioneshorarias',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
