# Generated by Django 5.2.16 on 2026-07-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_add_whatsapp_destino'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='notificacio_usuario_667b9b_idx',
            old_name='notificacio_usuario_activa_idx',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('SALDO_BAJO', 'Saldo bajo'), ('RECARGA', 'Recarga exitosa'), ('CONSUMO', 'Consumo registrado'), ('VENCIMIENTO', 'Vencimiento de tarjeta'), ('ALMUERZO', 'Cuenta de almuerzo'), ('SISTEMA', 'Alerta del sistema'), ('VENTA_DEUDA', 'Venta con saldo negativo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='solicitudnotificacion',
            name='destino',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SISTEMA', 'En sistema'), ('WHATSAPP', 'WhatsApp')], max_length=10),
        ),
    ]
