# Generated by Django 5.2.16 on 2026-07-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0006_rename_notificacio_usuario_activa_idx_notificacio_usuario_667b9b_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferencianotificacion',
            options={'ordering': ['usuario', 'tipo_notificacion'], 'verbose_name': 'Preferencia de Notificación', 'verbose_name_plural': 'Preferencias de Notificaciones'},
        ),
    ]
