# Generated by Django 5.2.16 on 2026-09-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0007_alter_preferencianotificacion_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailenviado',
            name='plantilla',
        ),
        migrations.DeleteModel(
            name='PlantillaEmail',
        ),
    ]
