# Generated by Django 5.2.16 on 2026-09-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0009_rename_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailenviado',
            name='id_email',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id_notificacion',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preferencianotificacion',
            name='id_preferencia',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='id_push',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudnotificacion',
            name='id_solicitud_notif',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
