# Generated by Django 5.2.16 on 2026-09-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0010_alter_emailenviado_id_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('SALDO_BAJO', 'Saldo bajo'), ('RECARGA', 'Recarga exitosa'), ('CONSUMO', 'Consumo registrado'), ('VENCIMIENTO', 'Vencimiento de tarjeta'), ('ALMUERZO', 'Cuenta de almuerzo'), ('SISTEMA', 'Alerta del sistema'), ('VENTA_DEUDA', 'Venta con saldo negativo'), ('SEGURIDAD', 'Seguridad')], max_length=15),
        ),
    ]
