# Generated by Django 6.0.2 on 2026-03-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaComisiones',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField()),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valor_nuevo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'auditoria_comisiones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_caja', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cajas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CierresCaja',
            fields=[
                ('id_cierre', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora_apertura', models.DateTimeField()),
                ('fecha_hora_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_contado_fisico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diferencia_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'cierres_caja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConciliacionPagos',
            fields=[
                ('id_conciliacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_acreditacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_conciliacion', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('monto_acreditado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'conciliacion_pagos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'datos_empresa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentoImpuestos',
            fields=[
                ('pk', models.CompositePrimaryKey('id_documento', 'id_impuesto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'documento_impuestos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentosTributarios',
            fields=[
                ('id_documento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nro_secuencial', models.IntegerField()),
                ('fecha_emision', models.DateTimeField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_documento', models.CharField(max_length=11)),
                ('cdc', models.CharField(blank=True, max_length=44, null=True)),
                ('url_kude', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_sifen', models.CharField(blank=True, max_length=9, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('nro_preimpreso_interno', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Documento Tributario',
                'verbose_name_plural': 'Documentos Tributarios',
                'db_table': 'documentos_tributarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id_impuesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_impuesto', models.CharField(max_length=50, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'impuestos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientosCaja',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_comision', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_movimiento', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'movimientos_caja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PuntosExpedicion',
            fields=[
                ('id_punto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_establecimiento', models.CharField(max_length=3)),
                ('codigo_punto_expedicion', models.CharField(max_length=3)),
                ('descripcion_ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'puntos_expedicion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TarifasComision',
            fields=[
                ('id_tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_vigencia', models.DateTimeField()),
                ('fecha_fin_vigencia', models.DateTimeField(blank=True, null=True)),
                ('porcentaje_comision', models.DecimalField(decimal_places=4, max_digits=5)),
                ('monto_fijo_comision', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tarifas_comision',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Timbrados',
            fields=[
                ('nro_timbrado', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=12)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('nro_inicial', models.IntegerField()),
                ('nro_final', models.IntegerField()),
                ('es_electronico', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Timbrado',
                'verbose_name_plural': 'Timbrados',
                'db_table': 'timbrados',
                'managed': True,
            },
        ),
    ]
