# Generated by Django 4.2 on 2026-05-14 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Comisión',
                'verbose_name_plural': 'Auditorías de Comisiones',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=0, default=0, help_text='Monto en Guaraníes al abrir la caja', max_digits=12)),
                ('monto_contado_fisico', models.DecimalField(blank=True, decimal_places=0, help_text='Monto contado al cerrar', max_digits=12, null=True)),
                ('diferencia_efectivo', models.DecimalField(blank=True, decimal_places=0, help_text='Diferencia entre lo esperado y lo contado', max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('CONCILIADO', 'Conciliado')], default='ABIERTO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='ConciliacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acreditacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_conciliacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_acreditado', models.DecimalField(blank=True, decimal_places=0, help_text='Monto en extracto bancario', max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONCILIADO', 'Conciliado'), ('DISCREPANCIA', 'Discrepancia')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conciliación de Pago',
                'verbose_name_plural': 'Conciliaciones de Pagos',
                'ordering': ['-fecha_conciliacion'],
            },
        ),
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, default='Paraguay', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Datos de Empresa',
                'verbose_name_plural': 'Datos de Empresa',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.CharField(help_text='Número preimpreso (ej: 001-001-0001234)', max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('iva_10', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('iva_5', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_exenta', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('monto_comision', models.DecimalField(decimal_places=0, default=0, help_text='Comisión del medio de pago', max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TarifaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, help_text='Porcentaje de comisión (ej: 3.50 para 3.5%)', max_digits=5)),
                ('monto_fijo', models.DecimalField(blank=True, decimal_places=0, help_text='Monto fijo en Guaraníes', max_digits=12, null=True)),
                ('fecha_inicio_vigencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin_vigencia', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarifa de Comisión',
                'verbose_name_plural': 'Tarifas de Comisión',
                'ordering': ['-fecha_inicio_vigencia'],
            },
        ),
    ]
