# Generated by Django 6.0.2 on 2026-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriacomisiones',
            name='id_empleado_modifico',
            field=models.ForeignKey(blank=True, db_column='id_empleado_modifico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='cierrescaja',
            name='id_caja',
            field=models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.DO_NOTHING, to='contabilidad.cajas'),
        ),
        migrations.AddField(
            model_name='cierrescaja',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
    ]
