# Generated by Django 4.2 on 2026-05-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifacomision',
            name='medio_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='core.mediopago'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.cierrecaja'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='medio_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='core.mediopago'),
        ),
    ]
