# Generated by Django 6.0.2 on 2026-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('core', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliacionpagos',
            name='id_pago_venta',
            field=models.OneToOneField(db_column='id_pago_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.pagosventa'),
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='id_cierre',
            field=models.ForeignKey(db_column='id_cierre', on_delete=django.db.models.deletion.DO_NOTHING, to='contabilidad.cierrescaja'),
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='id_medio_pago',
            field=models.ForeignKey(db_column='id_medio_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='core.mediospago'),
        ),
        migrations.AddField(
            model_name='movimientoscaja',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas'),
        ),
        migrations.AlterUniqueTogether(
            name='puntosexpedicion',
            unique_together={('codigo_establecimiento', 'codigo_punto_expedicion')},
        ),
        migrations.AddField(
            model_name='tarifascomision',
            name='id_medio_pago',
            field=models.ForeignKey(db_column='id_medio_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='core.mediospago'),
        ),
        migrations.AddField(
            model_name='auditoriacomisiones',
            name='id_tarifa',
            field=models.ForeignKey(blank=True, db_column='id_tarifa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabilidad.tarifascomision'),
        ),
        migrations.AddField(
            model_name='timbrados',
            name='id_punto',
            field=models.ForeignKey(db_column='id_punto', on_delete=django.db.models.deletion.DO_NOTHING, to='contabilidad.puntosexpedicion'),
        ),
        migrations.AddField(
            model_name='documentostributarios',
            name='nro_timbrado',
            field=models.ForeignKey(db_column='nro_timbrado', on_delete=django.db.models.deletion.DO_NOTHING, to='contabilidad.timbrados'),
        ),
        migrations.AlterUniqueTogether(
            name='documentostributarios',
            unique_together={('nro_timbrado', 'nro_secuencial')},
        ),
    ]
