# Generated by Django 4.2 on 2026-05-14 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        ('clientes', '0002_initial'),
        ('contabilidad', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='venta',
            field=models.OneToOneField(blank=True, help_text='Venta asociada a esta factura', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura_venta', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='conciliacionpago',
            name='pago_venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacion', to='ventas.pagoventa'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres', to='contabilidad.caja'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriacomision',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_comision', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriacomision',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='contabilidad.tarifacomision'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['cierre', 'fecha'], name='contabilida_cierre__e1f3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['venta'], name='contabilida_venta_i_f65731_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['fecha', 'tipo'], name='contabilida_fecha_e35151_idx'),
        ),
        migrations.AddIndex(
            model_name='cierrecaja',
            index=models.Index(fields=['caja', 'fecha_apertura'], name='contabilida_caja_id_a68404_idx'),
        ),
        migrations.AddIndex(
            model_name='cierrecaja',
            index=models.Index(fields=['empleado', 'fecha_apertura'], name='contabilida_emplead_3d3766_idx'),
        ),
        migrations.AddIndex(
            model_name='cierrecaja',
            index=models.Index(fields=['estado'], name='contabilida_estado_d6252f_idx'),
        ),
    ]
