# Generated by Django 6.0.2 on 2026-03-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoscaja',
            name='id_cierre',
            field=models.ForeignKey(blank=True, db_column='id_cierre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabilidad.cierrescaja'),
        ),
    ]
