# Generated by Django 4.2 on 2026-05-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifacomision',
            name='medio_pago',
        ),
        migrations.DeleteModel(
            name='AuditoriaComision',
        ),
        migrations.DeleteModel(
            name='TarifaComision',
        ),
    ]
