# Generated by Django 6.0.2 on 2026-03-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_id_cierre_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoscaja',
            name='monto_comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
