# Generated by Django 4.2 on 2026-05-18 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0001_initial'),
        ('contabilidad', '0004_remove_tarifacomision_medio_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFactura',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nro_factura', models.CharField(db_index=True, help_text='Número preimpreso (ej: 001-001-0001234)', max_length=20)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('iva_10', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('iva_5', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_exenta', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, db_constraint=False, help_text='Venta asociada a esta factura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'historical Factura',
                'verbose_name_plural': 'historical Facturas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
