# Generated by Django 4.2 on 2026-05-18 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0005_historicalfactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='observaciones_conciliacion',
            field=models.TextField(blank=True, help_text='Nota del contador al conciliar el cierre', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalCierreCaja',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=0, default=0, help_text='Monto en Guaraníes al abrir la caja', max_digits=12)),
                ('monto_contado_fisico', models.DecimalField(blank=True, decimal_places=0, help_text='Monto contado al cerrar', max_digits=12, null=True)),
                ('diferencia_efectivo', models.DecimalField(blank=True, decimal_places=0, help_text='Diferencia entre lo esperado y lo contado', max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('CONCILIADO', 'Conciliado')], default='ABIERTO', max_length=15)),
                ('observaciones_conciliacion', models.TextField(blank=True, help_text='Nota del contador al conciliar el cierre', null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('caja', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabilidad.caja')),
                ('empleado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cierre de Caja',
                'verbose_name_plural': 'historical Cierres de Caja',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
