# Generated by Django 6.0.2 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_datos_iniciales_impuestos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajas',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='datosempresa',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='impuestos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='puntosexpedicion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tarifascomision',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='timbrados',
            name='activo',
        ),
        migrations.AddField(
            model_name='cajas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datosempresa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='impuestos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='puntosexpedicion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarifascomision',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timbrados',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
