# Generated by Django 4.2 on 2026-05-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_cierrecaja_observaciones_conciliacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempresa',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
