# Generated by Django 4.2 on 2026-06-03 00:50
# Sprint C1: Vistas SQL para balance de cliente y estado de cajas

from django.db import migrations

VIEWS_SQL = """
-- Vista: último saldo por cliente (evita recalcular en cada request del dashboard)
CREATE OR REPLACE VIEW v_balance_cliente AS
SELECT
    c.id                                    AS cliente_id,
    c.nombres || ' ' || c.apellidos        AS cliente_nombre,
    c.ruc_ci,
    c.telefono,
    c.email,
    COALESCE(ult.saldo_resultante, 0)       AS saldo_deuda,
    ult.fecha                               AS fecha_ultimo_mov,
    CASE
        WHEN COALESCE(ult.saldo_resultante, 0) > 0 THEN 'CON_DEUDA'
        WHEN COALESCE(ult.saldo_resultante, 0) < 0 THEN 'A_FAVOR'
        ELSE 'SIN_MOVIMIENTOS'
    END                                     AS estado_cuenta
FROM clientes_cliente c
LEFT JOIN LATERAL (
    SELECT saldo_resultante, fecha
    FROM clientes_cuentacorrientecliente
    WHERE cliente_id = c.id
    ORDER BY id DESC
    LIMIT 1
) ult ON true
WHERE c.activo = true;

-- Vista: estado de todas las cajas con totales del día
CREATE OR REPLACE VIEW v_estado_cajas AS
SELECT
    cj.id                                           AS caja_id,
    cj.nombre                                       AS caja_nombre,
    cc.id                                           AS cierre_id,
    cc.estado,
    cc.fecha_apertura,
    cc.fecha_cierre,
    cc.monto_inicial,
    cc.monto_contado_fisico,
    cc.diferencia_efectivo,
    COALESCE(u.nombre || ' ' || u.apellido, 'Sin asignar') AS cajero,
    COUNT(DISTINCT mv.id)                           AS total_movimientos,
    COALESCE(SUM(mv.monto)
        FILTER (WHERE mv.tipo = 'INGRESO'), 0)      AS total_ingresos,
    COALESCE(SUM(mv.monto)
        FILTER (WHERE mv.tipo = 'EGRESO'), 0)       AS total_egresos,
    cc.fecha_apertura::date                         AS fecha
FROM contabilidad_caja cj
LEFT JOIN contabilidad_cierrecaja cc ON cc.caja_id = cj.id
LEFT JOIN usuarios u ON u.id = cc.empleado_id
LEFT JOIN contabilidad_movimientocaja mv ON mv.cierre_id = cc.id
WHERE cj.activo = true
GROUP BY cj.id, cj.nombre, cc.id, cc.estado, cc.fecha_apertura,
         cc.fecha_cierre, cc.monto_inicial, cc.monto_contado_fisico,
         cc.diferencia_efectivo, u.nombre, u.apellido;
"""

DROP_VIEWS = """
DROP VIEW IF EXISTS v_balance_cliente;
DROP VIEW IF EXISTS v_estado_cajas;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0007_add_nombre_fantasia_empresa"),
    ]

    operations = [
        migrations.RunSQL(VIEWS_SQL, reverse_sql=DROP_VIEWS),
    ]
