# Generated by Django 4.2 on 2026-06-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_views_sql'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocaja',
            name='monto_comision',
        ),
    ]
