# Generated by Django 6.0.2 on 2026-04-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_datos_iniciales_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentostributarios',
            name='nro_preimpreso_interno',
            field=models.CharField(blank=True, help_text='Número de formulario preimpreso (ej: 001-001-0000123)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentostributarios',
            name='nro_secuencial',
            field=models.IntegerField(help_text='Número secuencial fiscal dentro del rango del timbrado'),
        ),
    ]
