# Generated by Django 4.2 on 2026-06-09 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_movimientocaja_medio_pago_nullable'),
        ('contabilidad', '0009_remove_monto_comision_movimientocaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='medio_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='core.mediopago'),
        ),
    ]
