# Generated by Django 6.0.2 on 2026-04-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_condicion_venta'),
        ('core', '0011_configuraciones_adicionales'),
        ('usuarios', '0008_alter_empleados_options_and_more'),
        ('ventas', '0007_add_condicion_venta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierrescaja',
            options={'managed': True, 'ordering': ['-fecha_hora_apertura']},
        ),
        migrations.AlterModelOptions(
            name='movimientoscaja',
            options={'managed': True, 'ordering': ['-fecha_movimiento']},
        ),
        migrations.AddIndex(
            model_name='cierrescaja',
            index=models.Index(fields=['id_caja', 'fecha_hora_apertura'], name='idx_cierres_caja_fecha'),
        ),
        migrations.AddIndex(
            model_name='cierrescaja',
            index=models.Index(fields=['id_empleado', 'fecha_hora_apertura'], name='idx_cierres_emp_fecha'),
        ),
        migrations.AddIndex(
            model_name='cierrescaja',
            index=models.Index(fields=['estado', 'fecha_hora_cierre'], name='idx_cierres_estado'),
        ),
        migrations.AddIndex(
            model_name='cierrescaja',
            index=models.Index(fields=['fecha_hora_apertura'], name='idx_cierres_apertura'),
        ),
        migrations.AddIndex(
            model_name='movimientoscaja',
            index=models.Index(fields=['id_cierre', 'fecha_movimiento'], name='idx_mov_caja_cierre'),
        ),
        migrations.AddIndex(
            model_name='movimientoscaja',
            index=models.Index(fields=['id_venta'], name='idx_mov_caja_venta'),
        ),
        migrations.AddIndex(
            model_name='movimientoscaja',
            index=models.Index(fields=['fecha_movimiento', 'tipo_movimiento'], name='idx_mov_caja_fecha_tipo'),
        ),
        migrations.AddIndex(
            model_name='movimientoscaja',
            index=models.Index(fields=['id_medio_pago', 'fecha_movimiento'], name='idx_mov_caja_medio'),
        ),
    ]
