# Generated by Django 6.0.2 on 2026-04-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_condicion_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='timbrados',
            name='es_electronico',
            field=models.SmallIntegerField(default=0, help_text='0=impreso, 1=electrónico'),
        ),
    ]
