# Generated by Django 5.2.16 on 2026-09-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_mv_balance_cliente_uq_caja_abierta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConciliacionPago',
        ),
    ]
