# Generated by Django 5.2.16 on 2026-09-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0014_rename_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='id_caja',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='id_cierre',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datosempresa',
            name='id_datos_empresa',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id_factura',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcierrecaja',
            name='id_cierre',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfactura',
            name='id_factura',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='id_movimiento_caja',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
