# Generated by Django 5.2.16 on 2026-09-05 13:34

import django.db.models.deletion
from django.db import migrations, models


def convertir_ciudad_texto_a_fk(apps, schema_editor):
    """Mapea el texto libre en DatosEmpresa.ciudad al id de Ciudad correspondiente
    (creándola si no existe), para que el AlterField posterior a ForeignKey
    pueda castear el valor sin perder datos reales."""
    DatosEmpresa = apps.get_model('contabilidad', 'DatosEmpresa')
    Ciudad = apps.get_model('clientes', 'Ciudad')

    for empresa in DatosEmpresa.objects.exclude(ciudad__isnull=True).exclude(ciudad=''):
        nombre = (empresa.ciudad or '').strip()
        if not nombre:
            continue
        ciudad = Ciudad.objects.filter(nombre__iexact=nombre).first()
        if ciudad is None:
            ciudad = Ciudad.objects.create(nombre=nombre)
        DatosEmpresa.objects.filter(pk=empresa.pk).update(ciudad=str(ciudad.pk))


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_remove_ciudad_pais_remove_cliente_ciudad_catalogo_and_more'),
        ('contabilidad', '0016_fix_fn_sync_factura_venta'),
    ]

    operations = [
        migrations.RunPython(convertir_ciudad_texto_a_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='datosempresa',
            name='pais',
        ),
        migrations.AlterField(
            model_name='datosempresa',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_empresa', to='clientes.ciudad'),
        ),
    ]
