# Generated by Django 5.2.16 on 2026-09-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_remove_ciudad_pais_remove_cliente_ciudad_catalogo_and_more'),
        ('contabilidad', '0016_fix_fn_sync_factura_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosempresa',
            name='pais',
        ),
        migrations.AlterField(
            model_name='datosempresa',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_empresa', to='clientes.ciudad'),
        ),
    ]
