# Generated by Django 6.0.2 on 2026-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('contabilidad', '0001_initial'),
        ('core', '0001_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_promocion', models.CharField(max_length=25)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('dias_semana', models.JSONField(blank=True, null=True)),
                ('aplica_a', models.CharField(max_length=20)),
                ('min_cantidad', models.IntegerField()),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_usos_cliente', models.IntegerField(blank=True, null=True)),
                ('max_usos_total', models.IntegerField(blank=True, null=True)),
                ('usos_actuales', models.IntegerField()),
                ('requiere_codigo', models.BooleanField(default=True)),
                ('codigo_promocion', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('prioridad', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promociones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotasCreditoCliente',
            fields=[
                ('id_nota', models.BigAutoField(primary_key=True, serialize=False)),
                ('nro_nota_credito', models.BigIntegerField()),
                ('fecha_emision', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(max_length=10)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes')),
                ('id_empleado_autoriza', models.ForeignKey(db_column='id_empleado_autoriza', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'db_table': 'notas_credito_cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesNotaCredito',
            fields=[
                ('id_detalle_nota', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
                ('id_nota', models.ForeignKey(db_column='id_nota', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.notascreditocliente')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Crédito',
                'verbose_name_plural': 'Detalles de Notas de Crédito',
                'db_table': 'detalles_nota_credito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('nro_factura_venta', models.BigIntegerField(blank=True, help_text='Número de factura legal', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la venta')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total de la venta', max_digits=12)),
                ('saldo_pendiente', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Saldo pendiente de pago', max_digits=12, null=True)),
                ('estado_pago', models.CharField(help_text='Ej: Pagada, Pendiente, Parcial', max_length=10)),
                ('estado', models.CharField(help_text='Ej: Activa, Cancelada, Anulada', max_length=10)),
                ('tipo_venta', models.CharField(help_text='Ej: Contado, Crédito', max_length=20)),
                ('motivo_credito', models.TextField(blank=True, null=True)),
                ('genera_factura_legal', models.BooleanField(default=False, help_text='1 si genera factura electrónica')),
                ('autorizado_por', models.ForeignKey(blank=True, db_column='autorizado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas_autorizadas', to='usuarios.empleados')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas', to='clientes.clientes')),
                ('id_documento', models.ForeignKey(blank=True, db_column='id_documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas', to='contabilidad.documentostributarios')),
                ('id_empleado_cajero', models.ForeignKey(db_column='id_empleado_cajero', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas_realizadas', to='usuarios.empleados')),
                ('id_hijo', models.ForeignKey(blank=True, db_column='id_hijo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas', to='clientes.hijos')),
                ('id_medio_pago', models.ForeignKey(blank=True, db_column='id_medio_pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas', to='core.mediospago')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PromocionesAplicadas',
            fields=[
                ('id_aplicacion', models.AutoField(primary_key=True, serialize=False)),
                ('monto_descontado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_aplicacion', models.DateTimeField()),
                ('id_promocion', models.ForeignKey(db_column='id_promocion', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.promociones')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas')),
            ],
            options={
                'verbose_name': 'Promoción Aplicada',
                'verbose_name_plural': 'Promociones Aplicadas',
                'db_table': 'promociones_aplicadas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagosVenta',
            fields=[
                ('id_pago_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pago', models.DateTimeField()),
                ('estado', models.CharField(max_length=10)),
                ('id_cierre', models.BigIntegerField(blank=True, null=True)),
                ('id_medio_pago', models.ForeignKey(db_column='id_medio_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='core.mediospago')),
                ('nro_tarjeta_usada', models.ForeignKey(blank=True, db_column='nro_tarjeta_usada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tarjetas')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Venta',
                'db_table': 'pagos_venta',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='notascreditocliente',
            name='id_venta_origen',
            field=models.ForeignKey(blank=True, db_column='id_venta_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas'),
        ),
        migrations.CreateModel(
            name='AplicacionPagosVentas',
            fields=[
                ('id_aplicacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_pago_venta', models.ForeignKey(db_column='id_pago_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.pagosventa')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas')),
            ],
            options={
                'verbose_name': 'Aplicación de Pago',
                'verbose_name_plural': 'Aplicaciones de Pagos',
                'db_table': 'aplicacion_pagos_ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductosPromocion',
            fields=[
                ('id_producto_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
                ('id_promocion', models.ForeignKey(db_column='id_promocion', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.promociones')),
            ],
            options={
                'verbose_name': 'Producto en Promoción',
                'verbose_name_plural': 'Productos en Promociones',
                'db_table': 'productos_promocion',
                'managed': True,
                'unique_together': {('id_promocion', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='CategoriasPromocion',
            fields=[
                ('id_categoria_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.categorias')),
                ('id_promocion', models.ForeignKey(db_column='id_promocion', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.promociones')),
            ],
            options={
                'verbose_name': 'Categoría en Promoción',
                'verbose_name_plural': 'Categorías en Promociones',
                'db_table': 'categorias_promocion',
                'managed': True,
                'unique_together': {('id_promocion', 'id_categoria')},
            },
        ),
        migrations.CreateModel(
            name='DetallesVenta',
            fields=[
                ('id_detalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalles_venta',
                'managed': True,
                'unique_together': {('id_venta', 'id_producto')},
            },
        ),
    ]
