# Generated by Django 4.2 on 2026-05-14 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('contabilidad', '0002_initial'),
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('plazo_dias', models.IntegerField(default=0, help_text='Días de plazo para pago')),
            ],
            options={
                'verbose_name': 'Condición de Venta',
                'verbose_name_plural': 'Condiciones de Venta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10)),
                ('monto_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_gravada_10', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_gravada_5', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_exenta', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('iva_10', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('iva_5', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('nro_factura', models.CharField(blank=True, help_text='Número de factura legal', max_length=50, null=True)),
                ('genera_factura_legal', models.BooleanField(default=False)),
                ('motivo_credito', models.TextField(blank=True, help_text='Motivo si se vendió a crédito', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_factura', to='contabilidad.caja')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(help_text='Cliente que realizó la compra', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_factura', to='clientes.cliente')),
                ('factura', models.ForeignKey(blank=True, help_text='Factura preimpresa asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_factura', to='contabilidad.factura')),
                ('hijo', models.ForeignKey(blank=True, help_text='Hijo que recibió el producto (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_factura', to='clientes.hijo')),
                ('medio_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_factura', to='core.mediopago')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, help_text='Monto pagado en Guaraníes', max_digits=12)),
                ('monto_comision', models.DecimalField(decimal_places=0, default=0, help_text='Comisión por medio de pago (POS, transferencia)', max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, help_text='Referencia de la transacción', max_length=100, null=True)),
                ('ref_pago_pos', models.CharField(blank=True, help_text='Referencia del terminal POS', max_length=100, null=True)),
                ('ref_transferencia', models.CharField(blank=True, help_text='Comprobante de transferencia bancaria', max_length=100, null=True)),
                ('banco_emisor', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONCILIADO', 'Conciliado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('cierre_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='contabilidad.cierrecaja')),
                ('cliente', models.ForeignKey(help_text='Cliente que realiza el pago', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='clientes.cliente')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.mediopago')),
                ('venta', models.ForeignKey(blank=True, help_text='Venta asociada (nulo si es pago a cuenta corriente)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nota_credito', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=0, help_text='Monto en Guaraníes', max_digits=12)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('APLICADA', 'Aplicada'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='clientes.cliente')),
                ('empleado_autoriza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('venta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=0, help_text='Precio unitario en Guaraníes', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=0, help_text='Subtotal en Guaraníes', max_digits=12)),
                ('monto_gravada_10', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_gravada_5', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_exenta', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('iva_10', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('iva_5', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=0, help_text='Precio en Guaraníes', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=0, help_text='Subtotal en Guaraníes', max_digits=12)),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.notacredito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_nc', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Crédito',
                'verbose_name_plural': 'Detalles de Notas de Crédito',
            },
        ),
        migrations.CreateModel(
            name='AplicacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=0, help_text='Monto aplicado a esta venta', max_digits=12)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='ventas.pagoventa')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_pago', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Aplicación de Pago',
                'verbose_name_plural': 'Aplicaciones de Pagos',
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente', 'fecha'], name='idx_venta_cliente_fecha'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='idx_venta_fecha'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado', 'fecha'], name='idx_venta_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado_pago'], name='idx_venta_estado_pago'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['nro_factura'], name='idx_venta_factura'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['cliente', 'fecha'], name='idx_pago_cliente_fecha'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['venta', 'fecha'], name='idx_pago_venta_fecha'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['estado'], name='idx_pago_estado'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['venta'], name='idx_det_venta'),
        ),
        migrations.AddIndex(
            model_name='detalleventa',
            index=models.Index(fields=['producto'], name='idx_det_producto'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleventa',
            unique_together={('venta', 'producto')},
        ),
    ]
