# Generated by Django 4.2 on 2026-05-18 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0002_initial'),
        ('contabilidad', '0005_historicalfactura'),
        ('core', '0007_historicalcargasaldo'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVenta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10)),
                ('monto_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_gravada_10', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_gravada_5', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('monto_exenta', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('iva_10', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('iva_5', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('nro_factura', models.CharField(blank=True, help_text='Número de factura legal', max_length=50, null=True)),
                ('genera_factura_legal', models.BooleanField(default=False)),
                ('motivo_credito', models.TextField(blank=True, help_text='Motivo si se vendió a crédito', null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autorizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('caja', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabilidad.caja')),
                ('cajero', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, help_text='Cliente que realizó la compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
                ('factura', models.ForeignKey(blank=True, db_constraint=False, help_text='Factura preimpresa asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabilidad.factura')),
                ('hijo', models.ForeignKey(blank=True, db_constraint=False, help_text='Hijo que recibió el producto (si aplica)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.hijo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medio_pago', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.mediopago')),
            ],
            options={
                'verbose_name': 'historical Venta',
                'verbose_name_plural': 'historical Ventas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
