# Generated by Django 6.0.2 on 2026-03-01 16:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosventa',
            name='monto_comision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recargo por uso de POS (NO facturado, trasladado al cliente)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pagosventa',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto de productos (base facturada, sin comisión)', max_digits=12),
        ),
    ]
