# Generated by Django 6.0.2 on 2026-03-16 21:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_agregar_comision_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesventa',
            name='iva_10',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IVA liquidado al 10% (subtotal / 11)', max_digits=12),
        ),
        migrations.AddField(
            model_name='detallesventa',
            name='iva_5',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IVA liquidado al 5% (subtotal / 21)', max_digits=12),
        ),
        migrations.AddField(
            model_name='detallesventa',
            name='monto_exenta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto exento de IVA', max_digits=12),
        ),
        migrations.AddField(
            model_name='detallesventa',
            name='monto_gravada_10',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base imponible gravada al 10%', max_digits=12),
        ),
        migrations.AddField(
            model_name='detallesventa',
            name='monto_gravada_5',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base imponible gravada al 5%', max_digits=12),
        ),
        migrations.AddField(
            model_name='ventas',
            name='iva_10',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IVA liquidado al 10% (monto_gravada_10 / 11)', max_digits=12),
        ),
        migrations.AddField(
            model_name='ventas',
            name='iva_5',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='IVA liquidado al 5% (monto_gravada_5 / 21)', max_digits=12),
        ),
        migrations.AddField(
            model_name='ventas',
            name='monto_exenta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto exento de IVA', max_digits=12),
        ),
        migrations.AddField(
            model_name='ventas',
            name='monto_gravada_10',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base imponible gravada al 10%', max_digits=12),
        ),
        migrations.AddField(
            model_name='ventas',
            name='monto_gravada_5',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base imponible gravada al 5%', max_digits=12),
        ),
    ]
