# Generated by Django 4.2 on 2026-05-18 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicalcargasaldo'),
        ('ventas', '0002_historicalventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalventa',
            name='tarjeta',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Tarjeta usada en el pago (permite reverso al anular)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tarjeta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tarjeta',
            field=models.ForeignKey(blank=True, help_text='Tarjeta usada en el pago (permite reverso al anular)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='core.tarjeta'),
        ),
    ]
