# Generated by Django 6.0.2 on 2026-03-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_agregar_campos_impuesto_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosventa',
            name='banco_emisor',
            field=models.CharField(blank=True, help_text='Banco emisor del pago (transferencia o tarjeta)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagosventa',
            name='ref_pago_pos',
            field=models.CharField(blank=True, help_text='Número de referencia generado por el terminal POS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagosventa',
            name='ref_pg_transf',
            field=models.CharField(blank=True, help_text='Número de referencia/comprobante de transferencia bancaria', max_length=100, null=True),
        ),
    ]
