# Generated by Django 4.2 on 2026-05-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_historicalventa_tarjeta_venta_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoventa',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONCILIADO', 'Conciliado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=15),
        ),
    ]
