# Generated by Django 4.2 on 2026-06-03 00:41
# Sprint A1: CHECK constraints monetarios en ventas_venta

from django.db import migrations

CHECK_SQL = """
ALTER TABLE ventas_venta
    ADD CONSTRAINT chk_venta_monto_total
    CHECK (monto_total >= 0);

ALTER TABLE ventas_venta
    ADD CONSTRAINT chk_venta_montos_gravados
    CHECK (monto_gravada_10 >= 0 AND monto_gravada_5 >= 0 AND monto_exenta >= 0);

ALTER TABLE ventas_venta
    ADD CONSTRAINT chk_venta_iva
    CHECK (iva_10 >= 0 AND iva_5 >= 0);
"""

DROP_SQL = """
ALTER TABLE ventas_venta DROP CONSTRAINT IF EXISTS chk_venta_monto_total;
ALTER TABLE ventas_venta DROP CONSTRAINT IF EXISTS chk_venta_montos_gravados;
ALTER TABLE ventas_venta DROP CONSTRAINT IF EXISTS chk_venta_iva;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0004_add_pago_venta_estado_anulado"),
    ]

    operations = [
        migrations.RunSQL(CHECK_SQL, reverse_sql=DROP_SQL),
    ]
