# Generated by Django 6.0.2 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_agregar_referencias_pago_seguridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promociones',
            name='activo',
        ),
        migrations.AddField(
            model_name='promociones',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
