# Generated by Django 6.0.2 on 2026-03-31 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_rename_activo_to_estado'),
        ('ventas', '0005_rename_activo_to_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='id_caja',
            field=models.ForeignKey(blank=True, db_column='id_caja', help_text='Caja (terminal POS) que procesó esta venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='contabilidad.cajas'),
        ),
    ]
