# Generated by Django 6.0.2 on 2026-04-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_clientes_idx_clientes_email_and_more'),
        ('contabilidad', '0012_alter_cierrescaja_options_and_more'),
        ('core', '0011_configuraciones_adicionales'),
        ('productos', '0006_productos_idx_productos_cod_barra_and_more'),
        ('usuarios', '0008_alter_empleados_options_and_more'),
        ('ventas', '0007_add_condicion_venta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagosventa',
            options={'managed': True, 'ordering': ['-fecha_pago'], 'verbose_name': 'Pago de Venta', 'verbose_name_plural': 'Pagos de Venta'},
        ),
        migrations.AddIndex(
            model_name='detallesventa',
            index=models.Index(fields=['id_venta'], name='idx_detalles_venta_venta'),
        ),
        migrations.AddIndex(
            model_name='detallesventa',
            index=models.Index(fields=['id_producto'], name='idx_detalles_venta_prod'),
        ),
        migrations.AddIndex(
            model_name='pagosventa',
            index=models.Index(fields=['id_venta', 'fecha_pago'], name='idx_pagos_venta_venta'),
        ),
        migrations.AddIndex(
            model_name='pagosventa',
            index=models.Index(fields=['fecha_pago'], name='idx_pagos_venta_fecha'),
        ),
        migrations.AddIndex(
            model_name='pagosventa',
            index=models.Index(fields=['id_medio_pago', 'fecha_pago'], name='idx_pagos_venta_medio'),
        ),
        migrations.AddIndex(
            model_name='pagosventa',
            index=models.Index(fields=['estado', 'fecha_pago'], name='idx_pagos_venta_estado'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['fecha', 'id_empleado_cajero'], name='idx_ventas_fecha_emp'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['nro_factura_venta'], name='idx_ventas_nro_factura'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['id_cliente', 'fecha'], name='idx_ventas_cliente_fecha'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['estado', 'fecha'], name='idx_ventas_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['id_caja', 'fecha'], name='idx_ventas_caja_fecha'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['fecha'], name='idx_ventas_fecha'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['id_hijo', 'fecha'], name='idx_ventas_hijo_fecha'),
        ),
    ]
