# Generated by Django 5.2.16 on 2026-07-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_add_descuento_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, help_text='Subtotal neto en Guaraníes (ya con descuento aplicado)', max_digits=12),
        ),
    ]
