# Generated by Django 5.2.16 on 2026-07-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_detalleventa_subtotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacionpago',
            options={'ordering': ['id'], 'verbose_name': 'Aplicación de Pago', 'verbose_name_plural': 'Aplicaciones de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Venta'},
        ),
    ]
