# Generated by Django 5.2.16 on 2026-09-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_rename_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacionpago',
            options={'ordering': ['id_aplicacion_pago'], 'verbose_name': 'Aplicación de Pago', 'verbose_name_plural': 'Aplicaciones de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['id_detalle_venta'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Venta'},
        ),
        migrations.AlterField(
            model_name='aplicacionpago',
            name='id_aplicacion_pago',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='condicionventa',
            name='id_condicion_venta',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallenotacredito',
            name='id_detalle_nc',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='id_detalle_venta',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalventa',
            name='id_venta',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='id_nota_credito',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='id_pago_venta',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
