# Generated by Django 5.2.16 on 2026-09-05 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_aplicacionpago_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CondicionVenta',
        ),
    ]
