# Generated by Django 5.2.16 on 2026-09-19 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almuerzos', '0026_eliminar_marcado_en_cuenta_y_trigger'),
        ('clientes', '0021_calendario_lectivo'),
        ('contabilidad', '0017_remove_datosempresa_pais_alter_datosempresa_ciudad'),
        ('core', '0034_remove_pagobancard_cuenta_almuerzo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCuentaAlumno',
            fields=[
                ('id_cierre_cuenta', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('PARCIAL', 'Parcial'), ('RESUELTO', 'Resuelto'), ('CERRADO_CON_SALDO', 'Cerrado con saldo pendiente')], default='ABIERTO', max_length=20)),
                ('saldo_cantina_inicial', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('saldo_almuerzo_inicial', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('motivo_cierre', models.TextField(blank=True)),
                ('saldo_cantina_final', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('saldo_almuerzo_final', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('abierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_cuenta', to='clientes.hijo')),
            ],
            options={
                'verbose_name': 'Cierre de cuenta de alumno',
                'verbose_name_plural': 'Cierres de cuenta de alumnos',
                'ordering': ['-anio', 'hijo__apellido', 'hijo__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResolucionSaldo',
            fields=[
                ('id_resolucion', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DEVOLUCION', 'Devolución'), ('TRASPASO_HERMANO', 'Traspaso a hermano'), ('COMPENSACION', 'Compensación entre bolsillos'), ('COBRO', 'Cobro de deuda'), ('TRASLADO_CC', 'Traslado a cuenta corriente familiar'), ('CONDONACION', 'Condonación')], max_length=20)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Pendiente de aprobación'), ('EJECUTADA', 'Ejecutada'), ('RECHAZADA', 'Rechazada')], default='SOLICITADA', max_length=12)),
                ('bolsillo_origen', models.CharField(choices=[('CANTINA', 'Cantina (tarjeta)'), ('ALMUERZO', 'Almuerzo')], max_length=10)),
                ('bolsillo_destino', models.CharField(blank=True, choices=[('CANTINA', 'Cantina (tarjeta)'), ('ALMUERZO', 'Almuerzo')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('motivo', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('movimiento_tarjeta_origen_id', models.BigIntegerField(blank=True, null=True)),
                ('movimiento_tarjeta_destino_id', models.BigIntegerField(blank=True, null=True)),
                ('carga_saldo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.cargasaldo')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones', to='cierre_cuentas.cierrecuentaalumno')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hijo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones_recibidas', to='clientes.hijo')),
                ('movimiento_almuerzo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='almuerzos.movimientosaldoalmuerzo')),
                ('movimiento_almuerzo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='almuerzos.movimientosaldoalmuerzo')),
                ('movimiento_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.movimientocaja')),
                ('movimiento_cc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clientes.cuentacorrientecliente')),
                ('recarga_almuerzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='almuerzos.recargasaldoalmuerzo')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resolución de saldo',
                'verbose_name_plural': 'Resoluciones de saldo',
                'ordering': ['-fecha_solicitud', '-id_resolucion'],
            },
        ),
        migrations.AddConstraint(
            model_name='cierrecuentaalumno',
            constraint=models.UniqueConstraint(fields=('hijo', 'anio'), name='unique_cierre_cuenta_hijo_anio'),
        ),
        migrations.AddConstraint(
            model_name='resolucionsaldo',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='resolucion_monto_positivo'),
        ),
    ]
