# Generated by Django 4.2 on 2026-05-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('INVENTARIO', 'Inventario'), ('CUENTA_CORRIENTE', 'Cuenta Corriente'), ('ALMUERZOS', 'Almuerzos'), ('CAJA', 'Caja'), ('TRIBUTARIO', 'Tributario')], max_length=20)),
                ('frecuencia', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual'), ('PERSONALIZADO', 'Personalizado')], max_length=15)),
                ('query_sql', models.TextField(help_text='Consulta SQL base del reporte')),
                ('parametros', models.JSONField(default=dict, help_text='Parámetros configurables (fechas, filtros, etc.)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
