# Generated by Django 6.0.2 on 2026-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiMetricas',
            fields=[
                ('id_kpi', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('formula', models.TextField()),
                ('unidad', models.CharField(max_length=20)),
                ('valor_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('categoria', models.CharField(max_length=30)),
                ('frecuencia', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'kpi_metricas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id_dashboard', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('configuracion', models.JSONField()),
                ('es_publico', models.IntegerField()),
                ('predeterminado', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados')),
            ],
            options={
                'db_table': 'dashboards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantillasReporte',
            fields=[
                ('id_template', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('query_sql', models.TextField()),
                ('parametros', models.JSONField()),
                ('tipo_reporte', models.CharField(max_length=20)),
                ('frecuencia', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados')),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'db_table': 'plantillas_reporte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantillasTarea',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_tarea', models.CharField(max_length=30)),
                ('comando', models.TextField()),
                ('parametros', models.JSONField()),
                ('frecuencia', models.CharField(max_length=20)),
                ('cron', models.CharField(max_length=100)),
                ('timeout', models.IntegerField()),
                ('max_reintentos', models.IntegerField()),
                ('notif_exito', models.IntegerField()),
                ('notif_error', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados')),
            ],
            options={
                'db_table': 'plantillas_tarea',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EjecucionesTarea',
            fields=[
                ('id_ejecucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_seg', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('servidor', models.CharField(max_length=100)),
                ('parametros', models.JSONField()),
                ('ejecutado_por', models.ForeignKey(blank=True, db_column='ejecutado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados')),
                ('id_plantilla', models.ForeignKey(db_column='id_plantilla', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.plantillastarea')),
            ],
            options={
                'db_table': 'ejecuciones_tarea',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DestinatariosTarea',
            fields=[
                ('id_destinatario', models.AutoField(primary_key=True, serialize=False)),
                ('notif_inicio', models.IntegerField()),
                ('notif_fin', models.IntegerField()),
                ('notif_error', models.IntegerField()),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados')),
                ('id_plantilla', models.ForeignKey(db_column='id_plantilla', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.plantillastarea')),
            ],
            options={
                'db_table': 'destinatarios_tarea',
                'managed': True,
                'unique_together': {('id_plantilla', 'id_empleado')},
            },
        ),
        migrations.CreateModel(
            name='ValoresKpi',
            fields=[
                ('id_valor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notas', models.TextField(blank=True, null=True)),
                ('auto_calc', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('id_kpi', models.ForeignKey(db_column='id_kpi', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.kpimetricas')),
            ],
            options={
                'db_table': 'valores_kpi',
                'managed': True,
                'unique_together': {('id_kpi', 'fecha')},
            },
        ),
    ]
