# Generated by Django 6.0.2 on 2026-03-07 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        ('usuarios', '0003_alter_autenticacion2fa_backup_codes'),
    ]

    operations = [
        # created_at already exists in the DB (added before this migration was recorded)
        migrations.AddField(
            model_name='kpimetricas',
            name='frecuencia_actualizacion',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='kpimetricas',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='kpi_id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='kpimetricas',
            name='meta_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='kpimetricas',
            name='nombre_kpi',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='kpimetricas',
            name='query_sql',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='kpimetricas',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='plantillastarea',
            name='configuracion_envio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantillastarea',
            name='configuracion_programacion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destinatariostarea',
            name='notif_error',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destinatariostarea',
            name='notif_fin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destinatariostarea',
            name='notif_inicio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpimetricas',
            name='formula',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kpimetricas',
            name='frecuencia',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='kpimetricas',
            name='unidad',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantillastarea',
            name='notif_error',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plantillastarea',
            name='notif_exito',
            field=models.IntegerField(default=0),
        ),
    ]
