# Generated by Django 6.0.2 on 2026-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboards',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='destinatariostarea',
            name='id_empleado',
            field=models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='ejecucionestarea',
            name='ejecutado_por',
            field=models.ForeignKey(blank=True, db_column='ejecutado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='plantillasreporte',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='plantillastarea',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='ejecucionestarea',
            name='id_plantilla',
            field=models.ForeignKey(db_column='id_plantilla', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.plantillastarea'),
        ),
        migrations.AddField(
            model_name='destinatariostarea',
            name='id_plantilla',
            field=models.ForeignKey(db_column='id_plantilla', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.plantillastarea'),
        ),
        migrations.AddField(
            model_name='valoreskpi',
            name='id_kpi',
            field=models.ForeignKey(db_column='id_kpi', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.kpimetricas'),
        ),
        migrations.AlterUniqueTogether(
            name='destinatariostarea',
            unique_together={('id_plantilla', 'id_empleado')},
        ),
        migrations.AlterUniqueTogether(
            name='valoreskpi',
            unique_together={('id_kpi', 'fecha')},
        ),
    ]
