# Generated by Django 6.0.2 on 2026-03-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_kpimetricas_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillastarea',
            name='comando',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plantillastarea',
            name='cron',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantillastarea',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plantillastarea',
            name='frecuencia',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantillastarea',
            name='max_reintentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plantillastarea',
            name='parametros',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='plantillastarea',
            name='timeout',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plantillastarea',
            name='tipo_tarea',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
