# Generated by Django 6.0.2 on 2026-03-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_add_defaults_plantillastarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatariostarea',
            name='tipo_destinatario',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
