# Generated by Django 6.0.2 on 2026-03-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_add_destinatarios_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucionestarea',
            name='parametros',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ejecucionestarea',
            name='servidor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
