# Generated by Django 5.2.12 on 2026-03-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_add_ejecuciones_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpimetricas',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
