# Generated by Django 6.0.2 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_kpimetricas_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboards',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='kpimetricas',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='plantillasreporte',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='plantillastarea',
            name='activo',
        ),
        migrations.AddField(
            model_name='dashboards',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kpimetricas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plantillasreporte',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plantillastarea',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
