# Generated by Django 6.0.2 on 2026-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaOperaciones',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('operacion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_operacion', models.DateTimeField()),
                ('resultado', models.CharField(max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auditoria_operaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BloqueosCuenta',
            fields=[
                ('id_bloqueo', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_bloqueo', models.DateTimeField()),
                ('fecha_desbloqueo', models.DateTimeField(blank=True, null=True)),
                ('bloqueado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bloqueos_cuenta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena_hash', models.CharField(max_length=60)),
                ('fecha_ingreso', models.DateTimeField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Intentos2Fa',
            fields=[
                ('id_intento', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_ingresado', models.CharField(blank=True, max_length=10, null=True)),
                ('exitoso', models.IntegerField()),
                ('tipo_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_intento', models.DateTimeField()),
            ],
            options={
                'db_table': 'intentos_2fa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IntentosLogin',
            fields=[
                ('id_intento', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=45)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_intento', models.DateTimeField()),
                ('exitoso', models.IntegerField()),
                ('motivo_fallo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'intentos_login',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PatronesAcceso',
            fields=[
                ('id_patron', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('ip_address', models.CharField(max_length=45)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fin', models.TimeField(blank=True, null=True)),
                ('dias_semana', models.CharField(blank=True, max_length=50, null=True)),
                ('primera_deteccion', models.DateTimeField()),
                ('ultima_deteccion', models.DateTimeField()),
                ('frecuencia_accesos', models.IntegerField()),
                ('es_habitual', models.IntegerField()),
            ],
            options={
                'db_table': 'patrones_acceso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RenovacionesSesion',
            fields=[
                ('id_renovacion', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('session_key_anterior', models.CharField(blank=True, max_length=255, null=True)),
                ('session_key_nuevo', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_renovacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'renovaciones_sesion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SesionesActivas',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('ultima_actividad', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sesiones_activas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuariosWebClientes',
            fields=[
                ('id_cliente', models.OneToOneField(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='clientes.clientes')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena_hash', models.CharField(max_length=128)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuarios_web_clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaUsuariosWeb',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField()),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes')),
            ],
            options={
                'db_table': 'auditoria_usuarios_web',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Autenticacion2Fa',
            fields=[
                ('id_2fa', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('secret_key', models.CharField(max_length=32)),
                ('backup_codes', models.TextField(blank=True, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'autenticacion_2fa',
                'managed': True,
                'unique_together': {('usuario', 'tipo_usuario')},
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEmpleados',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField()),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados')),
            ],
            options={
                'db_table': 'auditoria_empleados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilesUsuario',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=20)),
                ('idioma', models.CharField(max_length=10)),
                ('timezone', models.CharField(max_length=50)),
                ('dashboard_config', models.JSONField()),
                ('menu_colapsado', models.IntegerField()),
                ('notif_email', models.IntegerField()),
                ('notif_push', models.IntegerField()),
                ('notif_desktop', models.IntegerField()),
                ('formato_fecha', models.CharField(max_length=20)),
                ('moneda', models.CharField(max_length=10)),
                ('config_adicional', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('id_empleado', models.OneToOneField(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados')),
            ],
            options={
                'db_table': 'perfiles_usuario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.roles'),
        ),
        migrations.CreateModel(
            name='TokensRecuperacion',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.IntegerField()),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('ip_solicitud', models.CharField(blank=True, max_length=45, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes')),
            ],
            options={
                'db_table': 'tokens_recuperacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuariosPortal',
            fields=[
                ('id_usuario_portal', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('email_verificado', models.IntegerField()),
                ('fecha_registro', models.DateTimeField()),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_cliente', models.OneToOneField(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes')),
            ],
            options={
                'db_table': 'usuarios_portal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TokensVerificacion',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_portal', models.ForeignKey(db_column='id_usuario_portal', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuariosportal')),
            ],
            options={
                'db_table': 'tokens_verificacion',
                'managed': True,
            },
        ),
    ]
