# Generated by Django 4.2 on 2026-05-14 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Correo electrónico (usado como nombre de usuario)', max_length=255, unique=True)),
                ('nombre', models.CharField(help_text='Nombre(s)', max_length=200)),
                ('apellido', models.CharField(help_text='Apellido(s)', max_length=200)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CAJERO', 'Cajero'), ('COCINA', 'Cocina'), ('CLIENTE_WEB', 'Cliente Portal Web')], default='CAJERO', help_text='Rol del usuario en el sistema', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='False si el usuario está deshabilitado')),
                ('is_staff', models.BooleanField(default=False, help_text='Puede acceder al admin de Django')),
                ('email_verificado', models.BooleanField(default=False, help_text='Email verificado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, help_text='Fecha de desactivación', null=True)),
                ('cliente', models.OneToOneField(blank=True, help_text='Cliente asociado (solo para usuarios del portal web)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_portal', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='IntentoLogin',
            fields=[
                ('id_intento', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email ingresado en el intento', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('motivo_fallo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'db_table': 'intentos_login',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_permiso', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('modulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
                'ordering': ['modulo', 'codigo_permiso'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TokenVerificacion',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(default='email_verification', max_length=50)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_verificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Verificación',
                'verbose_name_plural': 'Tokens de Verificación',
                'db_table': 'tokens_verificacion',
            },
        ),
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Recuperación',
                'verbose_name_plural': 'Tokens de Recuperación',
                'db_table': 'tokens_recuperacion',
            },
        ),
        migrations.CreateModel(
            name='SesionActiva',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión Activa',
                'verbose_name_plural': 'Sesiones Activas',
                'db_table': 'sesiones_activas',
            },
        ),
        migrations.CreateModel(
            name='RenovacionSesion',
            fields=[
                ('id_renovacion', models.AutoField(primary_key=True, serialize=False)),
                ('session_key_anterior', models.CharField(blank=True, max_length=255, null=True)),
                ('session_key_nuevo', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_renovacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Renovación de Sesión',
                'verbose_name_plural': 'Renovaciones de Sesión',
                'db_table': 'renovaciones_sesion',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(default='claro', max_length=20)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('timezone', models.CharField(default='America/Asuncion', max_length=50)),
                ('formato_fecha', models.CharField(default='d/m/Y', max_length=20)),
                ('moneda', models.CharField(default='PYG', max_length=10)),
                ('notif_email', models.BooleanField(default=True)),
                ('notif_push', models.BooleanField(default=True)),
                ('notif_desktop', models.BooleanField(default=False)),
                ('dashboard_config', models.JSONField(blank=True, default=dict)),
                ('menu_colapsado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'perfiles_usuario',
            },
        ),
        migrations.CreateModel(
            name='PatronAcceso',
            fields=[
                ('id_patron', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fin', models.TimeField(blank=True, null=True)),
                ('dias_semana', models.CharField(blank=True, max_length=50, null=True)),
                ('primera_deteccion', models.DateTimeField(auto_now_add=True)),
                ('ultima_deteccion', models.DateTimeField(auto_now=True)),
                ('frecuencia_accesos', models.IntegerField(default=1)),
                ('es_habitual', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrones_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patrón de Acceso',
                'verbose_name_plural': 'Patrones de Acceso',
                'db_table': 'patrones_acceso',
            },
        ),
        migrations.CreateModel(
            name='Intento2FA',
            fields=[
                ('id_intento', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('codigo_ingresado', models.CharField(blank=True, max_length=10, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_2fa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento 2FA',
                'verbose_name_plural': 'Intentos 2FA',
                'db_table': 'intentos_2fa',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre(s)', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido(s)', max_length=100)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de ingreso')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, default='Paraguay', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, help_text='True=Activo, False=Inactivo')),
                ('id_rol', models.ForeignKey(db_column='id_rol', help_text='Rol asignado', on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['apellido', 'nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BloqueoCuenta',
            fields=[
                ('id_bloqueo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True)),
                ('fecha_desbloqueo', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True, help_text='True si sigue bloqueado')),
                ('bloqueado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueo de Cuenta',
                'verbose_name_plural': 'Bloqueos de Cuentas',
                'db_table': 'bloqueos_cuenta',
            },
        ),
        migrations.CreateModel(
            name='Autenticacion2FA',
            fields=[
                ('id_2fa', models.AutoField(primary_key=True, serialize=False)),
                ('secret_key', models.CharField(max_length=64)),
                ('backup_codes', models.JSONField(blank=True, default=list)),
                ('habilitado', models.BooleanField(default=False)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_2fa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autenticación 2FA',
                'verbose_name_plural': 'Autenticaciones 2FA',
                'db_table': 'autenticacion_2fa',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaUsuarioWeb',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_web', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Auditoría de Usuario Web',
                'verbose_name_plural': 'Auditorías de Usuarios Web',
                'db_table': 'auditoria_usuarios_web',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaOperacion',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('operacion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(default='EXITO', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Operación',
                'verbose_name_plural': 'Auditorías de Operaciones',
                'db_table': 'auditoria_operaciones',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEmpleado',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='usuarios.empleado')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Empleado',
                'verbose_name_plural': 'Auditorías de Empleados',
                'db_table': 'auditoria_empleados',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='empleado_legacy',
            field=models.OneToOneField(blank=True, help_text='Registro de empleado asociado (datos de personal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_django', to='usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, db_column='asignado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, to='usuarios.permiso')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'Rol-Permiso',
                'verbose_name_plural': 'Roles-Permisos',
                'db_table': 'roles_permisos',
                'managed': True,
                'unique_together': {('id_rol', 'id_permiso')},
            },
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['email'], name='idx_empleados_email'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['estado', 'id_rol'], name='idx_empleados_estado_rol'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['apellido', 'nombre'], name='idx_empleados_nombre'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='idx_usuarios_email'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='idx_usuarios_rol'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_active'], name='idx_usuarios_activo'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['apellido', 'nombre'], name='idx_usuarios_nombre'),
        ),
    ]
