# Generated by Django 6.0.2 on 2026-03-01 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_permiso', models.CharField(help_text="Código único del permiso (ej: 'ventas.crear')", max_length=100, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del permiso', max_length=100)),
                ('modulo', models.CharField(help_text='Módulo al que pertenece (ventas, inventario, usuarios, etc)', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
                'ordering': ['modulo', 'codigo_permiso'],
            },
        ),
        migrations.CreateModel(
            name='RolesPermisos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, db_column='asignado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleados')),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, to='usuarios.permisos')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='usuarios.roles')),
            ],
            options={
                'verbose_name': 'Rol-Permiso',
                'verbose_name_plural': 'Roles-Permisos',
                'db_table': 'roles_permisos',
                'unique_together': {('id_rol', 'id_permiso')},
            },
        ),
    ]
