# Generated by Django 4.2 on 2026-07-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_trigger_patron_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_contrasena',
            field=models.BooleanField(default=False, help_text='Obliga al usuario a cambiar su contraseña en el próximo ingreso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CAJERO', 'Cajero'), ('SUPERVISOR', 'Supervisor'), ('COBRADOR', 'Cobrador'), ('COCINA', 'Cocina'), ('CLIENTE_WEB', 'Cliente Portal Web')], default='CAJERO', help_text='Rol del usuario en el sistema', max_length=20),
        ),
    ]
