# Generated by Django 6.0.2 on 2026-03-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_permisos_rolespermisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autenticacion2fa',
            name='backup_codes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
