# Generated by Django 5.2.16 on 2026-07-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_add_debe_cambiar_contrasena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ['id_perfil'], 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': True, 'ordering': ['nombre_rol'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rolpermiso',
            options={'managed': True, 'ordering': ['id_rol', 'id_permiso'], 'verbose_name': 'Rol-Permiso', 'verbose_name_plural': 'Roles-Permisos'},
        ),
    ]
