# Generated by Django 6.0.2 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_autenticacion2fa_backup_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloqueoscuenta',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuariosportal',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuarioswebclientes',
            name='activo',
        ),
        migrations.AddField(
            model_name='bloqueoscuenta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permisos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuariosportal',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarioswebclientes',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
