# Generated by Django 5.2.16 on 2026-08-12 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfilusuario_options_alter_rol_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialWebAuthn',
            fields=[
                ('id_credencial', models.AutoField(primary_key=True, serialize=False)),
                ('credential_id', models.CharField(max_length=255, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('nombre_dispositivo', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales_webauthn', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credencial WebAuthn',
                'verbose_name_plural': 'Credenciales WebAuthn',
                'db_table': 'credenciales_webauthn',
            },
        ),
    ]
