# Generated by Django 5.2.16 on 2026-08-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_credencialwebauthn'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ci_ruc',
            field=models.CharField(blank=True, help_text='CI o RUC — usado para el login del personal interno (roles no CLIENTE_WEB)', max_length=20, null=True, unique=True),
        ),
    ]
