# Generated by Django 6.0.2 on 2026-03-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_portal_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosportal',
            options={'managed': True, 'verbose_name': 'Usuario Portal', 'verbose_name_plural': 'Usuarios Portal'},
        ),
    ]
