# Generated by Django 5.2.16 on 2026-08-19 22:14
"""
Carga el CI/RUC del personal interno existente, requerido para el nuevo
login por CI/RUC en /login, /pos y /cobranzas. Usa filter().update() por
email: si una cuenta no existe en un entorno dado (dev/test), es un no-op.
"""
from django.db import migrations

CI_RUC_POR_EMAIL = {
    "admin@cantinatita.com": "531616",
    "lucaspy14@gmail.com": "2447330",
    "agus.caja@cantinatita.com": "1111111",
    "cobrador@cantinatita.com": "2222222",
    "super@cantinatita.com": "3333333",
    "visita.1@cantinatita.com": "4444444",
}


def cargar_ci_ruc(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    for email, ci_ruc in CI_RUC_POR_EMAIL.items():
        Usuario.objects.filter(email=email).update(ci_ruc=ci_ruc)


def revertir(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    Usuario.objects.filter(email__in=CI_RUC_POR_EMAIL.keys()).update(ci_ruc=None)


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_ci_ruc'),
    ]

    operations = [
        migrations.RunPython(cargar_ci_ruc, revertir),
    ]
