# Generated by Django 6.0.2 on 2026-04-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_portal_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='contrasena_hash',
            field=models.CharField(max_length=256),
        ),
    ]
