# Generated by Django 5.2.16 on 2026-08-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_backfill_ci_ruc_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento (opcional) — se usa para la alerta de cumpleaños del personal', null=True),
        ),
    ]
