# Generated by Django 6.0.2 on 2026-04-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_expand_contrasena_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'managed': True, 'ordering': ['apellido', 'nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddIndex(
            model_name='empleados',
            index=models.Index(fields=['usuario'], name='idx_empleados_usuario'),
        ),
        migrations.AddIndex(
            model_name='empleados',
            index=models.Index(fields=['email'], name='idx_empleados_email'),
        ),
        migrations.AddIndex(
            model_name='empleados',
            index=models.Index(fields=['estado', 'id_rol'], name='idx_empleados_estado_rol'),
        ),
        migrations.AddIndex(
            model_name='empleados',
            index=models.Index(fields=['apellido', 'nombre'], name='idx_empleados_nombre'),
        ),
    ]
