# Generated by Django 5.2.16 on 2026-09-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoriausuarioweb',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='AuditoriaEmpleado',
        ),
        migrations.DeleteModel(
            name='AuditoriaUsuarioWeb',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
