# Generated by Django 6.0.2 on 2026-05-07 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_empleados_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisos',
            options={'managed': True, 'ordering': ['modulo', 'codigo_permiso'], 'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterModelOptions(
            name='rolespermisos',
            options={'managed': True, 'verbose_name': 'Rol-Permiso', 'verbose_name_plural': 'Roles-Permisos'},
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellido',
            field=models.CharField(help_text='Apellido(s) del empleado', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad de residencia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='contrasena_hash',
            field=models.CharField(help_text='Hash de la contraseña', max_length=256),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección de domicilio', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='email',
            field=models.CharField(blank=True, help_text='Correo electrónico', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estado',
            field=models.BooleanField(default=True, help_text='True=Activo, False=Inactivo'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el empleado dejó la empresa', null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='fecha_ingreso',
            field=models.DateTimeField(help_text='Fecha de ingreso del empleado a la empresa'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', help_text='Rol asignado al empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.roles'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(help_text='Nombre(s) del empleado', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='pais',
            field=models.CharField(blank=True, help_text='País de residencia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='usuario',
            field=models.CharField(help_text='Nombre de usuario para login', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='codigo_permiso',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='modulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
