# Generated by Django 5.2.16 on 2026-09-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_auditoriausuarioweb_cliente_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolpermiso',
            name='id_permiso',
        ),
        migrations.RemoveField(
            model_name='rolpermiso',
            name='asignado_por',
        ),
        migrations.RemoveField(
            model_name='rolpermiso',
            name='id_rol',
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='RolPermiso',
        ),
    ]
