# Generated by Django 5.2.16 on 2026-09-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_rolpermiso_id_permiso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenrecuperacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tokenverificacion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='RenovacionSesion',
        ),
        migrations.DeleteModel(
            name='TokenRecuperacion',
        ),
        migrations.DeleteModel(
            name='TokenVerificacion',
        ),
    ]
