# Generated by Django 5.2.16 on 2026-09-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_rename_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
