# Generated by Django 5.2.16 on 2026-09-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_remove_ciudad_pais_remove_cliente_ciudad_catalogo_and_more'),
        ('usuarios', '0013_alter_usuario_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='empleado_legacy',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento (opcional) — se usa para la alerta de cumpleaños del personal', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empleado',
            field=models.OneToOneField(blank=True, help_text='Empleado al que pertenece este acceso al sistema (roles de personal interno)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='usuarios.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='clientes.ciudad'),
        ),
    ]
