# Generated by Django 5.2.16 on 2026-09-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_remove_empleado_pais_remove_usuario_empleado_legacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ci',
            field=models.CharField(blank=True, help_text='Cédula de identidad del empleado', max_length=20, null=True, unique=True),
        ),
    ]
