# Generated by Django 6.0.2 on 2026-04-16 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0008_clientes_idx_clientes_email_and_more'),
        ('core', '0011_configuraciones_adicionales'),
        ('usuarios', '0008_alter_empleados_options_and_more'),
        ('ventas', '0008_alter_pagosventa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosClientes',
            fields=[
                ('id_pago_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total del pago', max_digits=12)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del pago')),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia/comprobante', max_length=100, null=True)),
                ('banco_emisor', models.CharField(blank=True, help_text='Banco emisor (transferencia/cheque)', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del pago', null=True)),
                ('estado', models.CharField(default='Confirmado', help_text='Estado del pago: Confirmado, Anulado', max_length=20)),
                ('id_cierre', models.BigIntegerField(blank=True, help_text='ID del cierre de caja asociado', null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', help_text='Cliente que realiza el pago', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to='clientes.clientes')),
                ('id_empleado_cajero', models.ForeignKey(db_column='id_empleado_cajero', help_text='Empleado que registró el pago', on_delete=django.db.models.deletion.PROTECT, to='usuarios.empleados')),
                ('id_medio_pago', models.ForeignKey(db_column='id_medio_pago', help_text='Medio de pago utilizado', on_delete=django.db.models.deletion.PROTECT, to='core.mediospago')),
            ],
            options={
                'verbose_name': 'Pago de Cliente',
                'verbose_name_plural': 'Pagos de Clientes',
                'db_table': 'pagos_clientes',
                'ordering': ['-fecha_pago'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AplicacionPagosClientes',
            fields=[
                ('id_aplicacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto_aplicado', models.DecimalField(decimal_places=2, help_text='Monto aplicado a esta factura', max_digits=12)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de aplicación')),
                ('id_venta', models.ForeignKey(db_column='id_venta', help_text='Venta a la que se aplica el pago', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_aplicados', to='ventas.ventas')),
                ('id_pago_cliente', models.ForeignKey(db_column='id_pago_cliente', help_text='Pago al que pertenece esta aplicación', on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cobros.pagosclientes')),
            ],
            options={
                'verbose_name': 'Aplicación de Pago',
                'verbose_name_plural': 'Aplicaciones de Pagos',
                'db_table': 'aplicacion_pagos_clientes',
                'ordering': ['-fecha_aplicacion'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='pagosclientes',
            index=models.Index(fields=['id_cliente', 'fecha_pago'], name='idx_pagos_cli_cliente'),
        ),
        migrations.AddIndex(
            model_name='pagosclientes',
            index=models.Index(fields=['fecha_pago'], name='idx_pagos_cli_fecha'),
        ),
        migrations.AddIndex(
            model_name='pagosclientes',
            index=models.Index(fields=['estado'], name='idx_pagos_cli_estado'),
        ),
        migrations.AddIndex(
            model_name='pagosclientes',
            index=models.Index(fields=['id_empleado_cajero', 'fecha_pago'], name='idx_pagos_cli_cajero'),
        ),
        migrations.AddIndex(
            model_name='aplicacionpagosclientes',
            index=models.Index(fields=['id_pago_cliente'], name='idx_aplic_pago_cli'),
        ),
        migrations.AddIndex(
            model_name='aplicacionpagosclientes',
            index=models.Index(fields=['id_venta'], name='idx_aplic_venta'),
        ),
    ]
