# Generated by Django 4.2 on 2026-05-14 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cargado', models.DecimalField(decimal_places=0, help_text='Monto en Guaraníes', max_digits=12)),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('comision', models.DecimalField(decimal_places=0, default=0, help_text='Comisión cobrada en Guaraníes', max_digits=12)),
                ('total_cobrado', models.DecimalField(blank=True, decimal_places=0, help_text='Total cobrado (monto + comisión)', max_digits=12, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('pay_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tx_id', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_comprobante_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carga de Saldo',
                'verbose_name_plural': 'Cargas de Saldo',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consumo', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_consumido', models.DecimalField(decimal_places=0, help_text='Monto en Guaraníes', max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=0, max_digits=12)),
                ('saldo_posterior', models.DecimalField(decimal_places=0, max_digits=12)),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consumo de Tarjeta',
                'verbose_name_plural': 'Consumos de Tarjetas',
                'ordering': ['-fecha_consumo'],
            },
        ),
        migrations.CreateModel(
            name='LimiteTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('VENTA', 'Venta'), ('DESCUENTO', 'Aplicar descuento'), ('NOTA_CREDITO_CLIENTE', 'Nota de crédito a cliente'), ('NOTA_CREDITO_PROVEEDOR', 'Nota de crédito de proveedor'), ('AJUSTE_INVENTARIO', 'Ajuste de inventario'), ('EXCEDER_CREDITO', 'Exceder límite de crédito'), ('ANULAR_VENTA', 'Anular venta'), ('RETIRO_CAJA', 'Retiro de caja'), ('DEVOLUCION', 'Procesar devolución')], max_length=30)),
                ('monto_maximo', models.DecimalField(decimal_places=0, help_text='Monto máximo en Guaraníes sin autorización', max_digits=12)),
                ('requiere_autorizacion_doble', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Límite de Transacción',
                'verbose_name_plural': 'Límites de Transacciones',
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('genera_comision', models.BooleanField(default=False)),
                ('requiere_validacion', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
            },
        ),
        migrations.CreateModel(
            name='RegistroAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('motivo', models.TextField()),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Autorización',
                'verbose_name_plural': 'Registro de Autorizaciones',
                'ordering': ['-fecha_autorizacion'],
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('nro_tarjeta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('saldo_actual', models.DecimalField(decimal_places=0, default=0, help_text='Saldo en Guaraníes', max_digits=12)),
                ('limite_credito', models.DecimalField(decimal_places=0, default=0, help_text='Límite de crédito en Guaraníes', max_digits=12)),
                ('permite_saldo_negativo', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('BLOQUEADA', 'Bloqueada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=15)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('saldo_alerta', models.DecimalField(blank=True, decimal_places=0, help_text='Umbral para notificación de saldo bajo', max_digits=12, null=True)),
                ('notificar_saldo_bajo', models.BooleanField(default=True)),
                ('ultima_notificacion_saldo', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
            },
        ),
        migrations.CreateModel(
            name='TarjetaAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(max_length=50, unique=True)),
                ('tipo_autorizacion', models.CharField(max_length=15)),
                ('puede_anular_almuerzos', models.BooleanField(default=False)),
                ('puede_anular_ventas', models.BooleanField(default=False)),
                ('puede_anular_recargas', models.BooleanField(default=False)),
                ('puede_modificar_precios', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarjeta de Autorización',
                'verbose_name_plural': 'Tarjetas de Autorización',
            },
        ),
    ]
