# Generated by Django 6.0.2 on 2026-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheConfiguracion',
            fields=[
                ('id_cache', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('ttl_segundos', models.IntegerField()),
                ('max_size_mb', models.IntegerField()),
                ('tipo_cache', models.CharField(max_length=20)),
                ('auto_invalidate', models.IntegerField()),
                ('eventos_invalid', models.JSONField()),
                ('activo', models.BooleanField(default=True)),
                ('hits', models.BigIntegerField()),
                ('misses', models.BigIntegerField()),
                ('ultima_limpieza', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cache_configuracion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('valor_defecto', models.TextField()),
                ('requerido', models.IntegerField()),
                ('validacion', models.CharField(max_length=500)),
                ('valores_permitidos', models.JSONField()),
                ('valor_min', models.CharField(max_length=100)),
                ('valor_max', models.CharField(max_length=100)),
                ('requiere_reinicio', models.IntegerField()),
                ('solo_superuser', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'configuracion_sistema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConsumosTarjeta',
            fields=[
                ('id_consumo', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_consumo', models.DateTimeField()),
                ('monto_consumido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'consumos_tarjeta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MediosPago',
            fields=[
                ('id_medio_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('genera_comision', models.IntegerField()),
                ('requiere_validacion', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'db_table': 'medios_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('nro_tarjeta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('saldo_alerta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('permite_saldo_negativo', models.IntegerField()),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notificar_saldo_bajo', models.IntegerField()),
                ('ultima_notificacion_saldo', models.DateTimeField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'db_table': 'tarjetas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TarjetasAutorizacion',
            fields=[
                ('id_tarjeta_autorizacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_barra', models.CharField(max_length=50, unique=True)),
                ('tipo_autorizacion', models.CharField(max_length=15)),
                ('puede_anular_almuerzos', models.IntegerField()),
                ('puede_anular_ventas', models.IntegerField()),
                ('puede_anular_recargas', models.IntegerField()),
                ('puede_modificar_precios', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tarjeta de Autorización',
                'verbose_name_plural': 'Tarjetas de Autorización',
                'db_table': 'tarjetas_autorizacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransaccionesOnline',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('referencia_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('id_transaccion_externa', models.CharField(blank=True, max_length=255, null=True)),
                ('datos_extra', models.TextField(blank=True, null=True)),
                ('fecha_transaccion', models.DateTimeField()),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'transacciones_online',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CargasSaldo',
            fields=[
                ('id_carga', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_carga', models.DateTimeField()),
                ('monto_cargado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('pay_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tx_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('custom_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('id_nota', models.BigIntegerField(blank=True, null=True)),
                ('id_cliente_origen', models.ForeignKey(blank=True, db_column='id_cliente_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes')),
            ],
            options={
                'db_table': 'cargas_saldo',
                'managed': True,
            },
        ),
    ]
