# Generated by Django 4.2 on 2026-05-14 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('ventas', '0001_initial'),
        ('compras', '0002_initial'),
        ('usuarios', '0001_initial'),
        ('inventario', '0002_initial'),
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetaautorizacion',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas_autorizacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='hijo',
            field=models.OneToOneField(help_text='Estudiante dueño de la tarjeta', on_delete=django.db.models.deletion.PROTECT, related_name='tarjeta', to='clientes.hijo'),
        ),
        migrations.AddField(
            model_name='registroautorizacion',
            name='ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ajusteinventario'),
        ),
        migrations.AddField(
            model_name='registroautorizacion',
            name='autorizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_otorgadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroautorizacion',
            name='autorizador_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_dobles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroautorizacion',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.compra'),
        ),
        migrations.AddField(
            model_name='registroautorizacion',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroautorizacion',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='limitetransaccion',
            name='configurado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limites_configurados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limitetransaccion',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='limites_transaccion', to='usuarios.rol'),
        ),
        migrations.AddField(
            model_name='limitetransaccion',
            name='roles_autorizadores',
            field=models.ManyToManyField(blank=True, related_name='limites_autorizables', to='usuarios.rol'),
        ),
        migrations.AddField(
            model_name='consumotarjeta',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumos_tarjeta_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumotarjeta',
            name='tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='core.tarjeta'),
        ),
        migrations.AddField(
            model_name='cargasaldo',
            name='cliente_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas_saldo', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='cargasaldo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas_procesadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargasaldo',
            name='supervisor_aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargasaldo',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='core.tarjeta'),
        ),
        migrations.AddField(
            model_name='cargasaldo',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_saldo', to='ventas.venta'),
        ),
        migrations.AddIndex(
            model_name='registroautorizacion',
            index=models.Index(fields=['solicitante', '-fecha_autorizacion'], name='core_regist_solicit_071c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='registroautorizacion',
            index=models.Index(fields=['autorizador', '-fecha_autorizacion'], name='core_regist_autoriz_0412ab_idx'),
        ),
        migrations.AddIndex(
            model_name='registroautorizacion',
            index=models.Index(fields=['tipo_operacion', '-fecha_autorizacion'], name='core_regist_tipo_op_3463ac_idx'),
        ),
        migrations.AddIndex(
            model_name='limitetransaccion',
            index=models.Index(fields=['rol', 'tipo_operacion'], name='core_limite_rol_id_2db7be_idx'),
        ),
        migrations.AddIndex(
            model_name='limitetransaccion',
            index=models.Index(fields=['tipo_operacion', 'activo'], name='core_limite_tipo_op_328657_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='limitetransaccion',
            unique_together={('rol', 'tipo_operacion')},
        ),
    ]
