# Generated by Django 6.0.2 on 2026-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='consumostarjeta',
            name='id_empleado_registro',
            field=models.ForeignKey(blank=True, db_column='id_empleado_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='tarjetas',
            name='id_hijo',
            field=models.OneToOneField(db_column='id_hijo', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.hijos'),
        ),
        migrations.AddField(
            model_name='consumostarjeta',
            name='nro_tarjeta',
            field=models.ForeignKey(db_column='nro_tarjeta', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tarjetas'),
        ),
        migrations.AddField(
            model_name='cargassaldo',
            name='nro_tarjeta',
            field=models.ForeignKey(db_column='nro_tarjeta', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tarjetas'),
        ),
        migrations.AddField(
            model_name='tarjetasautorizacion',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='transaccionesonline',
            name='id_usuario_portal',
            field=models.ForeignKey(blank=True, db_column='id_usuario_portal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuariosportal'),
        ),
        migrations.AddField(
            model_name='transaccionesonline',
            name='nro_tarjeta',
            field=models.ForeignKey(blank=True, db_column='nro_tarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tarjetas'),
        ),
    ]
