# Generated by Django 6.0.2 on 2026-03-01 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('core', '0001_initial'),
        ('inventario', '0004_lotesproducto_alertasvencimiento_and_more'),
        ('usuarios', '0001_initial'),
        ('ventas', '0002_agregar_comision_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitesTransaccion',
            fields=[
                ('id_limite', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(choices=[('venta', 'Venta'), ('descuento', 'Aplicar descuento'), ('nota_credito_cliente', 'Nota de crédito a cliente'), ('nota_credito_proveedor', 'Nota de crédito de proveedor'), ('ajuste_inventario', 'Ajuste de inventario'), ('exceder_credito', 'Exceder límite de crédito cliente'), ('anular_venta', 'Anular venta'), ('retiro_caja', 'Retiro de caja'), ('devolucion', 'Procesar devolución')], help_text='Tipo de operación a controlar', max_length=50)),
                ('monto_maximo_sin_autorizacion', models.DecimalField(decimal_places=2, help_text='Monto máximo que el rol puede procesar sin autorización', max_digits=12)),
                ('requiere_autorizacion_doble', models.BooleanField(default=False, help_text='Requiere autorización de dos supervisores diferentes')),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_empleado_configurador', models.ForeignKey(blank=True, db_column='id_empleado_configurador', help_text='Quién configuró este límite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados')),
                ('id_rol', models.ForeignKey(db_column='id_rol', help_text='Rol al que aplica este límite', on_delete=django.db.models.deletion.DO_NOTHING, related_name='limites_transaccion', to='usuarios.roles')),
                ('roles_autorizadores', models.ManyToManyField(blank=True, help_text='Roles que pueden autorizar esta operación', related_name='roles_autorizados_para', to='usuarios.roles')),
            ],
            options={
                'verbose_name': 'Límite de Transacción',
                'verbose_name_plural': 'Límites de Transacciones',
                'db_table': 'limites_transaccion',
                'managed': True,
                'indexes': [models.Index(fields=['id_rol', 'tipo_operacion'], name='limites_tra_id_rol_699257_idx'), models.Index(fields=['tipo_operacion', 'activo'], name='limites_tra_tipo_op_7e1cad_idx')],
                'unique_together': {('id_rol', 'tipo_operacion')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAutorizaciones',
            fields=[
                ('id_autorizacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField(help_text='Justificación de por qué se autorizó')),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('id_ajuste', models.ForeignKey(blank=True, db_column='id_ajuste', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.ajustesinventario')),
                ('id_compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras')),
                ('id_empleado_autorizador', models.ForeignKey(db_column='id_empleado_autorizador', help_text='Quien autoriza (supervisor/gerente)', on_delete=django.db.models.deletion.DO_NOTHING, related_name='autorizaciones_otorgadas', to='usuarios.empleados')),
                ('id_empleado_autorizador_2', models.ForeignKey(blank=True, db_column='id_empleado_autorizador_2', help_text='Segundo autorizador (si requiere doble autorización)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autorizaciones_dobles', to='usuarios.empleados')),
                ('id_empleado_solicitante', models.ForeignKey(db_column='id_empleado_solicitante', help_text='Quien solicita la autorización', on_delete=django.db.models.deletion.DO_NOTHING, related_name='autorizaciones_solicitadas', to='usuarios.empleados')),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas')),
            ],
            options={
                'verbose_name': 'Registro de Autorización',
                'verbose_name_plural': 'Registro de Autorizaciones',
                'db_table': 'registro_autorizaciones',
                'ordering': ['-fecha_autorizacion'],
                'managed': True,
                'indexes': [models.Index(fields=['id_empleado_solicitante', '-fecha_autorizacion'], name='registro_au_id_empl_448a16_idx'), models.Index(fields=['id_empleado_autorizador', '-fecha_autorizacion'], name='registro_au_id_empl_c436cc_idx'), models.Index(fields=['tipo_operacion', '-fecha_autorizacion'], name='registro_au_tipo_op_44f2ac_idx')],
            },
        ),
    ]
