# Generated by Django 4.2 on 2026-05-14 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('RECARGA', 'Recarga'), ('CONSUMO', 'Consumo'), ('AJUSTE', 'Ajuste'), ('REVERSO', 'Reverso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=0, help_text='Monto en Guaraníes', max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=0, max_digits=12)),
                ('saldo_resultante', models.DecimalField(decimal_places=0, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_tarjeta', to='core.cargasaldo')),
                ('consumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_tarjeta', to='core.consumotarjeta')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_tarjeta_creados', to=settings.AUTH_USER_MODEL)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.tarjeta')),
            ],
            options={
                'verbose_name': 'Movimiento de Tarjeta',
                'verbose_name_plural': 'Movimientos de Tarjetas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='movimientotarjeta',
            index=models.Index(fields=['tarjeta', 'fecha'], name='core_movimi_tarjeta_0a1d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientotarjeta',
            index=models.Index(fields=['tarjeta', 'tipo'], name='core_movimi_tarjeta_985605_idx'),
        ),
    ]
