# Generated by Django 6.0.2 on 2026-03-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expand_cargas_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargassaldo',
            name='codigo_referencia_interno',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='comision_aplicada',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='fecha_aprobacion',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='id_factura',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='imagen_comprobante',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='ip_origen',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='motivo_rechazo',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='numero_comprobante_externo',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='porcentaje_comision',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='referencia_externa',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='requiere_validacion_supervisor',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='supervisor_aprobador',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='total_cobrado',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='usuario_responsable',
        ),
        migrations.RemoveField(
            model_name='cargassaldo',
            name='webhook_payload',
        ),
        migrations.AlterField(
            model_name='cargassaldo',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
