# Generated by Django 4.2 on 2026-05-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movimientotarjeta_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movimientotarjeta',
            new_name='idx_mov_tarj_fecha',
            old_name='core_movimi_tarjeta_0a1d2b_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientotarjeta',
            new_name='idx_mov_tarj_tipo',
            old_name='core_movimi_tarjeta_985605_idx',
        ),
    ]
