# Generated by Django 4.2 on 2026-05-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_core_movimi_tarjeta_0a1d2b_idx_idx_mov_tarj_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediopago',
            name='genera_comision',
        ),
    ]
