# Generated by Django 4.2 on 2026-05-18 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0005_historicalfactura'),
        ('ventas', '0001_initial'),
        ('core', '0006_factura_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCargaSaldo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('monto_cargado', models.DecimalField(decimal_places=0, help_text='Monto en Guaraníes', max_digits=12)),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('comision', models.DecimalField(decimal_places=0, default=0, help_text='Comisión cobrada en Guaraníes', max_digits=12)),
                ('total_cobrado', models.DecimalField(blank=True, decimal_places=0, help_text='Total cobrado (monto + comisión)', max_digits=12, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('pay_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tx_id', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_comprobante_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente_origen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
                ('factura', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabilidad.factura')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supervisor_aprobador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tarjeta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tarjeta')),
                ('venta', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'historical Carga de Saldo',
                'verbose_name_plural': 'historical Cargas de Saldo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
