# Generated by Django 6.0.2 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_legacy_cargassaldo_fields'),
        ('usuarios', '0004_rename_activo_to_estado'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='limitestransaccion',
            name='limites_tra_tipo_op_7e1cad_idx',
        ),
        migrations.RemoveField(
            model_name='cacheconfiguracion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='mediospago',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tarjetasautorizacion',
            name='activo',
        ),
        migrations.AddField(
            model_name='cacheconfiguracion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='limitestransaccion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mediospago',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarjetasautorizacion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='limitestransaccion',
            index=models.Index(fields=['tipo_operacion', 'estado'], name='limites_tra_tipo_op_cad906_idx'),
        ),
        migrations.RemoveField(
            model_name='limitestransaccion',
            name='activo',
        ),
    ]
