# Generated by Django 4.2 on 2026-05-18 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_historicalcliente'),
        ('core', '0007_historicalcargasaldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTarjeta',
            fields=[
                ('nro_tarjeta', models.CharField(db_index=True, max_length=20)),
                ('codigo_barras', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('saldo_actual', models.DecimalField(decimal_places=0, default=0, help_text='Saldo en Guaraníes', max_digits=12)),
                ('limite_credito', models.DecimalField(decimal_places=0, default=0, help_text='Límite de crédito en Guaraníes', max_digits=12)),
                ('permite_saldo_negativo', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('BLOQUEADA', 'Bloqueada'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=15)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('saldo_alerta', models.DecimalField(blank=True, decimal_places=0, help_text='Umbral para notificación de saldo bajo', max_digits=12, null=True)),
                ('notificar_saldo_bajo', models.BooleanField(default=True)),
                ('ultima_notificacion_saldo', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('hijo', models.ForeignKey(blank=True, db_constraint=False, help_text='Estudiante dueño de la tarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.hijo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tarjeta',
                'verbose_name_plural': 'historical Tarjetas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
