# Generated by Django 4.2 on 2026-05-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_historicaltarjeta'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cargasaldo',
            index=models.Index(condition=models.Q(('estado', 'PENDIENTE')), fields=['tarjeta', 'fecha_carga'], name='idx_cargasaldo_pendientes'),
        ),
    ]
