"""
Migration 0010: configuraciones adicionales profesionales.

Agrega configuraciones para: Impresoras, Seguridad, Facturación, Reportes, Sistema.
"""
from django.db import migrations
from django.utils import timezone


CONFIGURACIONES = [
    # ── Impresoras ────────────────────────────────────────────────────────────
    {
        "clave": "IMPRESORA_TICKET_IP",
        "valor": "192.168.1.100",
        "tipo": "texto",
        "categoria": "Impresoras",
        "descripcion": "IP de la impresora térmica para tickets de venta (POS)",
        "valor_defecto": "192.168.1.100",
        "requerido": False,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "IMPRESORA_TICKET_PUERTO",
        "valor": "9100",
        "tipo": "entero",
        "categoria": "Impresoras",
        "descripcion": "Puerto TCP de la impresora térmica de tickets",
        "valor_defecto": "9100",
        "requerido": False,
        "validacion": "min:1,max:65535",
        "valores_permitidos": [],
        "valor_min": "1",
        "valor_max": "65535",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "IMPRESORA_TICKET_ANCHO",
        "valor": "80",
        "tipo": "entero",
        "categoria": "Impresoras",
        "descripcion": "Ancho del papel de tickets en mm (58 o 80)",
        "valor_defecto": "80",
        "requerido": False,
        "validacion": "",
        "valores_permitidos": ["58", "80"],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "IMPRESORA_FACTURA_IP",
        "valor": "192.168.1.101",
        "tipo": "texto",
        "categoria": "Impresoras",
        "descripcion": "IP de la impresora matricial Epson LX-50 para facturas físicas",
        "valor_defecto": "192.168.1.101",
        "requerido": False,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "IMPRESORA_FACTURA_PUERTO",
        "valor": "9100",
        "tipo": "entero",
        "categoria": "Impresoras",
        "descripcion": "Puerto TCP de la impresora matricial para facturas",
        "valor_defecto": "9100",
        "requerido": False,
        "validacion": "min:1,max:65535",
        "valores_permitidos": [],
        "valor_min": "1",
        "valor_max": "65535",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "IMPRESORA_TICKET_COPIAS",
        "valor": "1",
        "tipo": "entero",
        "categoria": "Impresoras",
        "descripcion": "Cantidad de copias al imprimir un ticket de venta",
        "valor_defecto": "1",
        "requerido": True,
        "validacion": "min:1,max:3",
        "valores_permitidos": [],
        "valor_min": "1",
        "valor_max": "3",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    # ── Seguridad ─────────────────────────────────────────────────────────────
    {
        "clave": "SESION_TIMEOUT_MINUTOS",
        "valor": "30",
        "tipo": "entero",
        "categoria": "Seguridad",
        "descripcion": "Minutos de inactividad antes de cerrar sesión automáticamente",
        "valor_defecto": "30",
        "requerido": True,
        "validacion": "min:5,max:480",
        "valores_permitidos": [],
        "valor_min": "5",
        "valor_max": "480",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
    {
        "clave": "MAX_INTENTOS_LOGIN",
        "valor": "5",
        "tipo": "entero",
        "categoria": "Seguridad",
        "descripcion": "Intentos de login fallidos antes de bloquear la cuenta",
        "valor_defecto": "5",
        "requerido": True,
        "validacion": "min:3,max:20",
        "valores_permitidos": [],
        "valor_min": "3",
        "valor_max": "20",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
    {
        "clave": "PIN_REQUERIDO_CAJA",
        "valor": "false",
        "tipo": "booleano",
        "categoria": "Seguridad",
        "descripcion": "Exigir PIN supervisor para abrir / cerrar turno de caja",
        "valor_defecto": "false",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": ["true", "false"],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
    {
        "clave": "BLOQUEO_MINUTOS",
        "valor": "15",
        "tipo": "entero",
        "categoria": "Seguridad",
        "descripcion": "Minutos que permanece bloqueada una cuenta tras exceder los intentos",
        "valor_defecto": "15",
        "requerido": True,
        "validacion": "min:1,max:1440",
        "valores_permitidos": [],
        "valor_min": "1",
        "valor_max": "1440",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
    # ── Facturación ───────────────────────────────────────────────────────────
    {
        "clave": "FACTURA_ESTABLECIMIENTO",
        "valor": "001",
        "tipo": "texto",
        "categoria": "Facturación",
        "descripcion": "Código de establecimiento SET (3 dígitos, ej: 001)",
        "valor_defecto": "001",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
    {
        "clave": "FACTURA_PUNTO_EXPEDICION",
        "valor": "001",
        "tipo": "texto",
        "categoria": "Facturación",
        "descripcion": "Código de punto de expedición SET (3 dígitos, ej: 001)",
        "valor_defecto": "001",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
    {
        "clave": "FACTURA_CONDICION_VENTA",
        "valor": "Contado",
        "tipo": "texto",
        "categoria": "Facturación",
        "descripcion": "Condición de venta impresa en el formulario físico",
        "valor_defecto": "Contado",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": ["Contado", "Crédito", "Otro"],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "FACTURA_LEYENDA_PIE",
        "valor": "Gracias por su compra.",
        "tipo": "texto",
        "categoria": "Facturación",
        "descripcion": "Texto al pie de la factura impresa",
        "valor_defecto": "Gracias por su compra.",
        "requerido": False,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    # ── Reportes ──────────────────────────────────────────────────────────────
    {
        "clave": "REPORTE_EMAIL_DESTINO",
        "valor": "",
        "tipo": "texto",
        "categoria": "Reportes",
        "descripcion": "Email donde se envían los reportes diarios automáticos",
        "valor_defecto": "",
        "requerido": False,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "REPORTE_HORA_CIERRE_AUTOMATICO",
        "valor": "23:00",
        "tipo": "texto",
        "categoria": "Reportes",
        "descripcion": "Hora de generación automática del reporte diario (HH:MM)",
        "valor_defecto": "23:00",
        "requerido": False,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "REPORTE_DIAS_RETENCION",
        "valor": "90",
        "tipo": "entero",
        "categoria": "Reportes",
        "descripcion": "Días que se conservan los reportes en el sistema",
        "valor_defecto": "90",
        "requerido": True,
        "validacion": "min:30,max:3650",
        "valores_permitidos": [],
        "valor_min": "30",
        "valor_max": "3650",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
    # ── Sistema ───────────────────────────────────────────────────────────────
    {
        "clave": "MONEDA_SIMBOLO",
        "valor": "Gs.",
        "tipo": "texto",
        "categoria": "Sistema",
        "descripcion": "Símbolo de la moneda usado en toda la interfaz",
        "valor_defecto": "Gs.",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
    {
        "clave": "ZONA_HORARIA",
        "valor": "America/Asuncion",
        "tipo": "texto",
        "categoria": "Sistema",
        "descripcion": "Zona horaria del servidor (IANA, ej: America/Asuncion)",
        "valor_defecto": "America/Asuncion",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": True,
        "solo_superuser": True,
    },
    {
        "clave": "IDIOMA_SISTEMA",
        "valor": "es-PY",
        "tipo": "texto",
        "categoria": "Sistema",
        "descripcion": "Código de idioma/locale del sistema",
        "valor_defecto": "es-PY",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": ["es-PY", "es-AR", "es-ES"],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": True,
        "solo_superuser": True,
    },
    {
        "clave": "PAGINAS_POR_LISTA",
        "valor": "25",
        "tipo": "entero",
        "categoria": "Sistema",
        "descripcion": "Cantidad de filas por página en tablas y listados",
        "valor_defecto": "25",
        "requerido": True,
        "validacion": "min:10,max:200",
        "valores_permitidos": [],
        "valor_min": "10",
        "valor_max": "200",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "MODO_MANTENIMIENTO",
        "valor": "false",
        "tipo": "booleano",
        "categoria": "Sistema",
        "descripcion": "Activar modo mantenimiento (bloquea acceso a no-admins)",
        "valor_defecto": "false",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": ["true", "false"],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
]


def crear_configuraciones(apps, schema_editor):
    ConfiguracionSistema = apps.get_model("core", "ConfiguracionSistema")
    now = timezone.now()
    for cfg in CONFIGURACIONES:
        ConfiguracionSistema.objects.get_or_create(
            clave=cfg["clave"],
            defaults={
                **cfg,
                "estado": True,
                "updated_at": now,
                "updated_by": None,
            },
        )


def eliminar_configuraciones(apps, schema_editor):
    ConfiguracionSistema = apps.get_model("core", "ConfiguracionSistema")
    claves = [c["clave"] for c in CONFIGURACIONES]
    ConfiguracionSistema.objects.filter(clave__in=claves).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_datos_iniciales_configuracion"),
    ]

    operations = [
        migrations.RunPython(crear_configuraciones, eliminar_configuraciones),
    ]
