# Generated by Django 4.2 on 2026-06-03 00:41
# Sprint A1 + A2: CHECK constraints en core + función verificar_saldo_tarjeta

from django.db import migrations

CHECK_SQL = """
ALTER TABLE core_cargasaldo
    ADD CONSTRAINT chk_carga_monto_positivo
    CHECK (monto_cargado > 0);

ALTER TABLE core_cargasaldo
    ADD CONSTRAINT chk_carga_comision_no_negativa
    CHECK (comision >= 0);

ALTER TABLE core_cargasaldo
    ADD CONSTRAINT chk_carga_total_cobrado
    CHECK (total_cobrado IS NULL OR total_cobrado >= 0);

ALTER TABLE core_tarjeta
    ADD CONSTRAINT chk_tarjeta_limite_no_negativo
    CHECK (limite_credito >= 0);

ALTER TABLE core_tarjeta
    ADD CONSTRAINT chk_tarjeta_saldo_alerta_no_negativo
    CHECK (saldo_alerta IS NULL OR saldo_alerta >= 0);
"""

DROP_CHECKS = """
ALTER TABLE core_cargasaldo DROP CONSTRAINT IF EXISTS chk_carga_monto_positivo;
ALTER TABLE core_cargasaldo DROP CONSTRAINT IF EXISTS chk_carga_comision_no_negativa;
ALTER TABLE core_cargasaldo DROP CONSTRAINT IF EXISTS chk_carga_total_cobrado;
ALTER TABLE core_tarjeta    DROP CONSTRAINT IF EXISTS chk_tarjeta_limite_no_negativo;
ALTER TABLE core_tarjeta    DROP CONSTRAINT IF EXISTS chk_tarjeta_saldo_alerta_no_negativo;
"""

SALDO_FN = """
CREATE OR REPLACE FUNCTION verificar_saldo_tarjeta(p_nro varchar)
RETURNS TABLE(
    nro_tarjeta      varchar,
    saldo_almacenado numeric,
    saldo_calculado  numeric,
    diferencia       numeric,
    total_movimientos bigint
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        t.nro_tarjeta,
        t.saldo_actual,
        COALESCE(SUM(
            CASE m.tipo
                WHEN 'RECARGA' THEN  m.monto
                WHEN 'CONSUMO' THEN -m.monto
                WHEN 'AJUSTE'  THEN  m.monto
                WHEN 'REVERSO' THEN  m.monto
                ELSE 0
            END
        ), 0),
        t.saldo_actual - COALESCE(SUM(
            CASE m.tipo
                WHEN 'RECARGA' THEN  m.monto
                WHEN 'CONSUMO' THEN -m.monto
                WHEN 'AJUSTE'  THEN  m.monto
                WHEN 'REVERSO' THEN  m.monto
                ELSE 0
            END
        ), 0),
        COUNT(m.id)
    FROM core_tarjeta t
    LEFT JOIN core_movimientotarjeta m ON m.tarjeta_id = t.nro_tarjeta
    WHERE t.nro_tarjeta = p_nro
    GROUP BY t.nro_tarjeta, t.saldo_actual;
END;
$$ LANGUAGE plpgsql;
"""

DROP_FN = "DROP FUNCTION IF EXISTS verificar_saldo_tarjeta(varchar);"


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_idx_cargasaldo_pendientes"),
    ]

    operations = [
        migrations.RunSQL(CHECK_SQL, reverse_sql=DROP_CHECKS),
        migrations.RunSQL(SALDO_FN, reverse_sql=DROP_FN),
    ]
