"""
Migration 0011: 16 configuraciones adicionales (Almuerzos, Inventario, Ventas, Tarjetas, Empresa, Timbrado, Bancard).
"""
from django.db import migrations
from django.utils import timezone


CONFIGURACIONES = [
    # ── Almuerzos ─────────────────────────────────────────────────────────────
    {
        "clave": "ALMUERZO_DIA_CORTE_MENSUAL",
        "valor": "1",
        "tipo": "entero",
        "categoria": "Almuerzos",
        "descripcion": "Día del mes en que se generan las cuentas de almuerzos mensuales",
        "valor_defecto": "1",
        "requerido": True,
        "validacion": "min:1,max:28",
        "valores_permitidos": [],
        "valor_min": "1",
        "valor_max": "28",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "ALMUERZO_DIAS_PLAZO_PAGO",
        "valor": "5",
        "tipo": "entero",
        "categoria": "Almuerzos",
        "descripcion": "Días desde el corte para pagar antes de que la cuenta quede vencida",
        "valor_defecto": "5",
        "requerido": True,
        "validacion": "min:1,max:30",
        "valores_permitidos": [],
        "valor_min": "1",
        "valor_max": "30",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "ALMUERZO_PERMITE_CREDITO",
        "valor": "false",
        "tipo": "booleano",
        "categoria": "Almuerzos",
        "descripcion": "Permite consumir almuerzos sin saldo (crédito / cuenta negativa)",
        "valor_defecto": "false",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": ["true", "false"],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    # ── Inventario ────────────────────────────────────────────────────────────
    {
        "clave": "STOCK_DIAS_ALERTA_VENCIMIENTO",
        "valor": "30",
        "tipo": "entero",
        "categoria": "Inventario",
        "descripcion": "Días antes del vencimiento del producto para generar alerta de stock",
        "valor_defecto": "30",
        "requerido": True,
        "validacion": "min:1,max:365",
        "valores_permitidos": [],
        "valor_min": "1",
        "valor_max": "365",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "STOCK_PERMITE_NEGATIVO",
        "valor": "false",
        "tipo": "booleano",
        "categoria": "Inventario",
        "descripcion": "Permite realizar ventas cuando el stock del producto llega a 0",
        "valor_defecto": "false",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": ["true", "false"],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "STOCK_UNIDAD_DEFAULT",
        "valor": "Und",
        "tipo": "texto",
        "categoria": "Inventario",
        "descripcion": "Abreviatura de la unidad de medida preseleccionada al crear un producto",
        "valor_defecto": "Und",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    # ── Ventas ────────────────────────────────────────────────────────────────
    {
        "clave": "VENTA_DIAS_DEVOLUCION",
        "valor": "7",
        "tipo": "entero",
        "categoria": "Ventas",
        "descripcion": "Plazo máximo en días para aceptar devoluciones de una venta",
        "valor_defecto": "7",
        "requerido": True,
        "validacion": "min:0,max:365",
        "valores_permitidos": [],
        "valor_min": "0",
        "valor_max": "365",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "VENTA_REQUIERE_CLIENTE",
        "valor": "false",
        "tipo": "booleano",
        "categoria": "Ventas",
        "descripcion": "Exige identificar al cliente en toda venta (desactiva ventas anónimas)",
        "valor_defecto": "false",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": ["true", "false"],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    # ── Tarjetas ──────────────────────────────────────────────────────────────
    {
        "clave": "TARJETA_COMISION_RECARGA_PORCENTAJE",
        "valor": "0",
        "tipo": "decimal",
        "categoria": "Tarjetas",
        "descripcion": "Porcentaje de comisión cobrado al usuario al recargar la tarjeta (0 = sin comisión)",
        "valor_defecto": "0",
        "requerido": True,
        "validacion": "min:0,max:20",
        "valores_permitidos": [],
        "valor_min": "0",
        "valor_max": "20",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
    {
        "clave": "TARJETA_DIAS_INACTIVIDAD_ALERTA",
        "valor": "90",
        "tipo": "entero",
        "categoria": "Tarjetas",
        "descripcion": "Días sin uso de una tarjeta antes de generar alerta por inactividad",
        "valor_defecto": "90",
        "requerido": True,
        "validacion": "min:30,max:730",
        "valores_permitidos": [],
        "valor_min": "30",
        "valor_max": "730",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    # ── Empresa ───────────────────────────────────────────────────────────────
    {
        "clave": "EMPRESA_EMAIL",
        "valor": "",
        "tipo": "texto",
        "categoria": "Empresa",
        "descripcion": "Email institucional que aparece en documentos y comunicaciones",
        "valor_defecto": "",
        "requerido": False,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    {
        "clave": "EMPRESA_LOGO_URL",
        "valor": "",
        "tipo": "texto",
        "categoria": "Empresa",
        "descripcion": "URL pública del logo de la institución (para tickets y documentos PDF)",
        "valor_defecto": "",
        "requerido": False,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    # ── Timbrado ──────────────────────────────────────────────────────────────
    {
        "clave": "TIMBRADO_DIAS_ALERTA_VENCIMIENTO",
        "valor": "30",
        "tipo": "entero",
        "categoria": "Facturación",
        "descripcion": "Días antes del vencimiento del timbrado SET para mostrar alerta al administrador",
        "valor_defecto": "30",
        "requerido": True,
        "validacion": "min:7,max:180",
        "valores_permitidos": [],
        "valor_min": "7",
        "valor_max": "180",
        "requiere_reinicio": False,
        "solo_superuser": False,
    },
    # ── Bancard / Integración ─────────────────────────────────────────────────
    {
        "clave": "BANCARD_PUBLIC_KEY",
        "valor": "",
        "tipo": "texto",
        "categoria": "Integraciones",
        "descripcion": "Clave pública del gateway Bancard (obtenida en el portal de Bancard)",
        "valor_defecto": "",
        "requerido": False,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
    {
        "clave": "BANCARD_PRIVATE_KEY",
        "valor": "",
        "tipo": "texto",
        "categoria": "Integraciones",
        "descripcion": "Clave privada del gateway Bancard (mantener secreta, no compartir)",
        "valor_defecto": "",
        "requerido": False,
        "validacion": "",
        "valores_permitidos": [],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
    {
        "clave": "BANCARD_SANDBOX",
        "valor": "true",
        "tipo": "booleano",
        "categoria": "Integraciones",
        "descripcion": "Activar entorno de pruebas (sandbox) de Bancard. Desactivar en producción.",
        "valor_defecto": "true",
        "requerido": True,
        "validacion": "",
        "valores_permitidos": ["true", "false"],
        "valor_min": "",
        "valor_max": "",
        "requiere_reinicio": False,
        "solo_superuser": True,
    },
]


def crear_configuraciones(apps, schema_editor):
    ConfiguracionSistema = apps.get_model("core", "ConfiguracionSistema")
    now = timezone.now()
    for cfg in CONFIGURACIONES:
        ConfiguracionSistema.objects.get_or_create(
            clave=cfg["clave"],
            defaults={
                **cfg,
                "estado": True,
                "updated_at": now,
                "updated_by": None,
            },
        )


def eliminar_configuraciones(apps, schema_editor):
    ConfiguracionSistema = apps.get_model("core", "ConfiguracionSistema")
    claves = [c["clave"] for c in CONFIGURACIONES]
    ConfiguracionSistema.objects.filter(clave__in=claves).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_configuraciones_profesionales"),
    ]

    operations = [
        migrations.RunPython(crear_configuraciones, eliminar_configuraciones),
    ]
