# Generated by Django 4.2 on 2026-06-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pagobancard'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pagobancard',
            new_name='core_pagoba_shop_pr_01bb2f_idx',
            old_name='idx_bancard_shop_pid',
        ),
        migrations.RenameIndex(
            model_name='pagobancard',
            new_name='core_pagoba_tarjeta_50b8b6_idx',
            old_name='idx_bancard_tarjeta',
        ),
        migrations.RenameIndex(
            model_name='pagobancard',
            new_name='core_pagoba_estado_7fed01_idx',
            old_name='idx_bancard_estado',
        ),
    ]
