# Generated by Django 4.2 on 2026-06-10 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_movimientocaja_medio_pago_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientotarjeta',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_tarjeta_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
