# Generated by Django 5.2.16 on 2026-07-13 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0014_fix_trigger_ya_cobrado'),
        ('clientes', '0009_add_idx_cuentacorriente_cliente_id'),
        ('core', '0018_tarjeta_cliente_directo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagobancard',
            name='cuenta_almuerzo',
            field=models.ForeignKey(blank=True, help_text='Cuenta mensual de almuerzo a abonar (solo tipo ALMUERZO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_bancard', to='almuerzos.cuentaalmuerzomensual'),
        ),
        migrations.AddField(
            model_name='pagobancard',
            name='tipo',
            field=models.CharField(choices=[('TARJETA', 'Recarga de tarjeta'), ('ALMUERZO', 'Pago de cuenta almuerzo')], default='TARJETA', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicaltarjeta',
            name='cliente_directo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Docente/funcionario dueño de la tarjeta (cuando no es alumno)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='historicaltarjeta',
            name='hijo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Estudiante dueño de la tarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.hijo'),
        ),
        migrations.AlterField(
            model_name='pagobancard',
            name='tarjeta',
            field=models.ForeignKey(blank=True, help_text='Tarjeta prepago que se recargará (solo tipo TARJETA)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_bancard', to='core.tarjeta'),
        ),
    ]
