# Generated by Django 5.2.16 on 2026-07-22 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_mv_balance_cliente_uq_caja_abierta'),
        ('core', '0019_pagobancard_tipo_almuerzo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargasaldo',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_saldo', to='contabilidad.factura'),
        ),
    ]
