# Generated by Django 5.2.16 on 2026-07-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_factura_fk_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediopago',
            options={'ordering': ['descripcion'], 'verbose_name': 'Medio de Pago', 'verbose_name_plural': 'Medios de Pago'},
        ),
    ]
