# Generated by Django 5.2.16 on 2026-08-06 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0020_saldo_almuerzo_cuenta_corriente'),
        ('clientes', '0011_add_factura_genera_factura_to_cc'),
        ('core', '0024_desactivar_tarjeta_rfid_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagobancard',
            name='hijo',
            field=models.ForeignKey(blank=True, help_text='Hijo cuyo saldo corriente de almuerzo se recarga (solo tipo ALMUERZO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_bancard_almuerzo', to='clientes.hijo'),
        ),
        migrations.AlterField(
            model_name='pagobancard',
            name='cuenta_almuerzo',
            field=models.ForeignKey(blank=True, help_text='Histórico: cuenta mensual de almuerzo abonada (modelo anterior a la cuenta corriente)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_bancard', to='almuerzos.cuentaalmuerzomensual'),
        ),
    ]
