# Generated by Django 5.2.16 on 2026-08-06 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0020_saldo_almuerzo_cuenta_corriente'),
        ('core', '0025_pagobancard_hijo_almuerzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagobancard',
            name='recarga_almuerzo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_bancard', to='almuerzos.recargasaldoalmuerzo'),
        ),
    ]
