# Generated by Django 5.2.16 on 2026-08-20 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_hijo_fecha_baja_purga'),
        ('core', '0026_pagobancard_recarga_almuerzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagobancard',
            name='movimiento_cc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_bancard', to='clientes.cuentacorrientecliente'),
        ),
        migrations.AlterField(
            model_name='pagobancard',
            name='tipo',
            field=models.CharField(choices=[('TARJETA', 'Recarga de tarjeta'), ('ALMUERZO', 'Pago de cuenta almuerzo'), ('CC', 'Pago de cuenta corriente')], default='TARJETA', max_length=10),
        ),
    ]
