# Generated by Django 5.2.16 on 2026-09-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_pagobancard_movimiento_cc_alter_pagobancard_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroautorizacion',
            name='ajuste',
        ),
        migrations.RemoveField(
            model_name='registroautorizacion',
            name='autorizador',
        ),
        migrations.RemoveField(
            model_name='registroautorizacion',
            name='autorizador_2',
        ),
        migrations.RemoveField(
            model_name='registroautorizacion',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='registroautorizacion',
            name='solicitante',
        ),
        migrations.RemoveField(
            model_name='registroautorizacion',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='tarjetaautorizacion',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='LimiteTransaccion',
        ),
        migrations.DeleteModel(
            name='RegistroAutorizacion',
        ),
        migrations.DeleteModel(
            name='TarjetaAutorizacion',
        ),
    ]
