# Generated by Django 5.2.16 on 2026-09-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_registroautorizacion_ajuste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientotarjeta',
            name='consumo',
        ),
        migrations.DeleteModel(
            name='ConsumoTarjeta',
        ),
    ]
