# Generated by Django 5.2.16 on 2026-09-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_movimientotarjeta_consumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagobancard',
            name='origen_cc',
            field=models.CharField(blank=True, choices=[('CANTINA', 'Cantina'), ('ALMUERZO', 'Almuerzo')], help_text='Categoría de deuda que cubre este pago (solo aplica a tipo=CC) — se guarda al iniciar el pago para que sobreviva la confirmación asíncrona de Bancard.', max_length=10, null=True),
        ),
    ]
