# Generated by Django 5.2.16 on 2026-09-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientotarjeta',
            options={'ordering': ['-fecha', '-id_movimiento_tarjeta'], 'verbose_name': 'Movimiento de Tarjeta', 'verbose_name_plural': 'Movimientos de Tarjetas'},
        ),
        migrations.AlterField(
            model_name='cargasaldo',
            name='id_carga',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcargasaldo',
            name='id_carga',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='id_medio_pago',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movimientotarjeta',
            name='id_movimiento_tarjeta',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagobancard',
            name='id_pago_bancard',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudcatastrobancard',
            name='id_solicitud_catastro',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
