# Generated by Django 5.2.16 on 2026-09-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0023_alter_alergeno_id_alergeno_and_more'),
        ('clientes', '0020_remove_ciudad_pais_remove_cliente_ciudad_catalogo_and_more'),
        ('core', '0033_fix_verificar_saldo_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagobancard',
            name='cuenta_almuerzo',
        ),
        migrations.AddConstraint(
            model_name='pagobancard',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'TARJETA'), ('recarga_almuerzo__isnull', True), ('movimiento_cc__isnull', True)), models.Q(('tipo', 'ALMUERZO'), ('carga_saldo__isnull', True), ('movimiento_cc__isnull', True)), models.Q(('tipo', 'CC'), ('carga_saldo__isnull', True), ('recarga_almuerzo__isnull', True)), _connector='OR'), name='pagobancard_resultado_segun_tipo'),
        ),
    ]
