"""
Constantes globales del proyecto
"""

# Estados de ventas
VENTA_ESTADO_PENDIENTE = 'PENDIENTE'
VENTA_ESTADO_COMPLETADA = 'COMPLETADA'
VENTA_ESTADO_CANCELADA = 'CANCELADA'

VENTA_ESTADOS = [
    (VENTA_ESTADO_PENDIENTE, 'Pendiente'),
    (VENTA_ESTADO_COMPLETADA, 'Completada'),
    (VENTA_ESTADO_CANCELADA, 'Cancelada'),
]

# Métodos de pago
METODO_PAGO_EFECTIVO = 'EFECTIVO'
METODO_PAGO_TARJETA = 'TARJETA'
METODO_PAGO_TRANSFERENCIA = 'TRANSFERENCIA'
METODO_PAGO_CREDITO = 'CREDITO'

METODOS_PAGO = [
    (METODO_PAGO_EFECTIVO, 'Efectivo'),
    (METODO_PAGO_TARJETA, 'Tarjeta'),
    (METODO_PAGO_TRANSFERENCIA, 'Transferencia'),
    (METODO_PAGO_CREDITO, 'Crédito'),
]

# Tipos de usuario
TIPO_USUARIO_ADMIN = 'ADMIN'
TIPO_USUARIO_VENDEDOR = 'VENDEDOR'
TIPO_USUARIO_CLIENTE = 'CLIENTE'

TIPOS_USUARIO = [
    (TIPO_USUARIO_ADMIN, 'Administrador'),
    (TIPO_USUARIO_VENDEDOR, 'Vendedor'),
    (TIPO_USUARIO_CLIENTE, 'Cliente'),
]
