# Generated by Django 4.2 on 2026-05-14 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('path', models.CharField(max_length=200)),
                ('metodo', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=6)),
                ('headers', models.JSONField(default=dict, help_text='Headers por defecto')),
                ('parametros', models.JSONField(default=dict, help_text='Parámetros por defecto')),
                ('schema_request', models.JSONField(default=dict, help_text='Schema esperado del request')),
                ('schema_response', models.JSONField(default=dict, help_text='Schema esperado del response')),
                ('cache_segundos', models.IntegerField(default=0, help_text='0 = sin caché')),
                ('requiere_auth', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Endpoint de API',
                'verbose_name_plural': 'Endpoints de API',
            },
        ),
        migrations.CreateModel(
            name='ProveedorApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo_servicio', models.CharField(choices=[('PAGOS_QR', 'Pagos QR (SIPAP)'), ('BANCO', 'Banco'), ('NOTIFICACIONES', 'Notificaciones'), ('OTRO', 'Otro')], max_length=20)),
                ('url_base', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('documentacion', models.URLField(blank=True, null=True)),
                ('tipo_auth', models.CharField(choices=[('API_KEY', 'API Key'), ('BEARER', 'Bearer Token'), ('BASIC', 'Basic Auth'), ('OAUTH2', 'OAuth 2.0')], max_length=10)),
                ('config_auth', models.JSONField(default=dict)),
                ('timeout', models.IntegerField(default=30, help_text='Timeout en segundos')),
                ('max_reintentos', models.IntegerField(default=3)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor de API',
                'verbose_name_plural': 'Proveedores de API',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('path', models.CharField(help_text='Ruta del webhook (ej: /api/webhooks/sipap/)', max_length=200)),
                ('requiere_verificacion', models.BooleanField(default=True)),
                ('secret_key', models.CharField(help_text='Clave secreta para validar firma', max_length=255)),
                ('header_verificacion', models.CharField(help_text='Nombre del header que contiene la firma', max_length=100)),
                ('eventos', models.JSONField(default=list, help_text='Eventos que acepta este webhook')),
                ('handler', models.CharField(help_text='Función o ruta que procesa el webhook', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='api_integrations.proveedorapi')),
            ],
            options={
                'verbose_name': 'Webhook Endpoint',
                'verbose_name_plural': 'Webhook Endpoints',
                'unique_together': {('proveedor', 'path')},
            },
        ),
        migrations.CreateModel(
            name='LogWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('headers', models.JSONField(default=dict)),
                ('payload', models.TextField()),
                ('evento_tipo', models.CharField(max_length=100)),
                ('verificacion_ok', models.BooleanField(default=False)),
                ('procesado_ok', models.BooleanField(default=False)),
                ('tiempo_proc_ms', models.IntegerField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('webhook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api_integrations.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Log de Webhook',
                'verbose_name_plural': 'Logs de Webhooks',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LogLlamadaApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=500)),
                ('headers_req', models.JSONField(default=dict)),
                ('payload_req', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('headers_res', models.JSONField(default=dict)),
                ('payload_res', models.TextField(blank=True, null=True)),
                ('tiempo_ms', models.IntegerField()),
                ('bytes_sent', models.IntegerField(blank=True, null=True)),
                ('bytes_received', models.IntegerField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('intento', models.IntegerField(default=1)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('contexto', models.JSONField(default=dict)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api_integrations.endpointapi')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Llamada API',
                'verbose_name_plural': 'Logs de Llamadas API',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='endpointapi',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='api_integrations.proveedorapi'),
        ),
        migrations.AlterUniqueTogether(
            name='endpointapi',
            unique_together={('proveedor', 'path', 'metodo')},
        ),
        migrations.CreateModel(
            name='CredencialApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCCION', 'Producción')], max_length=15)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('secret', models.TextField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('configuracion', models.JSONField(default=dict)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales', to='api_integrations.proveedorapi')),
            ],
            options={
                'verbose_name': 'Credencial de API',
                'verbose_name_plural': 'Credenciales de API',
                'unique_together': {('proveedor', 'ambiente')},
            },
        ),
    ]
