# Generated by Django 6.0.2 on 2026-03-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialesApi',
            fields=[
                ('id_credencial', models.AutoField(primary_key=True, serialize=False)),
                ('ambiente', models.CharField(max_length=20)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('secret', models.TextField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('configuracion', models.JSONField()),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'credenciales_api',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EndpointsApi',
            fields=[
                ('id_endpoint', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('path', models.CharField(max_length=200)),
                ('metodo', models.CharField(max_length=10)),
                ('headers', models.JSONField()),
                ('parametros', models.JSONField()),
                ('schema_request', models.JSONField()),
                ('schema_response', models.JSONField()),
                ('cache_segundos', models.IntegerField()),
                ('requiere_auth', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'endpoints_api',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogsLlamadasApi',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('metodo', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=500)),
                ('headers_req', models.JSONField()),
                ('payload_req', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('headers_res', models.JSONField()),
                ('payload_res', models.TextField(blank=True, null=True)),
                ('tiempo_ms', models.IntegerField()),
                ('bytes_sent', models.IntegerField(blank=True, null=True)),
                ('bytes_received', models.IntegerField(blank=True, null=True)),
                ('exitoso', models.IntegerField()),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('intento', models.IntegerField()),
                ('ip_origen', models.CharField(blank=True, max_length=39, null=True)),
                ('contexto', models.JSONField()),
            ],
            options={
                'db_table': 'logs_llamadas_api',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogsWebhooks',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('headers', models.JSONField()),
                ('payload', models.TextField()),
                ('evento_tipo', models.CharField(max_length=100)),
                ('verificacion_ok', models.IntegerField()),
                ('procesado_ok', models.IntegerField()),
                ('tiempo_proc_ms', models.IntegerField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('ip_origen', models.CharField(max_length=39)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logs_webhooks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProveedoresApi',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_servicio', models.CharField(max_length=30)),
                ('url_base', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=20)),
                ('documentacion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_auth', models.CharField(max_length=20)),
                ('config_auth', models.JSONField()),
                ('timeout', models.IntegerField()),
                ('max_reintentos', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'proveedores_api',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoints',
            fields=[
                ('id_webhook', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('path', models.CharField(max_length=200)),
                ('requiere_verificacion', models.IntegerField()),
                ('secret_key', models.CharField(max_length=255)),
                ('header_verificacion', models.CharField(max_length=100)),
                ('eventos', models.JSONField()),
                ('handler_func', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'webhook_endpoints',
                'managed': True,
            },
        ),
    ]
