# Generated by Django 6.0.2 on 2026-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_integrations', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsllamadasapi',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='logsllamadasapi',
            name='id_endpoint',
            field=models.ForeignKey(blank=True, db_column='id_endpoint', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_integrations.endpointsapi'),
        ),
        migrations.AddField(
            model_name='endpointsapi',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='api_integrations.proveedoresapi'),
        ),
        migrations.AddField(
            model_name='credencialesapi',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='api_integrations.proveedoresapi'),
        ),
        migrations.AddField(
            model_name='webhookendpoints',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='api_integrations.proveedoresapi'),
        ),
        migrations.AddField(
            model_name='logswebhooks',
            name='id_webhook',
            field=models.ForeignKey(blank=True, db_column='id_webhook', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_integrations.webhookendpoints'),
        ),
        migrations.AlterUniqueTogether(
            name='credencialesapi',
            unique_together={('id_proveedor', 'ambiente')},
        ),
        migrations.AlterUniqueTogether(
            name='webhookendpoints',
            unique_together={('id_proveedor', 'path')},
        ),
    ]
