# Generated by Django 6.0.2 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integrations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credencialesapi',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='endpointsapi',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='proveedoresapi',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='webhookendpoints',
            name='activo',
        ),
        migrations.AddField(
            model_name='credencialesapi',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='endpointsapi',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedoresapi',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webhookendpoints',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
