# Generated by Django 4.2 on 2026-05-14 03:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacionSaldoNegativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_autorizado', models.DecimalField(decimal_places=0, help_text='Monto en Guaraníes', max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=0, max_digits=12)),
                ('saldo_resultante', models.DecimalField(decimal_places=0, max_digits=12)),
                ('motivo', models.TextField(help_text='Justificación')),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('APROBADA', 'Aprobada'), ('USADA', 'Usada'), ('CANCELADA', 'Cancelada')], default='APROBADA', max_length=10)),
            ],
            options={
                'verbose_name': 'Autorización de Saldo Negativo',
                'verbose_name_plural': 'Autorizaciones de Saldo Negativo',
                'ordering': ['-fecha_autorizacion'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres del cliente', max_length=100)),
                ('apellidos', models.CharField(help_text='Apellidos del cliente', max_length=100)),
                ('razon_social', models.CharField(blank=True, help_text='Razón social si es empresa', max_length=255, null=True)),
                ('ruc_ci', models.CharField(help_text='RUC o Cédula de Identidad', max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('limite_credito', models.DecimalField(decimal_places=0, default=0, help_text='Límite de crédito en Guaraníes (sin decimales)', max_digits=12)),
                ('activo', models.BooleanField(default=True, help_text='False si el cliente está inactivo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nivel', models.IntegerField(help_text='Nivel numérico (1-12)')),
                ('orden', models.IntegerField(help_text='Orden de visualización')),
                ('es_ultimo', models.BooleanField(default=False, help_text='True si es el último grado')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del estudiante', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del estudiante', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_perfil', models.ImageField(blank=True, help_text='Foto de perfil del estudiante', null=True, upload_to='hijos/fotos/%Y/%m/')),
                ('fecha_foto', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Hijo/Estudiante',
                'verbose_name_plural': 'Hijos/Estudiantes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RestriccionHijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ej: Alergia, Intolerancia, Médica', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('hijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restricciones', to='clientes.hijo')),
            ],
            options={
                'verbose_name': 'Restricción de Hijo',
                'verbose_name_plural': 'Restricciones de Hijos',
                'ordering': ['-severidad'],
            },
        ),
        migrations.CreateModel(
            name='HistorialGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('grado_nuevo', models.CharField(max_length=50)),
                ('anio_escolar', models.IntegerField()),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=20)),
                ('usuario_registro', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('hijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_grados', to='clientes.hijo')),
            ],
            options={
                'verbose_name': 'Historial de Grado',
                'verbose_name_plural': 'Historial de Grados',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='CuentaCorrienteCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=0, help_text='Monto en Guaraníes', max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=0, help_text='Saldo antes del movimiento', max_digits=12)),
                ('saldo_resultante', models.DecimalField(decimal_places=0, help_text='Saldo después del movimiento', max_digits=12)),
                ('descripcion', models.CharField(blank=True, help_text='Detalle del movimiento', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(help_text='Cliente titular de la cuenta', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cuenta', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Movimiento de Cuenta Corriente',
                'verbose_name_plural': 'Cuentas Corrientes de Clientes',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
