# Generated by Django 6.0.2 on 2026-03-01 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacionesSaldoNegativo',
            fields=[
                ('id_autorizacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto_autorizado', models.DecimalField(decimal_places=2, help_text='Monto máximo autorizado en negativo', max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_resultante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField(help_text='Justificación de la autorización')),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(help_text='Ej: Aprobada, Usada, Cancelada', max_length=10)),
            ],
            options={
                'verbose_name': 'Autorización de Saldo Negativo',
                'verbose_name_plural': 'Autorizaciones de Saldo Negativo',
                'db_table': 'autorizaciones_saldo_negativo',
                'ordering': ['-fecha_autorizacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(help_text='Nombres del cliente', max_length=100)),
                ('apellidos', models.CharField(help_text='Apellidos del cliente', max_length=100)),
                ('razon_social', models.CharField(blank=True, help_text='Razón social si es empresa', max_length=255, null=True)),
                ('ruc_ci', models.CharField(help_text='RUC o Cédula de Identidad', max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('activo', models.BooleanField(default=True, help_text='1=Activo, 0=Inactivo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['apellidos', 'nombres'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=50, unique=True)),
                ('nivel', models.IntegerField(help_text='Nivel numérico del grado (1-12)')),
                ('orden_visualizacion', models.IntegerField()),
                ('es_ultimo_grado', models.BooleanField(default=False, help_text='1 si es el último grado')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'db_table': 'grados',
                'ordering': ['orden_visualizacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hijos',
            fields=[
                ('id_hijo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del estudiante', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del estudiante', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_foto', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, help_text='1=Activo, 0=Inactivo')),
            ],
            options={
                'verbose_name': 'Hijo/Estudiante',
                'verbose_name_plural': 'Hijos/Estudiantes',
                'db_table': 'hijos',
                'ordering': ['apellido', 'nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialGradosHijos',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('grado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('grado_nuevo', models.CharField(max_length=50)),
                ('anio_escolar', models.IntegerField()),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=20)),
                ('usuario_registro', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historial de Grado',
                'verbose_name_plural': 'Historial de Grados',
                'db_table': 'historial_grados_hijos',
                'ordering': ['-fecha_cambio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogsAutorizaciones',
            fields=[
                ('id_log', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_barra', models.CharField(max_length=50)),
                ('tipo_operacion', models.CharField(help_text='Ej: Lectura, Autorización, Validación', max_length=20)),
                ('id_registro_afectado', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('resultado', models.CharField(help_text='Ej: Exitoso, Fallido, Denegado', max_length=15)),
            ],
            options={
                'verbose_name': 'Log de Autorización',
                'verbose_name_plural': 'Logs de Autorizaciones',
                'db_table': 'logs_autorizaciones',
                'ordering': ['-fecha_hora'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RestriccionesHijos',
            fields=[
                ('id_restriccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_restriccion', models.CharField(help_text='Ej: Alergia, Intolerancia, Médica', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('severidad', models.CharField(help_text='Ej: Baja, Media, Alta, Crítica', max_length=20)),
                ('requiere_autorizacion', models.BooleanField(default=False, help_text='1 si requiere autorización para excepciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Restricción de Hijo',
                'verbose_name_plural': 'Restricciones de Hijos',
                'db_table': 'restricciones_hijos',
                'ordering': ['-severidad', '-activo'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TiposCliente',
            fields=[
                ('id_tipo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Cliente',
                'db_table': 'tipos_cliente',
                'ordering': ['nombre_tipo'],
                'managed': True,
            },
        ),
    ]
