# Generated by Django 6.0.2 on 2026-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionessaldonegativo',
            name='id_empleado_autoriza',
            field=models.ForeignKey(db_column='id_empleado_autoriza', on_delete=django.db.models.deletion.DO_NOTHING, related_name='autorizaciones_realizadas', to='usuarios.empleados'),
        ),
    ]
