# Generated by Django 4.2 on 2026-05-14 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0001_initial'),
        ('clientes', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorrientecliente',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cuenta_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentacorrientecliente',
            name='nota_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta', to='ventas.notacredito'),
        ),
        migrations.AddField(
            model_name='cuentacorrientecliente',
            name='pago',
            field=models.ForeignKey(blank=True, help_text='Pago que generó este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta', to='ventas.pagoventa'),
        ),
        migrations.AddField(
            model_name='cuentacorrientecliente',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='clientes.ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lista_precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='productos.listaprecio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.tipocliente'),
        ),
        migrations.AddField(
            model_name='autorizacionsaldonegativo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_saldo', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='autorizacionsaldonegativo',
            name='empleado_autoriza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_realizadas', to='usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='autorizacionsaldonegativo',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_saldo', to='ventas.venta'),
        ),
        migrations.AddIndex(
            model_name='cuentacorrientecliente',
            index=models.Index(fields=['cliente', 'fecha'], name='idx_cc_cli_fecha'),
        ),
        migrations.AddIndex(
            model_name='cuentacorrientecliente',
            index=models.Index(fields=['cliente', 'tipo'], name='idx_cc_cli_tipo'),
        ),
        migrations.AddIndex(
            model_name='cuentacorrientecliente',
            index=models.Index(fields=['venta'], name='idx_cc_cli_venta'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ruc_ci'], name='idx_cliente_ruc'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='idx_cliente_email'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['activo'], name='idx_cliente_activo'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['apellidos', 'nombres'], name='idx_cliente_nombre'),
        ),
    ]
