# Generated by Django 6.0.2 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restriccioneshijos',
            options={'managed': True, 'ordering': ['-severidad', '-estado'], 'verbose_name': 'Restricción de Hijo', 'verbose_name_plural': 'Restricciones de Hijos'},
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='grados',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='hijos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='restriccioneshijos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tiposcliente',
            name='activo',
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.BooleanField(default=True, help_text='1=estado, 0=Inactivo'),
        ),
        migrations.AddField(
            model_name='grados',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hijos',
            name='estado',
            field=models.BooleanField(default=True, help_text='1=estado, 0=Inactivo'),
        ),
        migrations.AddField(
            model_name='restriccioneshijos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tiposcliente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
