# Generated by Django 6.0.2 on 2026-03-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_initial'),
        ('core', '0002_initial'),
        ('productos', '0002_initial'),
        ('ventas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacionessaldonegativo',
            name='id_venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, related_name='autorizaciones_saldo', to='ventas.ventas'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_lista',
            field=models.ForeignKey(db_column='id_lista', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.listasprecios'),
        ),
        migrations.AddField(
            model_name='autorizacionessaldonegativo',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='autorizaciones_saldo', to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='hijos',
            name='id_cliente_responsable',
            field=models.ForeignKey(db_column='id_cliente_responsable', on_delete=django.db.models.deletion.DO_NOTHING, related_name='hijos', to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='historialgradoshijos',
            name='id_hijo',
            field=models.ForeignKey(db_column='id_hijo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='historial_grados', to='clientes.hijos'),
        ),
        migrations.AddField(
            model_name='logsautorizaciones',
            name='id_tarjeta_autorizacion',
            field=models.ForeignKey(db_column='id_tarjeta_autorizacion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='core.tarjetasautorizacion'),
        ),
        migrations.AddField(
            model_name='restriccioneshijos',
            name='id_hijo',
            field=models.ForeignKey(db_column='id_hijo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='restricciones', to='clientes.hijos'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_tipo_cliente',
            field=models.ForeignKey(db_column='id_tipo_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.tiposcliente'),
        ),
    ]
