# Generated by Django 4.2 on 2026-05-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_historicalcliente'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hijo',
            constraint=models.UniqueConstraint(fields=('cliente_responsable', 'nombre', 'apellido'), name='uq_hijo_cliente_nombre_apellido'),
        ),
    ]
