# Generated by Django 5.2.12 on 2026-03-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_rename_activo_to_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hijos',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del estudiante', null=True, upload_to='fotos_estudiantes/'),
        ),
    ]
