# Generated by Django 4.2 on 2026-06-02 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0005_hijo_grado_fk_ciudad_pais_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('ABUELO', 'Abuelo'), ('ABUELA', 'Abuela'), ('TIO', 'Tío'), ('TIA', 'Tía'), ('TUTOR', 'Tutor/a Legal'), ('OTRO', 'Otro')], max_length=20)),
                ('es_titular', models.BooleanField(default=False, help_text='Responsable financiero principal. Sincronizado con Hijo.cliente_responsable.')),
                ('orden_cobro', models.PositiveSmallIntegerField(default=1, help_text='Orden de contacto para escalamiento de cobro (1 = primero).')),
                ('recibe_notificaciones', models.BooleanField(default=False, help_text='Recibe alertas de deuda y saldo bajo.')),
                ('puede_ver_saldo', models.BooleanField(default=False, help_text='Puede consultar el saldo y consumos del alumno en el portal.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('agregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsables_registrados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(help_text='Responsable financiero', on_delete=django.db.models.deletion.RESTRICT, related_name='hijos_asignados', to='clientes.cliente')),
                ('hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='clientes.hijo')),
            ],
            options={
                'verbose_name': 'Responsable de Alumno',
                'verbose_name_plural': 'Responsables de Alumnos',
                'ordering': ['hijo', 'orden_cobro'],
            },
        ),
        migrations.AddIndex(
            model_name='alumnoresponsable',
            index=models.Index(fields=['hijo', 'activo', 'orden_cobro'], name='idx_ar_hijo_cobro'),
        ),
        migrations.AddIndex(
            model_name='alumnoresponsable',
            index=models.Index(fields=['cliente', 'activo'], name='idx_ar_cliente_activo'),
        ),
        migrations.AddConstraint(
            model_name='alumnoresponsable',
            constraint=models.UniqueConstraint(fields=('hijo', 'cliente'), name='uq_alumno_responsable'),
        ),
        migrations.AddConstraint(
            model_name='alumnoresponsable',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('es_titular', True)), fields=('hijo',), name='uq_alumno_titular_activo'),
        ),
    ]
