# Generated by Django 6.0.2 on 2026-04-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_add_id_ciudad_to_clientes'),
        ('productos', '0005_rename_activo_to_estado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['email'], name='idx_clientes_email'),
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['estado', 'fecha_registro'], name='idx_clientes_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['apellidos', 'nombres'], name='idx_clientes_nombre'),
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['ciudad'], name='idx_clientes_ciudad'),
        ),
    ]
