# Generated by Django 5.2.16 on 2026-07-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_add_idx_cuentacorriente_cliente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='modalidad_facturacion',
            field=models.CharField(choices=[('INMEDIATA', 'Factura por transacción'), ('MENSUAL', 'Factura mensual agrupada')], default='INMEDIATA', help_text='Cuándo se emite la factura: al momento o acumulada mensual', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='modalidad_facturacion',
            field=models.CharField(choices=[('INMEDIATA', 'Factura por transacción'), ('MENSUAL', 'Factura mensual agrupada')], default='INMEDIATA', help_text='Cuándo se emite la factura: al momento o acumulada mensual', max_length=10),
        ),
    ]
