# Generated by Django 5.2.16 on 2026-07-23 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_add_modalidad_facturacion'),
        ('contabilidad', '0012_mv_balance_cliente_uq_caja_abierta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorrientecliente',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta', to='contabilidad.factura'),
        ),
        migrations.AddField(
            model_name='cuentacorrientecliente',
            name='genera_factura_legal',
            field=models.BooleanField(default=False),
        ),
    ]
