# Generated by Django 5.2.16 on 2026-08-11 02:00

from django.db import migrations, models
from django.utils import timezone


def backfill_fecha_baja(apps, schema_editor):
    """
    Alumnos ya inactivos antes de que este campo existiera no tienen forma de
    saber cuándo se dieron de baja. Por decisión del negocio, el reloj de
    retención de 1 año arranca desde el día que se aplica esta migración,
    no retroactivamente.
    """
    Hijo = apps.get_model('clientes', 'Hijo')
    Hijo.objects.filter(activo=False, fecha_baja__isnull=True).update(
        fecha_baja=timezone.now()
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_add_factura_genera_factura_to_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijo',
            name='datos_purgados',
            field=models.BooleanField(default=False, help_text='True si ya se ejecutó la anonimización de datos sensibles (restricciones, foto, nombre)'),
        ),
        migrations.AddField(
            model_name='hijo',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el alumno fue dado de baja (manual o automática al terminar el último curso)', null=True),
        ),
        migrations.AddField(
            model_name='hijo',
            name='purga_solicitada_en',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se marcó como pendiente de purga de datos sensibles (esperando aprobación de un ADMIN)', null=True),
        ),
        migrations.RunPython(backfill_fecha_baja, noop_reverse),
    ]
