# Generated by Django 5.2.16 on 2026-09-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_hijo_fecha_baja_purga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pin_autorizacion',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='pin_autorizacion',
        ),
    ]
