# Generated by Django 5.2.16 on 2026-09-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_remove_cliente_pin_autorizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='permite_cuenta_corriente',
            field=models.BooleanField(default=False, help_text='Si está desactivado, el cliente no puede acumular deuda (ventas al fiado ni recargas por cuenta corriente), sin importar limite_credito.'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='permite_cuenta_corriente',
            field=models.BooleanField(default=False, help_text='Si está desactivado, el cliente no puede acumular deuda (ventas al fiado ni recargas por cuenta corriente), sin importar limite_credito.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Límite de crédito en Guaraníes. 0 = sin límite (solo aplica si permite_cuenta_corriente está activo).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Límite de crédito en Guaraníes. 0 = sin límite (solo aplica si permite_cuenta_corriente está activo).', max_digits=12),
        ),
    ]
