# Generated by Django 5.2.16 on 2026-09-02 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_cliente_permite_cuenta_corriente_and_more'),
        ('contabilidad', '0012_mv_balance_cliente_uq_caja_abierta'),
        ('ventas', '0009_alter_aplicacionpago_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorrientecliente',
            name='origen',
            field=models.CharField(choices=[('CANTINA', 'Cantina'), ('ALMUERZO', 'Almuerzo'), ('GENERAL', 'General')], default='GENERAL', help_text='Categoría de deuda que generó el movimiento — no afecta saldo_resultante ni limite_credito, solo reporte.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='cuentacorrientecliente',
            index=models.Index(fields=['cliente', 'origen'], name='idx_cc_cli_origen'),
        ),
        # Retro-tagueo de movimientos históricos. Los que tienen venta/nota_credito/pago
        # vinculado son inequívocamente CANTINA (esos FKs solo los usa ventas/services.py).
        # El resto se infiere de descripcion; lo que no matchea queda GENERAL — son pagos
        # genéricos de antes de esta categorización, no hay forma de saber a qué categoría
        # corresponden.
        migrations.RunSQL(
            sql="""
                UPDATE clientes_cuentacorrientecliente
                SET origen = 'CANTINA'
                WHERE (venta_id IS NOT NULL OR nota_credito_id IS NOT NULL OR pago_id IS NOT NULL)
                  AND origen = 'GENERAL';

                UPDATE clientes_cuentacorrientecliente
                SET origen = 'ALMUERZO'
                WHERE venta_id IS NULL AND nota_credito_id IS NULL AND pago_id IS NULL
                  AND descripcion ILIKE '%%almuerzo%%'
                  AND origen = 'GENERAL';

                UPDATE clientes_cuentacorrientecliente
                SET origen = 'CANTINA'
                WHERE venta_id IS NULL AND nota_credito_id IS NULL AND pago_id IS NULL
                  AND descripcion ILIKE '%%tarjeta%%'
                  AND origen = 'GENERAL';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
