# Generated by Django 5.2.16 on 2026-09-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_rename_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='id_cliente',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
    ]
