# Generated by Django 5.2.16 on 2026-09-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_rename_ids_resto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentacorrientecliente',
            options={'ordering': ['-fecha', '-id_movimiento_cc'], 'verbose_name': 'Movimiento de Cuenta Corriente', 'verbose_name_plural': 'Cuentas Corrientes de Clientes'},
        ),
        migrations.AlterField(
            model_name='alumnoresponsable',
            name='id_responsable',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autorizacionsaldonegativo',
            name='id_autorizacion',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='id_ciudad',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuentacorrientecliente',
            name='id_movimiento_cc',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grado',
            name='id_grado',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hijo',
            name='id_hijo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historialgrado',
            name='id_historial_grado',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id_pais',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restriccionhijo',
            name='id_restriccion',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='id_tipo_cliente',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
