# Generated by Django 5.2.16 on 2026-09-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_alter_cuentacorrientecliente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad_catalogo',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='ciudad_catalogo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='clientes.ciudad'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='ciudad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.ciudad'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos', to='clientes.pais')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudades', to='clientes.departamento'),
        ),
        migrations.AddConstraint(
            model_name='ciudad',
            constraint=models.UniqueConstraint(fields=('nombre', 'departamento'), name='uq_ciudad_nombre_departamento'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('nombre', 'pais'), name='uq_departamento_nombre_pais'),
        ),
    ]
