# Generated by Django 5.2.16 on 2026-09-04 21:20

import django.db.models.deletion
from django.db import migrations, models


def convertir_ciudad_texto_a_fk(apps, schema_editor):
    """Mapea el texto libre en Cliente.ciudad / HistoricalCliente.ciudad al id de
    Ciudad correspondiente (creándola si no existe), para que el AlterField
    posterior a ForeignKey pueda castear el valor sin perder datos reales."""
    Cliente = apps.get_model('clientes', 'Cliente')
    HistoricalCliente = apps.get_model('clientes', 'HistoricalCliente')
    Ciudad = apps.get_model('clientes', 'Ciudad')

    cache = {}

    def resolver_id(nombre):
        nombre = (nombre or '').strip()
        if not nombre:
            return None
        clave = nombre.lower()
        if clave not in cache:
            ciudad = Ciudad.objects.filter(nombre__iexact=nombre).first()
            if ciudad is None:
                ciudad = Ciudad.objects.create(nombre=nombre)
            cache[clave] = ciudad.pk
        return cache[clave]

    for cliente in Cliente.objects.exclude(ciudad__isnull=True).exclude(ciudad=''):
        id_ciudad = resolver_id(cliente.ciudad)
        if id_ciudad is not None:
            Cliente.objects.filter(pk=cliente.pk).update(ciudad=str(id_ciudad))

    for hist in HistoricalCliente.objects.exclude(ciudad__isnull=True).exclude(ciudad=''):
        id_ciudad = resolver_id(hist.ciudad)
        if id_ciudad is not None:
            HistoricalCliente.objects.filter(pk=hist.pk).update(ciudad=str(id_ciudad))


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_alter_cuentacorrientecliente_options_and_more'),
    ]

    operations = [
        migrations.RunPython(convertir_ciudad_texto_a_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='ciudad',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad_catalogo',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='ciudad_catalogo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='clientes.ciudad'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='ciudad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.ciudad'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos', to='clientes.pais')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudades', to='clientes.departamento'),
        ),
        migrations.AddConstraint(
            model_name='ciudad',
            constraint=models.UniqueConstraint(fields=('nombre', 'departamento'), name='uq_ciudad_nombre_departamento'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('nombre', 'pais'), name='uq_departamento_nombre_pais'),
        ),
    ]
