# Generated by Django 5.2.16 on 2026-09-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_remove_ciudad_pais_remove_cliente_ciudad_catalogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioLectivo',
            fields=[
                ('id_calendario', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(unique=True)),
                ('fecha_aviso_ultimo_curso', models.DateField(help_text='Desde esta fecha se avisan saldos y deudas del último curso (por defecto 01/10).')),
                ('fecha_cierre_lectivo', models.DateField(help_text='Último día en que opera el último curso (por defecto 31/12).')),
                ('baja_ultimo_curso_aplicada', models.BooleanField(default=False, help_text='El sistema ya dio de baja al último curso de este año.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calendario lectivo',
                'verbose_name_plural': 'Calendarios lectivos',
                'ordering': ['-anio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_aviso_ultimo_curso__lt', models.F('fecha_cierre_lectivo'))), name='calendario_aviso_antes_del_cierre')],
            },
        ),
    ]
