# Generated by Django 5.2.16 on 2026-09-20 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_calendario_lectivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='siguiente',
            field=models.ForeignKey(blank=True, help_text='Grado al que promocionan los alumnos (vacío en el último grado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anteriores', to='clientes.grado'),
        ),
        migrations.AlterField(
            model_name='historialgrado',
            name='motivo',
            field=models.CharField(choices=[('PROMOCION', 'Promoción'), ('REPITE', 'Repite el grado'), ('CAMBIO', 'Cambio de grado'), ('EGRESO', 'Egreso / no continúa'), ('MANUAL', 'Cambio manual')], default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='PromocionAnual',
            fields=[
                ('id_promocion', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APLICADA', 'Aplicada')], default='BORRADOR', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aplicacion', models.DateTimeField(blank=True, null=True)),
                ('aplicada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promoción anual',
                'verbose_name_plural': 'Promociones anuales',
                'ordering': ['-anio'],
            },
        ),
        migrations.AddField(
            model_name='historialgrado',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='clientes.promocionanual'),
        ),
        migrations.CreateModel(
            name='PromocionAlumno',
            fields=[
                ('id_promocion_alumno', models.BigAutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('PROMUEVE', 'Promociona al grado siguiente'), ('REPITE', 'Repite el grado'), ('CAMBIA', 'Cambia a otro grado'), ('EGRESA', 'Egresa'), ('NO_CONTINUA', 'No continúa')], default='PROMUEVE', max_length=12)),
                ('motivo', models.TextField(blank=True)),
                ('grado_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clientes.grado')),
                ('grado_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clientes.grado')),
                ('hijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_promocion', to='clientes.hijo')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='clientes.promocionanual')),
            ],
            options={
                'verbose_name': 'Alumno en promoción',
                'verbose_name_plural': 'Alumnos en promoción',
                'constraints': [models.UniqueConstraint(fields=('promocion', 'hijo'), name='unique_promocion_hijo')],
            },
        ),
    ]
