# Generated by Django 4.2 on 2026-05-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=0, max_digits=12)),
                ('precio_nuevo', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Precio',
                'verbose_name_plural': 'Histórico de Precios',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'ordering': ['porcentaje'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(default='PYG', max_length=3)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(blank=True, help_text='Código de barras para escaneo', max_length=50, null=True, unique=True)),
                ('codigo', models.CharField(blank=True, help_text='Código interno del producto', max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(help_text='Nombre descriptivo del producto', max_length=255)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Cantidad mínima antes de generar alerta', max_digits=10)),
                ('permite_stock_negativo', models.BooleanField(default=False, help_text='True si permite vender sin stock disponible')),
                ('es_servicio', models.BooleanField(default=False, help_text='True si es servicio (no requiere stock físico)')),
                ('requiere_stock', models.BooleanField(default=True, help_text='True si debe controlar stock')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo (Kilogramo, Litro)', max_length=50)),
                ('abreviatura', models.CharField(help_text='Abreviatura (Kg, L, Un)', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.impuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Impuesto de Producto',
                'verbose_name_plural': 'Impuestos de Productos',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.unidadmedida'),
        ),
        migrations.CreateModel(
            name='PrecioPorLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=0, help_text='Precio en Guaraníes (sin decimales)', max_digits=12)),
                ('fecha_vigencia', models.DateTimeField(auto_now_add=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='productos.listaprecio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Precio por Lista',
                'verbose_name_plural': 'Precios por Lista',
                'ordering': ['lista', 'producto'],
            },
        ),
    ]
