# Generated by Django 6.0.2 on 2026-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListasPrecios',
            fields=[
                ('id_lista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lista', models.CharField(help_text='Nombre de la lista de precios', max_length=100, unique=True)),
                ('fecha_vigencia', models.DateField(blank=True, help_text='Fecha desde la cual es válida', null=True)),
                ('moneda', models.CharField(default='PYG', help_text='Código de moneda (PYG, USD)', max_length=3)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
                'db_table': 'listas_precios',
                'ordering': ['nombre_lista'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id_unidad_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre completo (Kilogramo, Litro)', max_length=50)),
                ('abreviatura', models.CharField(help_text='Abreviatura (Kg, L)', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidades_medida',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('id_categoria_padre', models.ForeignKey(blank=True, db_column='id_categoria_padre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategorias', to='productos.categorias')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_barra', models.CharField(blank=True, help_text='Código de barras del producto', max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(help_text='Nombre/descripción del producto', max_length=255)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Stock mínimo para alertas', max_digits=10)),
                ('permite_stock_negativo', models.BooleanField(default=False, help_text='1 si permite vender sin stock')),
                ('activo', models.BooleanField(default=True, help_text='1=Activo, 0=Inactivo')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='productos.categorias')),
                ('id_impuesto', models.ForeignKey(db_column='id_impuesto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='contabilidad.impuestos')),
                ('id_unidad_medida', models.ForeignKey(blank=True, db_column='id_unidad_medida', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='productos.unidadesmedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['descripcion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricoPrecios',
            fields=[
                ('id_historico', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cambios_precios', to='usuarios.empleados')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_precios', to='productos.productos')),
            ],
            options={
                'verbose_name': 'Histórico de Precio',
                'verbose_name_plural': 'Histórico de Precios',
                'db_table': 'historico_precios',
                'ordering': ['-fecha_cambio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreciosPorLista',
            fields=[
                ('id_precio', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio del producto en esta lista', max_digits=12)),
                ('fecha_vigencia', models.DateTimeField(auto_now_add=True, help_text='Fecha desde la cual es válido este precio')),
                ('id_lista', models.ForeignKey(db_column='id_lista', on_delete=django.db.models.deletion.DO_NOTHING, related_name='precios', to='productos.listasprecios')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='precios', to='productos.productos')),
            ],
            options={
                'verbose_name': 'Precio por Lista',
                'verbose_name_plural': 'Precios por Lista',
                'db_table': 'precios_por_lista',
                'ordering': ['id_lista', 'id_producto'],
                'managed': True,
                'unique_together': {('id_producto', 'id_lista')},
            },
        ),
    ]
