# Generated by Django 6.0.2 on 2026-03-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
