# Generated by Django 6.0.2 on 2026-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoprecios',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cambios_precios', to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='preciosporlista',
            name='id_lista',
            field=models.ForeignKey(db_column='id_lista', on_delete=django.db.models.deletion.DO_NOTHING, related_name='precios', to='productos.listasprecios'),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='productos.categorias'),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_impuesto',
            field=models.ForeignKey(db_column='id_impuesto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='contabilidad.impuestos'),
        ),
        migrations.AddField(
            model_name='preciosporlista',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='precios', to='productos.productos'),
        ),
        migrations.AddField(
            model_name='historicoprecios',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='historico_precios', to='productos.productos'),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_unidad_medida',
            field=models.ForeignKey(blank=True, db_column='id_unidad_medida', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='productos.unidadesmedida'),
        ),
        migrations.AlterUniqueTogether(
            name='preciosporlista',
            unique_together={('id_producto', 'id_lista')},
        ),
    ]
