# Generated by Django 4.2 on 2026-05-14 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoprecio',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_precios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicoprecio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precios', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, help_text='Categoría superior (nulo si es raíz)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='productos.categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='productoimpuesto',
            unique_together={('producto', 'impuesto')},
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_barra'], name='idx_prod_cod_barra'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='idx_prod_codigo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['descripcion'], name='idx_prod_desc'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'categoria'], name='idx_prod_activo_cat'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='idx_prod_categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='precioporlista',
            unique_together={('producto', 'lista')},
        ),
    ]
