# Generated by Django 4.2 on 2026-05-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprecio',
            name='es_por_defecto',
            field=models.BooleanField(default=False, help_text='Lista usada como referencia cuando no se especifica ninguna (solo una puede ser por defecto)'),
        ),
    ]
