# Generated by Django 5.2.12 on 2026-03-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productos_codigo_es_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código interno del producto', max_length=50, null=True, unique=True),
        ),
    ]
