# Generated by Django 4.2 on 2026-06-03 00:41
# Sprint A3: pg_trgm + índices GIN para búsqueda tolerante a errores

from django.db import migrations

ENABLE_TRGM = "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
DROP_TRGM   = "-- extensión no se elimina; otros objetos pueden depender de pg_trgm"

GIN_SQL = """
CREATE INDEX IF NOT EXISTS idx_prod_desc_trgm
    ON productos_producto USING gin(descripcion gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_prod_codigo_trgm
    ON productos_producto USING gin(codigo gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_cliente_nombres_trgm
    ON clientes_cliente USING gin(nombres gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_cliente_apellidos_trgm
    ON clientes_cliente USING gin(apellidos gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_hijo_nombre_trgm
    ON clientes_hijo USING gin(nombre gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_proveedor_rs_trgm
    ON compras_proveedor USING gin(razon_social gin_trgm_ops);
"""

DROP_GIN = """
DROP INDEX IF EXISTS idx_prod_desc_trgm;
DROP INDEX IF EXISTS idx_prod_codigo_trgm;
DROP INDEX IF EXISTS idx_cliente_nombres_trgm;
DROP INDEX IF EXISTS idx_cliente_apellidos_trgm;
DROP INDEX IF EXISTS idx_hijo_nombre_trgm;
DROP INDEX IF EXISTS idx_proveedor_rs_trgm;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_listaprecio_es_por_defecto"),
        # GIN SQL toca compras_proveedor, clientes_cliente y clientes_hijo
        ("compras",  "0003_compra_estado_entrega"),
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(ENABLE_TRGM, reverse_sql=DROP_TRGM),
        migrations.RunSQL(GIN_SQL, reverse_sql=DROP_GIN),
    ]
