# Generated by Django 6.0.2 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_productos_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='listasprecios',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='unidadesmedida',
            name='activo',
        ),
        migrations.AddField(
            model_name='categorias',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listasprecios',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(default=True, help_text='1=estado, 0=Inactivo'),
        ),
        migrations.AddField(
            model_name='unidadesmedida',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
