# Generated by Django 5.2.16 on 2026-07-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_pgtrgm_gin_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoimpuesto',
            options={'ordering': ['producto', 'impuesto'], 'verbose_name': 'Impuesto de Producto', 'verbose_name_plural': 'Impuestos de Productos'},
        ),
    ]
