# Generated by Django 6.0.2 on 2026-04-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_alter_cierrescaja_options_and_more'),
        ('productos', '0005_rename_activo_to_estado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['codigo_barra'], name='idx_productos_cod_barra'),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['codigo'], name='idx_productos_codigo'),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['descripcion'], name='idx_productos_desc'),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['estado', 'id_categoria'], name='idx_productos_estado_cat'),
        ),
        migrations.AddIndex(
            model_name='productos',
            index=models.Index(fields=['id_categoria'], name='idx_productos_categoria'),
        ),
    ]
