# Generated by Django 5.2.16 on 2026-09-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_rename_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicoprecio',
            name='id_historico_precio',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='id_impuesto',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listaprecio',
            name='id_lista_precio',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='precioporlista',
            name='id_precio_lista',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoimpuesto',
            name='id_producto_impuesto',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='id_unidad_medida',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
