# Generated by Django 6.0.2 on 2026-05-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_productos_idx_productos_cod_barra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código interno del producto para identificación', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigo_barra',
            field=models.CharField(blank=True, help_text='Código de barras del producto para escaneo', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(help_text='Nombre descriptivo del producto', max_length=255),
        ),
        migrations.AlterField(
            model_name='productos',
            name='es_servicio',
            field=models.BooleanField(default=False, help_text='True si es un servicio (no requiere control de stock físico)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(default=True, help_text='True=Activo, False=Inactivo'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='permite_stock_negativo',
            field=models.BooleanField(default=False, help_text='True si permite vender aún sin stock disponible'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='requiere_stock',
            field=models.BooleanField(default=True, help_text='True si debe controlar stock, False si es producto sin gestión de inventario'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Cantidad mínima en stock antes de generar alerta', max_digits=10),
        ),
    ]
