# Generated by Django 4.2 on 2026-05-14 03:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('AUMENTO', 'Aumento de stock'), ('MERMA', 'Disminución de stock')], max_length=10)),
                ('motivo', models.CharField(help_text='Razón del ajuste', max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STOCK_MINIMO', 'Stock bajo el mínimo'), ('STOCK_CERO', 'Stock agotado'), ('STOCK_CRITICO', 'Stock crítico (50% del mínimo)')], max_length=15)),
                ('stock_actual', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('fecha_resuelta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'ordering': ['-fecha_generada'],
            },
        ),
        migrations.CreateModel(
            name='AlertaVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('30_DIAS', '30 días para vencer'), ('15_DIAS', '15 días para vencer'), ('7_DIAS', '7 días para vencer'), ('3_DIAS', '3 días para vencer'), ('VENCIDO', 'Producto vencido')], max_length=10)),
                ('dias_restantes', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_lote', models.DecimalField(decimal_places=3, max_digits=10)),
                ('accion_tomada', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('DESCUENTO', 'Descuento aplicado'), ('DEVUELTO', 'Devuelto a proveedor'), ('DONADO', 'Donado'), ('DESCARTADO', 'Descartado'), ('VENDIDO', 'Vendido a tiempo')], default='PENDIENTE', max_length=15, null=True)),
                ('fecha_accion', models.DateTimeField(blank=True, null=True)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta de Vencimiento',
                'verbose_name_plural': 'Alertas de Vencimiento',
                'ordering': ['fecha_vencimiento', '-fecha_generada'],
            },
        ),
        migrations.CreateModel(
            name='CostoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.DecimalField(decimal_places=0, help_text='Costo por unidad en Guaraníes', max_digits=12)),
                ('cantidad_comprada', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10)),
                ('fecha_compra', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Costo Histórico',
                'verbose_name_plural': 'Costos Históricos',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad a ajustar (siempre positiva)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
            ],
            options={
                'verbose_name': 'Detalle de Ajuste',
                'verbose_name_plural': 'Detalles de Ajustes',
            },
        ),
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_inicial', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad_disponible', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bloqueado', models.BooleanField(default=False)),
                ('motivo_bloqueo', models.CharField(blank=True, choices=[('VENCIDO', 'Producto vencido'), ('DEFECTUOSO', 'Lote defectuoso'), ('RETIRADO', 'Retiro preventivo'), ('OTRO', 'Otro motivo')], max_length=15, null=True)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lote de Producto',
                'verbose_name_plural': 'Lotes de Productos',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('motivo', models.CharField(choices=[('COMPRA', 'Compra a proveedor'), ('VENTA', 'Venta a cliente'), ('AJUSTE_AUMENTO', 'Ajuste de inventario (aumento)'), ('AJUSTE_MERMA', 'Ajuste de inventario (merma)'), ('DEVOLUCION_CLIENTE', 'Devolución de cliente'), ('DEVOLUCION_PROVEEDOR', 'Devolución a proveedor'), ('CORRECCION', 'Corrección manual'), ('TRANSFERENCIA', 'Transferencia'), ('VENCIDO', 'Baja por vencimiento'), ('DANADO', 'Baja por daño'), ('INVENTARIO_INICIAL', 'Inventario inicial')], max_length=25)),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad (siempre positiva)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('stock_resultante', models.DecimalField(decimal_places=3, help_text='Stock después del movimiento', max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, help_text='Stock actual disponible', max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
