# Generated by Django 6.0.2 on 2026-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesInventario',
            fields=[
                ('id_ajuste', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_ajuste', models.CharField(max_length=8)),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'db_table': 'ajustes_inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CostosHistoricos',
            fields=[
                ('id_costo_historico', models.BigAutoField(primary_key=True, serialize=False)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateTimeField()),
                ('id_compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
            ],
            options={
                'db_table': 'costos_historicos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientosStock',
            fields=[
                ('id_movimiento_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_movimiento', models.CharField(max_length=7)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock_resultante', models.DecimalField(decimal_places=3, max_digits=10)),
                ('id_ajuste', models.BigIntegerField(blank=True, null=True)),
                ('id_compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras')),
                ('id_empleado_autoriza', models.ForeignKey(db_column='id_empleado_autoriza', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas')),
            ],
            options={
                'db_table': 'movimientos_stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockUnico',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_ultima_actualizacion', models.DateTimeField()),
                ('id_producto', models.OneToOneField(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
            ],
            options={
                'db_table': 'stock_unico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesAjuste',
            fields=[
                ('id_detalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_ajustada', models.DecimalField(decimal_places=3, max_digits=8)),
                ('id_ajuste', models.ForeignKey(db_column='id_ajuste', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.ajustesinventario')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos')),
                ('id_movimiento_stock', models.OneToOneField(db_column='id_movimiento_stock', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.movimientosstock')),
            ],
            options={
                'db_table': 'detalles_ajuste',
                'managed': True,
                'unique_together': {('id_ajuste', 'id_producto')},
            },
        ),
    ]
