# Generated by Django 6.0.2 on 2026-03-01 17:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('ventas', '0002_agregar_comision_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertasStock',
            fields=[
                ('id_alerta', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(choices=[('stock_minimo', 'Stock por debajo del mínimo'), ('stock_cero', 'Stock agotado'), ('stock_critico', 'Stock crítico (50% del mínimo)')], default='stock_minimo', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=3, help_text='Stock cuando se generó la alerta', max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=3, help_text='Stock mínimo configurado', max_digits=10)),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('fecha_resuelta', models.DateTimeField(blank=True, help_text='Cuándo se resolvió (stock volvió arriba del mínimo)', null=True)),
                ('activa', models.BooleanField(default=True, help_text='False cuando se resuelve')),
                ('notificacion_enviada', models.BooleanField(default=False, help_text='Si ya se envió notificación')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'db_table': 'alertas_stock',
                'ordering': ['-fecha_generada'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='ajustesinventario',
            options={'managed': True, 'ordering': ['-fecha_hora'], 'verbose_name': 'Ajuste de Inventario', 'verbose_name_plural': 'Ajustes de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='costoshistoricos',
            options={'managed': True, 'ordering': ['-fecha_compra'], 'verbose_name': 'Costo Histórico', 'verbose_name_plural': 'Costos Históricos'},
        ),
        migrations.AlterModelOptions(
            name='detallesajuste',
            options={'managed': True, 'verbose_name': 'Detalle de Ajuste', 'verbose_name_plural': 'Detalles de Ajustes'},
        ),
        migrations.AlterModelOptions(
            name='movimientosstock',
            options={'managed': True, 'ordering': ['-fecha_hora'], 'verbose_name': 'Movimiento de Stock', 'verbose_name_plural': 'Movimientos de Stock'},
        ),
        migrations.AlterModelOptions(
            name='stockunico',
            options={'managed': True, 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AddField(
            model_name='ajustesinventario',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Cuándo fue aprobado/rechazado', null=True),
        ),
        migrations.AddField(
            model_name='ajustesinventario',
            name='id_empleado_aprueba',
            field=models.ForeignKey(blank=True, db_column='id_empleado_aprueba', help_text='Supervisor que aprueba/rechaza', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ajustes_aprobados', to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='ajustesinventario',
            name='id_empleado_solicita',
            field=models.ForeignKey(blank=True, db_column='id_empleado_solicita', help_text='Empleado que solicita el ajuste', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ajustes_solicitados', to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='costoshistoricos',
            name='cantidad_comprada',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Cantidad comprada a este costo', max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientosstock',
            name='motivo',
            field=models.CharField(choices=[('compra', 'Compra a proveedor'), ('venta', 'Venta a cliente'), ('ajuste_aumento', 'Ajuste de inventario (aumento)'), ('ajuste_merma', 'Ajuste de inventario (merma)'), ('devolucion_cliente', 'Devolución de cliente'), ('devolucion_proveedor', 'Devolución a proveedor'), ('correccion_manual', 'Corrección manual'), ('transferencia', 'Transferencia entre sucursales'), ('producto_vencido', 'Baja por vencimiento'), ('producto_danado', 'Baja por daño físico'), ('inventario_inicial', 'Inventario inicial')], default='correccion_manual', help_text='Razón específica del movimiento', max_length=50),
        ),
        migrations.AddField(
            model_name='movimientosstock',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre el movimiento', null=True),
        ),
        migrations.AlterField(
            model_name='ajustesinventario',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de aprobación'), ('Aprobado', 'Aprobado y aplicado'), ('Rechazado', 'Rechazado')], default='Pendiente', help_text='Estado del ajuste', max_length=10),
        ),
        migrations.AlterField(
            model_name='ajustesinventario',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del ajuste'),
        ),
        migrations.AlterField(
            model_name='ajustesinventario',
            name='motivo',
            field=models.CharField(help_text='Razón del ajuste', max_length=255),
        ),
        migrations.AlterField(
            model_name='ajustesinventario',
            name='tipo_ajuste',
            field=models.CharField(choices=[('Aumento', 'Aumento de stock'), ('Merma', 'Disminución de stock')], help_text='Aumento o Merma', max_length=8),
        ),
        migrations.AlterField(
            model_name='costoshistoricos',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Costo de compra por unidad', max_digits=10),
        ),
        migrations.AlterField(
            model_name='costoshistoricos',
            name='fecha_compra',
            field=models.DateTimeField(help_text='Fecha de la compra'),
        ),
        migrations.AlterField(
            model_name='costoshistoricos',
            name='id_compra',
            field=models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='costos_productos', to='compras.compras'),
        ),
        migrations.AlterField(
            model_name='costoshistoricos',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='costos_historicos', to='productos.productos'),
        ),
        migrations.AlterField(
            model_name='detallesajuste',
            name='cantidad_ajustada',
            field=models.DecimalField(decimal_places=3, help_text='Cantidad a ajustar (siempre positiva)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='detallesajuste',
            name='id_ajuste',
            field=models.ForeignKey(db_column='id_ajuste', on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='inventario.ajustesinventario'),
        ),
        migrations.AlterField(
            model_name='detallesajuste',
            name='id_movimiento_stock',
            field=models.OneToOneField(blank=True, db_column='id_movimiento_stock', help_text='Movimiento creado al aprobar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.movimientosstock'),
        ),
        migrations.AlterField(
            model_name='movimientosstock',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, help_text='Cantidad del movimiento (siempre positiva)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='movimientosstock',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientosstock',
            name='id_ajuste',
            field=models.BigIntegerField(blank=True, help_text='ID del ajuste de inventario asociado', null=True),
        ),
        migrations.AlterField(
            model_name='movimientosstock',
            name='id_compra',
            field=models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimientos_stock', to='compras.compras'),
        ),
        migrations.AlterField(
            model_name='movimientosstock',
            name='id_empleado_autoriza',
            field=models.ForeignKey(db_column='id_empleado_autoriza', on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimientos_autorizados', to='usuarios.empleados'),
        ),
        migrations.AlterField(
            model_name='movimientosstock',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimientos_stock', to='productos.productos'),
        ),
        migrations.AlterField(
            model_name='movimientosstock',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimientos_stock', to='ventas.ventas'),
        ),
        migrations.AlterField(
            model_name='movimientosstock',
            name='stock_resultante',
            field=models.DecimalField(decimal_places=3, help_text='Stock después del movimiento', max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientosstock',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], help_text='Ingreso o Egreso', max_length=7),
        ),
        migrations.AlterField(
            model_name='stockunico',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, help_text='Stock actual disponible', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='stockunico',
            name='fecha_ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Última modificación del stock'),
        ),
        migrations.AlterField(
            model_name='stockunico',
            name='id_producto',
            field=models.OneToOneField(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock', to='productos.productos'),
        ),
        migrations.AddIndex(
            model_name='costoshistoricos',
            index=models.Index(fields=['id_producto', '-fecha_compra'], name='costos_hist_id_prod_4de278_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosstock',
            index=models.Index(fields=['id_producto', '-fecha_hora'], name='movimientos_id_prod_a1fd92_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosstock',
            index=models.Index(fields=['tipo_movimiento', 'motivo'], name='movimientos_tipo_mo_95504b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientosstock',
            index=models.Index(fields=['-fecha_hora'], name='movimientos_fecha_h_d7a6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockunico',
            index=models.Index(fields=['id_producto'], name='stock_unico_id_prod_f96be3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockunico',
            index=models.Index(fields=['-fecha_ultima_actualizacion'], name='stock_unico_fecha_u_a52f16_idx'),
        ),
        migrations.AddField(
            model_name='alertasstock',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='alertas_stock', to='productos.productos'),
        ),
        migrations.AddIndex(
            model_name='alertasstock',
            index=models.Index(fields=['id_producto', 'activa'], name='alertas_sto_id_prod_b8b810_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasstock',
            index=models.Index(fields=['-fecha_generada'], name='alertas_sto_fecha_g_8d462d_idx'),
        ),
    ]
