# Generated by Django 6.0.2 on 2026-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0003_initial'),
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costoshistoricos',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos'),
        ),
        migrations.AddField(
            model_name='detallesajuste',
            name='id_ajuste',
            field=models.ForeignKey(db_column='id_ajuste', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.ajustesinventario'),
        ),
        migrations.AddField(
            model_name='detallesajuste',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos'),
        ),
        migrations.AddField(
            model_name='movimientosstock',
            name='id_compra',
            field=models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras'),
        ),
    ]
