# Generated by Django 4.2 on 2026-05-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='producto',
            field=models.OneToOneField(help_text='Producto asociado', on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.ajusteinventario'),
        ),
    ]
