# Generated by Django 6.0.2 on 2026-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_initial'),
        ('productos', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosstock',
            name='id_empleado_autoriza',
            field=models.ForeignKey(db_column='id_empleado_autoriza', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='movimientosstock',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos'),
        ),
    ]
