# Generated by Django 6.0.2 on 2026-03-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alertasstock_alter_ajustesinventario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockunico',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, help_text='Stock actual disponible', max_digits=10),
        ),
    ]
