# Generated by Django 4.2 on 2026-05-14 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0001_initial'),
        ('compras', '0002_initial'),
        ('inventario', '0002_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='autorizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='loteproducto',
            name='compra',
            field=models.ForeignKey(blank=True, help_text='Compra origen del lote', null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.compra'),
        ),
        migrations.AddField(
            model_name='loteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='detalleajuste',
            name='ajuste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ajusteinventario'),
        ),
        migrations.AddField(
            model_name='detalleajuste',
            name='movimiento_stock',
            field=models.OneToOneField(blank=True, help_text='Movimiento generado al aprobar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.movimientostock'),
        ),
        migrations.AddField(
            model_name='detalleajuste',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ajuste', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='costohistorico',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costos_productos', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='costohistorico',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_historicos', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='alertavencimiento',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.loteproducto'),
        ),
        migrations.AddField(
            model_name='alertavencimiento',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_vencimiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_stock', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['producto'], name='inventario__product_eabd7e_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['-fecha_actualizacion'], name='inventario__fecha_a_c0505e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['producto', '-fecha'], name='inventario__product_082fec_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['tipo', 'motivo'], name='inventario__tipo_0ef243_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['-fecha'], name='inventario__fecha_4cb854_idx'),
        ),
        migrations.AddIndex(
            model_name='loteproducto',
            index=models.Index(fields=['producto', 'fecha_vencimiento'], name='inventario__product_a051d5_idx'),
        ),
        migrations.AddIndex(
            model_name='loteproducto',
            index=models.Index(fields=['fecha_vencimiento', 'bloqueado'], name='inventario__fecha_v_0af03d_idx'),
        ),
        migrations.AddIndex(
            model_name='loteproducto',
            index=models.Index(fields=['numero_lote'], name='inventario__numero__5b6f83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleajuste',
            unique_together={('ajuste', 'producto')},
        ),
        migrations.AddIndex(
            model_name='costohistorico',
            index=models.Index(fields=['producto', '-fecha_compra'], name='inventario__product_9fe651_idx'),
        ),
        migrations.AddIndex(
            model_name='alertavencimiento',
            index=models.Index(fields=['lote', 'tipo'], name='inventario__lote_id_686a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='alertavencimiento',
            index=models.Index(fields=['fecha_vencimiento'], name='inventario__fecha_v_9aec49_idx'),
        ),
        migrations.AddIndex(
            model_name='alertavencimiento',
            index=models.Index(fields=['accion_tomada'], name='inventario__accion__3b46b2_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['producto', 'activa'], name='inventario__product_649244_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['-fecha_generada'], name='inventario__fecha_g_0f2ae3_idx'),
        ),
    ]
