# Generated by Django 6.0.2 on 2026-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_initial'),
        ('productos', '0002_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosstock',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas'),
        ),
        migrations.AddField(
            model_name='detallesajuste',
            name='id_movimiento_stock',
            field=models.OneToOneField(db_column='id_movimiento_stock', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.movimientosstock'),
        ),
        migrations.AddField(
            model_name='stockunico',
            name='id_producto',
            field=models.OneToOneField(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos'),
        ),
        migrations.AlterUniqueTogether(
            name='detallesajuste',
            unique_together={('id_ajuste', 'id_producto')},
        ),
    ]
