# Generated by Django 6.0.2 on 2026-03-01 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('inventario', '0003_alter_stockunico_cantidad'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotesProducto',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(help_text='Número de lote del proveedor', max_length=100)),
                ('fecha_fabricacion', models.DateField(blank=True, help_text='Fecha de fabricación (opcional)', null=True)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento del producto')),
                ('cantidad_inicial', models.DecimalField(decimal_places=3, help_text='Cantidad original comprada', max_digits=10)),
                ('cantidad_disponible', models.DecimalField(decimal_places=3, help_text='Cantidad actual disponible en el lote', max_digits=10)),
                ('bloqueado', models.BooleanField(default=False, help_text='True si está vencido o retirado del inventario')),
                ('motivo_bloqueo', models.CharField(blank=True, choices=[('vencido', 'Producto vencido'), ('defectuoso', 'Lote defectuoso'), ('retirado', 'Retiro preventivo'), ('otro', 'Otro motivo')], max_length=100, null=True)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, help_text='Cuándo se bloqueó el lote', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_compra', models.ForeignKey(blank=True, db_column='id_compra', help_text='Compra origen del lote (trazabilidad)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lotes', to='productos.productos')),
            ],
            options={
                'verbose_name': 'Lote de Producto',
                'verbose_name_plural': 'Lotes de Productos',
                'db_table': 'lotes_producto',
                'ordering': ['fecha_vencimiento', '-id_lote'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlertasVencimiento',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(choices=[('30_dias', '30 días para vencer'), ('15_dias', '15 días para vencer'), ('7_dias', '7 días para vencer'), ('3_dias', '3 días para vencer'), ('vencido', 'Producto vencido')], max_length=20)),
                ('dias_restantes', models.IntegerField(help_text='Días hasta vencimiento (negativo si ya venció)')),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento del lote')),
                ('cantidad_lote', models.DecimalField(decimal_places=3, help_text='Cantidad en el lote cuando se generó la alerta', max_digits=10)),
                ('accion_tomada', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('descuento_aplicado', 'Descuento aplicado'), ('devuelto', 'Devuelto a proveedor'), ('donado', 'Donado'), ('descartado', 'Descartado'), ('vendido', 'Vendido a tiempo')], default='pendiente', max_length=100, null=True)),
                ('fecha_accion', models.DateTimeField(blank=True, null=True)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('id_empleado_responsable', models.ForeignKey(blank=True, db_column='id_empleado_responsable', help_text='Empleado que tomó acción sobre la alerta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados')),
                ('id_lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.lotesproducto')),
            ],
            options={
                'verbose_name': 'Alerta de Vencimiento',
                'verbose_name_plural': 'Alertas de Vencimiento',
                'db_table': 'alertas_vencimiento',
                'ordering': ['fecha_vencimiento', '-fecha_generada'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='lotesproducto',
            index=models.Index(fields=['id_producto', 'fecha_vencimiento'], name='lotes_produ_id_prod_870ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='lotesproducto',
            index=models.Index(fields=['fecha_vencimiento', 'bloqueado'], name='lotes_produ_fecha_v_c7309d_idx'),
        ),
        migrations.AddIndex(
            model_name='lotesproducto',
            index=models.Index(fields=['numero_lote'], name='lotes_produ_numero__f9948e_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasvencimiento',
            index=models.Index(fields=['id_lote', 'tipo_alerta'], name='alertas_ven_id_lote_00b7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasvencimiento',
            index=models.Index(fields=['fecha_vencimiento'], name='alertas_ven_fecha_v_a2d2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='alertasvencimiento',
            index=models.Index(fields=['accion_tomada'], name='alertas_ven_accion__e514a4_idx'),
        ),
    ]
