# Generated by Django 5.2.16 on 2026-07-22 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_notacreditoproveedor_tipo_nc'),
        ('inventario', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='nota_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='compras.notacreditoproveedor'),
        ),
    ]
