# Generated by Django 5.2.16 on 2026-07-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_movimientostock_nota_credito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleajuste',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Ajuste', 'verbose_name_plural': 'Detalles de Ajustes'},
        ),
    ]
