# Generated by Django 5.2.16 on 2026-09-02 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_detalleajuste_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertaStock',
        ),
    ]
