# Generated by Django 5.2.16 on 2026-09-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_delete_alertastock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteproducto',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='loteproducto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='AlertaVencimiento',
        ),
        migrations.DeleteModel(
            name='LoteProducto',
        ),
    ]
