# Generated by Django 5.2.16 on 2026-09-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_rename_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleajuste',
            options={'ordering': ['id_detalle_ajuste'], 'verbose_name': 'Detalle de Ajuste', 'verbose_name_plural': 'Detalles de Ajustes'},
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='id_ajuste',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='costohistorico',
            name='id_costo_historico',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detalleajuste',
            name='id_detalle_ajuste',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='id_movimiento_stock',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id_stock',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
