# Generated by Django 4.2 on 2026-05-14 03:17

import apps.almuerzos.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('palabras_clave', models.JSONField(help_text='Palabras clave para detectar el alérgeno en descripciones')),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('icono', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alérgeno',
                'verbose_name_plural': 'Alérgenos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaAlmuerzoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.SmallIntegerField()),
                ('cantidad_almuerzos', models.IntegerField()),
                ('monto_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('forma_cobro', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('ONLINE', 'Pago online'), ('DEBITO_AUTOMATICO', 'Débito automático')], max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDACION', 'Validación Pendiente'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Parcial'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=15)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('comprobante_pago', models.TextField(blank=True, help_text='Referencia o URL del comprobante')),
                ('nro_comprobante', models.CharField(blank=True, help_text='Número de comprobante (ej: 001-001-0000001)', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta Mensual de Almuerzo',
                'verbose_name_plural': 'Cuentas Mensuales de Almuerzo',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='PagoAlmuerzoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mes_pagado', models.DateField(help_text='Mes al que corresponde el pago')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago Mensual de Almuerzo',
                'verbose_name_plural': 'Pagos Mensuales de Almuerzo',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuentaAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('medio_pago', models.CharField(max_length=15)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago de Cuenta de Almuerzo',
                'verbose_name_plural': 'Pagos de Cuentas de Almuerzo',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='PlanAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('CANTIDAD', 'Mensual con cantidad fija'), ('SIN_LIMITE', 'Mensual sin límite (cuenta corriente)')], default='SIN_LIMITE', max_length=15)),
                ('precio_mensual', models.DecimalField(decimal_places=0, help_text='Precio mensual fijo de referencia en Guaraníes', max_digits=12)),
                ('cantidad_almuerzos_mes', models.IntegerField(blank=True, help_text='Solo para tipo=CANTIDAD: máximo de almuerzos por mes', null=True)),
                ('limite_credito_mensual', models.DecimalField(blank=True, decimal_places=0, help_text='Monto máximo acumulable por mes. Vacío = sin límite', max_digits=12, null=True)),
                ('dias_semana_incluidos', models.CharField(help_text='Días de la semana incluidos (ej: LUN,MAR,MIE,JUE,VIE)', max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de Almuerzo',
                'verbose_name_plural': 'Planes de Almuerzo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=0, help_text='Precio por almuerzo en Guaraníes', max_digits=12)),
                ('fecha_inicio_vigencia', models.DateField()),
                ('fecha_fin_vigencia', models.DateField(blank=True, help_text='Vacío = sin vencimiento', null=True)),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Ajuste por inflación 2026', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Precio de Almuerzo',
                'verbose_name_plural': 'Precios de Almuerzo',
                'ordering': ['-fecha_inicio_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='ProductoAlergeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contiene', models.BooleanField(default=True, help_text='True=Contiene el alérgeno, False=Puede contener trazas')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto-Alérgeno',
                'verbose_name_plural': 'Productos-Alérgenos',
            },
        ),
        migrations.CreateModel(
            name='RegistroConsumoAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consumo', models.DateField()),
                ('hora_registro', models.TimeField(default=apps.almuerzos.models.hora_actual)),
                ('costo_almuerzo', models.DecimalField(blank=True, decimal_places=0, help_text='Costo en Guaraníes al momento del consumo', max_digits=12, null=True)),
                ('ya_cobrado', models.BooleanField(default=True, help_text='El primer registro del día cobra (True), siguientes no (False)')),
                ('marcado_en_cuenta', models.BooleanField(default=False, help_text='Si se agregó a la cuenta mensual de almuerzo')),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=15)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Consumo',
                'verbose_name_plural': 'Registros de Consumo',
                'ordering': ['-fecha_consumo', '-hora_registro'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscripción de Almuerzo',
                'verbose_name_plural': 'Suscripciones de Almuerzo',
            },
        ),
        migrations.CreateModel(
            name='TipoAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=0, help_text='Precio en Guaraníes', max_digits=12)),
                ('incluye_plato_principal', models.BooleanField(default=True)),
                ('incluye_postre', models.BooleanField(default=False)),
                ('incluye_bebida', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Almuerzo',
                'verbose_name_plural': 'Tipos de Almuerzo',
                'ordering': ['nombre'],
            },
        ),
    ]
