# Generated by Django 6.0.2 on 2026-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergenos',
            fields=[
                ('id_alergeno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('palabras_clave', models.JSONField()),
                ('nivel_severidad', models.CharField(max_length=10)),
                ('icono', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'alergenos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagosAlmuerzoMensual',
            fields=[
                ('id_pago_almuerzo', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_pagado', models.DateField()),
                ('estado', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'pagos_almuerzo_mensual',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagosCuentasAlmuerzo',
            fields=[
                ('id_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('medio_pago', models.CharField(max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pagos_cuentas_almuerzo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlanesAlmuerzo',
            fields=[
                ('id_plan_almuerzo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_semana_incluidos', models.CharField(max_length=60)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'planes_almuerzo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductosAlergenos',
            fields=[
                ('id_producto_alergeno', models.AutoField(primary_key=True, serialize=False)),
                ('contiene', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('usuario_registro', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'productos_alergenos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegistrosConsumoAlmuerzo',
            fields=[
                ('id_registro_consumo', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_consumo', models.DateField()),
                ('hora_registro', models.TimeField()),
                ('costo_almuerzo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('marcado_en_cuenta', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'registros_consumo_almuerzo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SuscripcionesAlmuerzo',
            fields=[
                ('id_suscripcion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'suscripciones_almuerzo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TiposAlmuerzo',
            fields=[
                ('id_tipo_almuerzo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incluye_plato_principal', models.IntegerField()),
                ('incluye_postre', models.IntegerField()),
                ('incluye_bebida', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_almuerzo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CuentasAlmuerzoMensual',
            fields=[
                ('id_cuenta', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('mes', models.SmallIntegerField()),
                ('cantidad_almuerzos', models.IntegerField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_cobro', models.CharField(max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=10)),
                ('fecha_generacion', models.DateField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_hijo', models.ForeignKey(db_column='id_hijo', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.hijos')),
            ],
            options={
                'db_table': 'cuentas_almuerzo_mensual',
                'managed': True,
            },
        ),
    ]
