# Generated by Django 6.0.2 on 2026-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almuerzos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentasalmuerzomensual',
            name='id_hijo',
            field=models.ForeignKey(db_column='id_hijo', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.hijos'),
        ),
    ]
