# Generated by Django 4.2 on 2026-05-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almuerzos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcionalmuerzo',
            name='hijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones_almuerzo', to='clientes.hijo'),
        ),
        migrations.AddField(
            model_name='suscripcionalmuerzo',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='almuerzos.planalmuerzo'),
        ),
        migrations.AddField(
            model_name='registroconsumoalmuerzo',
            name='hijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_almuerzo', to='clientes.hijo'),
        ),
    ]
