# Generated by Django 4.2 on 2026-05-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almuerzos', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroconsumoalmuerzo',
            name='nro_tarjeta',
            field=models.ForeignKey(blank=True, help_text='Tarjeta usada al momento del consumo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_almuerzo', to='core.tarjeta'),
        ),
    ]
