# Generated by Django 6.0.2 on 2026-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almuerzos', '0002_initial'),
        ('clientes', '0002_initial'),
        ('core', '0001_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosalmuerzomensual',
            name='id_venta',
            field=models.OneToOneField(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.ventas'),
        ),
        migrations.AddField(
            model_name='pagoscuentasalmuerzo',
            name='id_cuenta',
            field=models.ForeignKey(db_column='id_cuenta', on_delete=django.db.models.deletion.DO_NOTHING, to='almuerzos.cuentasalmuerzomensual'),
        ),
        migrations.AddField(
            model_name='pagoscuentasalmuerzo',
            name='id_empleado_registro',
            field=models.ForeignKey(blank=True, db_column='id_empleado_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='productosalergenos',
            name='id_alergeno',
            field=models.ForeignKey(db_column='id_alergeno', on_delete=django.db.models.deletion.DO_NOTHING, to='almuerzos.alergenos'),
        ),
        migrations.AddField(
            model_name='productosalergenos',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos'),
        ),
        migrations.AddField(
            model_name='registrosconsumoalmuerzo',
            name='id_empleado_registro',
            field=models.ForeignKey(blank=True, db_column='id_empleado_registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.empleados'),
        ),
        migrations.AddField(
            model_name='registrosconsumoalmuerzo',
            name='id_hijo',
            field=models.ForeignKey(db_column='id_hijo', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.hijos'),
        ),
        migrations.AddField(
            model_name='registrosconsumoalmuerzo',
            name='nro_tarjeta',
            field=models.ForeignKey(blank=True, db_column='nro_tarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tarjetas'),
        ),
        migrations.AddField(
            model_name='suscripcionesalmuerzo',
            name='id_hijo',
            field=models.ForeignKey(db_column='id_hijo', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.hijos'),
        ),
        migrations.AddField(
            model_name='suscripcionesalmuerzo',
            name='id_plan_almuerzo',
            field=models.ForeignKey(db_column='id_plan_almuerzo', on_delete=django.db.models.deletion.DO_NOTHING, to='almuerzos.planesalmuerzo'),
        ),
        migrations.AddField(
            model_name='registrosconsumoalmuerzo',
            name='id_suscripcion',
            field=models.ForeignKey(blank=True, db_column='id_suscripcion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='almuerzos.suscripcionesalmuerzo'),
        ),
        migrations.AddField(
            model_name='pagosalmuerzomensual',
            name='id_suscripcion',
            field=models.ForeignKey(db_column='id_suscripcion', on_delete=django.db.models.deletion.DO_NOTHING, to='almuerzos.suscripcionesalmuerzo'),
        ),
        migrations.AddField(
            model_name='registrosconsumoalmuerzo',
            name='id_tipo_almuerzo',
            field=models.ForeignKey(blank=True, db_column='id_tipo_almuerzo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='almuerzos.tiposalmuerzo'),
        ),
        migrations.AlterUniqueTogether(
            name='cuentasalmuerzomensual',
            unique_together={('id_hijo', 'anio', 'mes')},
        ),
        migrations.AlterUniqueTogether(
            name='productosalergenos',
            unique_together={('id_producto', 'id_alergeno')},
        ),
        migrations.AlterUniqueTogether(
            name='suscripcionesalmuerzo',
            unique_together={('id_hijo', 'id_plan_almuerzo', 'estado')},
        ),
        migrations.AlterUniqueTogether(
            name='pagosalmuerzomensual',
            unique_together={('id_suscripcion', 'mes_pagado')},
        ),
    ]
