# Generated by Django 4.2 on 2026-05-14 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almuerzos', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0002_initial'),
        ('ventas', '0001_initial'),
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroconsumoalmuerzo',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_almuerzo_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroconsumoalmuerzo',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='almuerzos.suscripcionalmuerzo'),
        ),
        migrations.AddField(
            model_name='registroconsumoalmuerzo',
            name='tipo_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='almuerzos.tipoalmuerzo'),
        ),
        migrations.AddField(
            model_name='productoalergeno',
            name='alergeno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='almuerzos.alergeno'),
        ),
        migrations.AddField(
            model_name='productoalergeno',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergenos', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='productoalergeno',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alergenos_productos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagocuentaalmuerzo',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='almuerzos.cuentaalmuerzomensual'),
        ),
        migrations.AddField(
            model_name='pagocuentaalmuerzo',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_almuerzo_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagoalmuerzomensual',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_mensuales', to='almuerzos.suscripcionalmuerzo'),
        ),
        migrations.AddField(
            model_name='pagoalmuerzomensual',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_almuerzo', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='cuentaalmuerzomensual',
            name='factura',
            field=models.ForeignKey(blank=True, help_text='Factura preimpresa asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_almuerzo', to='contabilidad.factura'),
        ),
        migrations.AddField(
            model_name='cuentaalmuerzomensual',
            name='hijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_almuerzo', to='clientes.hijo'),
        ),
        migrations.AddField(
            model_name='alergeno',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alergenos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='suscripcionalmuerzo',
            unique_together={('hijo', 'plan', 'estado')},
        ),
        migrations.AddIndex(
            model_name='registroconsumoalmuerzo',
            index=models.Index(fields=['hijo', 'fecha_consumo'], name='almuerzos_r_hijo_id_971f76_idx'),
        ),
        migrations.AddIndex(
            model_name='registroconsumoalmuerzo',
            index=models.Index(fields=['fecha_consumo'], name='almuerzos_r_fecha_c_6d560d_idx'),
        ),
        migrations.AddIndex(
            model_name='registroconsumoalmuerzo',
            index=models.Index(fields=['estado'], name='almuerzos_r_estado_aab96d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productoalergeno',
            unique_together={('producto', 'alergeno')},
        ),
        migrations.AlterUniqueTogether(
            name='pagoalmuerzomensual',
            unique_together={('suscripcion', 'mes_pagado')},
        ),
        migrations.AlterUniqueTogether(
            name='cuentaalmuerzomensual',
            unique_together={('hijo', 'anio', 'mes')},
        ),
    ]
