# Generated by Django 4.2 on 2026-05-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_remove_tarifacomision_medio_pago_and_more'),
        ('almuerzos', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuentaalmuerzo',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_cuenta_almuerzo', to='contabilidad.factura'),
        ),
    ]
