# Generated by Django 6.0.2 on 2026-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0004_add_ya_cobrado_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alergenos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='planesalmuerzo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tiposalmuerzo',
            name='activo',
        ),
        migrations.AddField(
            model_name='alergenos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planesalmuerzo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tiposalmuerzo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
