# Generated by Django 4.2 on 2026-05-18 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almuerzos', '0005_factura_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('plato_principal', models.CharField(max_length=255)),
                ('guarnicion', models.CharField(blank=True, max_length=255)),
                ('postre', models.CharField(blank=True, max_length=255)),
                ('bebida', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional o notas')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menú Diario',
                'verbose_name_plural': 'Menús Diarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
