# Generated by Django 6.0.2 on 2026-03-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0005_rename_activo_to_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioAlmuerzo',
            fields=[
                ('id_precio', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por almuerzo en guaraníes', max_digits=10)),
                ('fecha_inicio_vigencia', models.DateField(help_text='Fecha desde la cual aplica este precio')),
                ('fecha_fin_vigencia', models.DateField(blank=True, help_text='Fecha hasta la cual aplica (vacío = sin vencimiento)', null=True)),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Ajuste por inflación 2026', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'precios_almuerzo',
                'ordering': ['-fecha_inicio_vigencia'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cuentasalmuerzomensual',
            name='comprobante_pago',
            field=models.TextField(blank=True, help_text='Referencia, URL o descripción del comprobante de pago'),
        ),
        migrations.AddField(
            model_name='cuentasalmuerzomensual',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha efectiva del pago', null=True),
        ),
        migrations.AddField(
            model_name='cuentasalmuerzomensual',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('online', 'Pago online'), ('debito_automatico', 'Débito automático')], help_text='Método de pago utilizado', max_length=25),
        ),
        migrations.AddField(
            model_name='planesalmuerzo',
            name='cantidad_almuerzos_mes',
            field=models.IntegerField(blank=True, help_text='Solo para tipo=cantidad: máximo de almuerzos incluidos por mes', null=True),
        ),
        migrations.AddField(
            model_name='planesalmuerzo',
            name='tipo_plan',
            field=models.CharField(choices=[('cantidad', 'Mensual con cantidad de almuerzos'), ('sin_limite', 'Mensual sin límite (cuenta corriente)')], default='sin_limite', help_text='sin_limite: se registra consumo y se cobra al final del mes. cantidad: tiene cuota mensual de almuerzos.', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentasalmuerzomensual',
            name='estado',
            field=models.CharField(default='pendiente', max_length=25),
        ),
        migrations.AlterField(
            model_name='planesalmuerzo',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, help_text='Precio mensual fijo (solo referencia para facturación global)', max_digits=10),
        ),
    ]
