# Generated by Django 4.2 on 2026-05-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0006_menudiario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuentaalmuerzomensual',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pagoalmuerzomensual',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='suscripcionalmuerzo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='alergeno',
            name='palabras_clave',
            field=models.JSONField(default=list, help_text='Lista de palabras clave para detectar el alérgeno en descripciones'),
        ),
        migrations.AlterField(
            model_name='registroconsumoalmuerzo',
            name='marcado_en_cuenta',
            field=models.BooleanField(db_index=True, default=False, help_text='Si se agregó a la cuenta mensual de almuerzo'),
        ),
        migrations.AlterField(
            model_name='registroconsumoalmuerzo',
            name='ya_cobrado',
            field=models.BooleanField(db_index=True, default=True, help_text='El primer registro del día cobra (True), siguientes no (False)'),
        ),
        migrations.AddConstraint(
            model_name='cuentaalmuerzomensual',
            constraint=models.UniqueConstraint(fields=('hijo', 'anio', 'mes'), name='unique_cuenta_almuerzo_mensual'),
        ),
        migrations.AddConstraint(
            model_name='pagoalmuerzomensual',
            constraint=models.UniqueConstraint(fields=('suscripcion', 'mes_pagado'), name='unique_pago_mensual_suscripcion'),
        ),
        migrations.AddConstraint(
            model_name='suscripcionalmuerzo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('hijo', 'plan'), name='unique_suscripcion_activa_por_hijo_plan'),
        ),
    ]
