# Generated by Django 6.0.2 on 2026-03-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0006_precio_almuerzo_tipo_plan_pago_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='planesalmuerzo',
            name='limite_credito_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo acumulable en la cuenta corriente por mes. Null = sin límite.', max_digits=10, null=True),
        ),
    ]
