# Generated by Django 6.0.2 on 2026-03-23 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0007_limite_credito_mensual'),
        ('contabilidad', '0006_rename_activo_to_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentasalmuerzomensual',
            name='id_documento',
            field=models.ForeignKey(blank=True, db_column='id_documento', help_text='Factura/comprobante tributario emitido para esta cuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.documentostributarios'),
        ),
        migrations.AddField(
            model_name='cuentasalmuerzomensual',
            name='nro_comprobante',
            field=models.CharField(blank=True, help_text='Número de comprobante formateado (ej: 001-001-0000001)', max_length=30),
        ),
    ]
