# Generated by Django 4.2 on 2026-05-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0007_add_indexes_and_constraints'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoalergeno',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='productoalergeno',
            constraint=models.UniqueConstraint(fields=('producto', 'alergeno'), name='unique_producto_alergeno'),
        ),
    ]
