# Generated by Django 4.2 on 2026-06-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_pgtrgm_gin_indexes'),
        ('almuerzos', '0008_add_validations_and_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMenuDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('ENTRADA', 'Entrada'), ('PLATO_PRINCIPAL', 'Plato principal'), ('GUARNICION', 'Guarnición'), ('POSTRE', 'Postre'), ('BEBIDA', 'Bebida'), ('EXTRA', 'Extra')], default='PLATO_PRINCIPAL', help_text='Parte del menú a la que pertenece este ítem', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, help_text='Cantidad de producto por porción (en la unidad de medida del producto)', max_digits=8)),
                ('es_opcional', models.BooleanField(default=False, help_text='El alumno puede elegir si lo consume o no')),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almuerzos.menudiario')),
                ('producto', models.ForeignKey(help_text='Producto del catálogo que compone este plato', on_delete=django.db.models.deletion.PROTECT, related_name='apariciones_menu', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Menú Diario',
                'verbose_name_plural': 'Detalles de Menú Diario',
                'ordering': ['menu', 'curso'],
            },
        ),
        migrations.AddConstraint(
            model_name='detallemenudiario',
            constraint=models.UniqueConstraint(fields=('menu', 'producto', 'curso'), name='uq_menu_producto_curso'),
        ),
        migrations.AddConstraint(
            model_name='detallemenudiario',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='chk_detalle_menu_cantidad_positiva'),
        ),
    ]
