# Generated by Django 4.2 on 2026-06-03 00:44
# Sprint A1: CHECK constraints en tablas de almuerzos

from django.db import migrations

CHECK_SQL = """
-- almuerzos_cuentaalmuerzomensual
ALTER TABLE almuerzos_cuentaalmuerzomensual
    ADD CONSTRAINT chk_cuenta_mes
    CHECK (mes >= 1 AND mes <= 12);

ALTER TABLE almuerzos_cuentaalmuerzomensual
    ADD CONSTRAINT chk_cuenta_anio
    CHECK (anio >= 2024);

ALTER TABLE almuerzos_cuentaalmuerzomensual
    ADD CONSTRAINT chk_cuenta_montos
    CHECK (monto_total >= 0 AND monto_pagado >= 0 AND cantidad_almuerzos >= 0);

-- almuerzos_planalmuerzo
ALTER TABLE almuerzos_planalmuerzo
    ADD CONSTRAINT chk_plan_precio_no_negativo
    CHECK (precio_mensual >= 0);

ALTER TABLE almuerzos_planalmuerzo
    ADD CONSTRAINT chk_plan_cantidad_positiva
    CHECK (cantidad_almuerzos_mes > 0);
"""

DROP_SQL = """
ALTER TABLE almuerzos_cuentaalmuerzomensual DROP CONSTRAINT IF EXISTS chk_cuenta_mes;
ALTER TABLE almuerzos_cuentaalmuerzomensual DROP CONSTRAINT IF EXISTS chk_cuenta_anio;
ALTER TABLE almuerzos_cuentaalmuerzomensual DROP CONSTRAINT IF EXISTS chk_cuenta_montos;
ALTER TABLE almuerzos_planalmuerzo          DROP CONSTRAINT IF EXISTS chk_plan_precio_no_negativo;
ALTER TABLE almuerzos_planalmuerzo          DROP CONSTRAINT IF EXISTS chk_plan_cantidad_positiva;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("almuerzos", "0009_detalle_menu_diario"),
    ]

    operations = [
        migrations.RunSQL(CHECK_SQL, reverse_sql=DROP_SQL),
    ]
