# Generated by Django 4.2 on 2026-06-03 00:50
# Sprint C2: Trigger para mantener CuentaAlmuerzoMensual consistente

from django.db import migrations

TRIGGER_SQL = """
-- Función que recalcula los totales de la cuenta mensual del alumno
-- cuando se inserta, actualiza o elimina un RegistroConsumoAlmuerzo.
CREATE OR REPLACE FUNCTION fn_sync_cuenta_almuerzo_mensual()
RETURNS TRIGGER AS $$
DECLARE
    v_hijo_id   bigint;
    v_anio      int;
    v_mes       int;
BEGIN
    -- Determinar el hijo y período afectado
    IF TG_OP = 'DELETE' THEN
        v_hijo_id := OLD.hijo_id;
        v_anio    := EXTRACT(YEAR  FROM OLD.fecha_consumo)::int;
        v_mes     := EXTRACT(MONTH FROM OLD.fecha_consumo)::int;
    ELSE
        v_hijo_id := NEW.hijo_id;
        v_anio    := EXTRACT(YEAR  FROM NEW.fecha_consumo)::int;
        v_mes     := EXTRACT(MONTH FROM NEW.fecha_consumo)::int;
    END IF;

    -- Actualizar la cuenta mensual si existe (no la crea; eso lo hace la app)
    UPDATE almuerzos_cuentaalmuerzomensual
    SET
        cantidad_almuerzos = sub.cant,
        monto_total        = sub.total,
        fecha_actualizacion = now()
    FROM (
        SELECT
            COUNT(*)                      AS cant,
            COALESCE(SUM(costo_almuerzo), 0) AS total
        FROM almuerzos_registroconsumoalmuerzo
        WHERE hijo_id    = v_hijo_id
          AND EXTRACT(YEAR  FROM fecha_consumo) = v_anio
          AND EXTRACT(MONTH FROM fecha_consumo) = v_mes
          AND cobrado = false
    ) sub
    WHERE hijo_id = v_hijo_id
      AND anio    = v_anio
      AND mes     = v_mes;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Trigger que dispara la función en cada cambio de RegistroConsumoAlmuerzo
DROP TRIGGER IF EXISTS trg_sync_cuenta_almuerzo ON almuerzos_registroconsumoalmuerzo;

CREATE TRIGGER trg_sync_cuenta_almuerzo
AFTER INSERT OR UPDATE OR DELETE
ON almuerzos_registroconsumoalmuerzo
FOR EACH ROW EXECUTE FUNCTION fn_sync_cuenta_almuerzo_mensual();
"""

DROP_TRIGGER = """
DROP TRIGGER IF EXISTS trg_sync_cuenta_almuerzo ON almuerzos_registroconsumoalmuerzo;
DROP FUNCTION IF EXISTS fn_sync_cuenta_almuerzo_mensual();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("almuerzos", "0010_check_constraints_almuerzos"),
    ]

    operations = [
        migrations.RunSQL(TRIGGER_SQL, reverse_sql=DROP_TRIGGER),
    ]
