# Generated by Django 4.2 on 2026-07-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0012_partial_idx_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcionalmuerzo',
            name='tipo_cobro',
            field=models.CharField(choices=[('CUENTA', 'Por consumo (cuenta corriente)'), ('MENSUAL', 'Cuota mensual fija')], default='CUENTA', help_text='CUENTA = padre paga al final del mes según consumo real. MENSUAL = cuota fija por adelantado.', max_length=10),
        ),
    ]
