# Generated by Django 5.2.16 on 2026-07-22 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0014_fix_trigger_ya_cobrado'),
        ('contabilidad', '0012_mv_balance_cliente_uq_caja_abierta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuentaalmuerzo',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cuenta_almuerzo', to='contabilidad.factura'),
        ),
    ]
