# Generated by Django 5.2.16 on 2026-07-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0015_factura_fk_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoalergeno',
            options={'ordering': ['producto', 'alergeno'], 'verbose_name': 'Producto-Alérgeno', 'verbose_name_plural': 'Productos-Alérgenos'},
        ),
    ]
