# Generated by Django 5.2.16 on 2026-08-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0017_desactivar_tipo_plan_alternativos'),
    ]

    operations = [
        migrations.AddField(
            model_name='planalmuerzo',
            name='es_predeterminado',
            field=models.BooleanField(default=False, help_text='Plan preseleccionado al dar de alta una suscripción (solo uno puede serlo)'),
        ),
        migrations.AddField(
            model_name='tipoalmuerzo',
            name='es_predeterminado',
            field=models.BooleanField(default=False, help_text='Tipo preseleccionado al registrar un consumo (solo uno puede serlo)'),
        ),
    ]
