# Generated by Django 5.2.16 on 2026-08-06 22:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0019_marcar_predeterminados_iniciales'),
        ('clientes', '0011_add_factura_genera_factura_to_cc'),
        ('contabilidad', '0012_mv_balance_cliente_uq_caja_abierta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecargaSaldoAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_cargado', models.DecimalField(decimal_places=0, help_text='Monto en Guaraníes', max_digits=12)),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_almuerzo', to='contabilidad.factura')),
                ('hijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recargas_almuerzo', to='clientes.hijo')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Vacío si la recarga vino del portal de padres (Bancard)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recargas_almuerzo_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recarga de Saldo de Almuerzo',
                'verbose_name_plural': 'Recargas de Saldo de Almuerzo',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='SaldoAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_actual', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hijo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='saldo_almuerzo', to='clientes.hijo')),
            ],
            options={
                'verbose_name': 'Saldo de Almuerzo',
                'verbose_name_plural': 'Saldos de Almuerzo',
            },
        ),
        migrations.CreateModel(
            name='MovimientoSaldoAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECARGA', 'Recarga'), ('CONSUMO', 'Consumo'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=0, help_text='Positivo = crédito (recarga/reversión), negativo = débito (consumo)', max_digits=12)),
                ('saldo_resultante', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('registro_consumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_saldo', to='almuerzos.registroconsumoalmuerzo')),
                ('recarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_saldo', to='almuerzos.recargasaldoalmuerzo')),
                ('saldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='almuerzos.saldoalmuerzo')),
            ],
            options={
                'verbose_name': 'Movimiento de Saldo de Almuerzo',
                'verbose_name_plural': 'Movimientos de Saldo de Almuerzo',
                'ordering': ['-fecha'],
            },
        ),
    ]
