# Generated by Django 5.2.16 on 2026-09-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0020_saldo_almuerzo_cuenta_corriente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcionalmuerzo',
            name='tipo_cobro',
        ),
        migrations.DeleteModel(
            name='PagoAlmuerzoMensual',
        ),
    ]
