# Generated by Django 5.2.16 on 2026-09-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0022_rename_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergeno',
            name='id_alergeno',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuentaalmuerzomensual',
            name='id_cuenta_mensual',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallemenudiario',
            name='id_detalle_menu',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menudiario',
            name='id_menu',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movimientosaldoalmuerzo',
            name='id_movimiento_almuerzo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagocuentaalmuerzo',
            name='id_pago_cuenta',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='planalmuerzo',
            name='id_plan_almuerzo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='precioalmuerzo',
            name='id_precio_almuerzo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoalergeno',
            name='id_producto_alergeno',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recargasaldoalmuerzo',
            name='id_recarga_almuerzo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registroconsumoalmuerzo',
            name='id_registro_consumo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saldoalmuerzo',
            name='id_saldo_almuerzo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suscripcionalmuerzo',
            name='id_suscripcion',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoalmuerzo',
            name='id_tipo_almuerzo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
