# Generated by Django 5.2.16 on 2026-09-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0023_alter_alergeno_id_alergeno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroconsumoalmuerzo',
            name='client_request_id',
            field=models.CharField(blank=True, help_text='UUID generado en el navegador al escanear la tarjeta. Si la cola offline del Service Worker reintenta el mismo POST porque perdió la respuesta (no porque la request haya fallado), este campo permite reconocer el reintento y devolver el registro ya creado en vez de duplicarlo.', max_length=64, null=True, unique=True),
        ),
    ]
