# Generated by Django 5.2.16 on 2026-09-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0024_registroconsumoalmuerzo_client_request_id'),
        ('clientes', '0020_remove_ciudad_pais_remove_cliente_ciudad_catalogo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='suscripcionalmuerzo',
            name='unique_suscripcion_activa_por_hijo_plan',
        ),
        migrations.RemoveField(
            model_name='planalmuerzo',
            name='limite_credito_mensual',
        ),
        migrations.AddConstraint(
            model_name='suscripcionalmuerzo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('hijo',), name='unique_suscripcion_activa_por_hijo'),
        ),
    ]
