# Generated by Django 5.2.16 on 2026-09-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0026_eliminar_marcado_en_cuenta_y_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcionalmuerzo',
            name='plan',
        ),
        migrations.DeleteModel(
            name='PlanAlmuerzo',
        ),
    ]
