# Generated by Django 5.2.16 on 2026-09-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almuerzos', '0027_suprimir_planes_almuerzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldoalmuerzo',
            name='limite_credito',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Tope de deuda para la alerta a ADMIN. 0 = sin tope.', max_digits=12),
        ),
    ]
