# Generated by Django 4.2 on 2026-05-14 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionPagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=0, help_text='Monto aplicado a esta compra', max_digits=12)),
            ],
            options={
                'verbose_name': 'Aplicación de Pago',
                'verbose_name_plural': 'Aplicaciones de Pagos',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=0, default=0, help_text='Monto total en Guaraníes', max_digits=12)),
                ('tipo_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10)),
                ('nro_factura_proveedor', models.CharField(blank=True, help_text='Número de factura del proveedor', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CuentaCorrienteProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('NOTA_CREDITO', 'Nota de Crédito'), ('AJUSTE', 'Ajuste')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=0, help_text='Monto en Guaraníes', max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=0, help_text='Saldo antes del movimiento', max_digits=12)),
                ('saldo_resultante', models.DecimalField(decimal_places=0, help_text='Saldo después del movimiento', max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Cuenta Corriente Proveedor',
                'verbose_name_plural': 'Cuentas Corrientes de Proveedores',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad comprada', max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=0, help_text='Costo por unidad en Guaraníes', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=0, help_text='Subtotal en Guaraníes', max_digits=12)),
                ('monto_iva', models.DecimalField(decimal_places=0, default=0, help_text='IVA aplicado', max_digits=12)),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCreditoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=0, help_text='Precio en Guaraníes', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=0, help_text='Subtotal en Guaraníes', max_digits=12)),
            ],
            options={
                'verbose_name': 'Detalle de NC de Proveedor',
                'verbose_name_plural': 'Detalles de NC de Proveedores',
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=0, help_text='Monto total en Guaraníes', max_digits=12)),
                ('nro_factura_compra', models.CharField(blank=True, help_text='Nro de factura de la compra original', max_length=50, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('APLICADA', 'Aplicada'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota de Crédito de Proveedor',
                'verbose_name_plural': 'Notas de Crédito de Proveedores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=0, help_text='Monto total del pago en Guaraníes', max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, help_text='Nro de transferencia, cheque, etc.', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONCILIADO', 'Conciliado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(help_text='RUC del proveedor', max_length=20, unique=True)),
                ('razon_social', models.CharField(help_text='Razón social o nombre comercial', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['ruc'], name='idx_prov_ruc'),
        ),
    ]
