# Generated by Django 6.0.2 on 2026-03-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionPagosCompras',
            fields=[
                ('id_aplicacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Aplicación de Pago de Compra',
                'verbose_name_plural': 'Aplicaciones de Pagos de Compras',
                'db_table': 'aplicacion_pagos_compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_pago', models.CharField(max_length=10)),
                ('nro_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesCompra',
            fields=[
                ('id_detalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'db_table': 'detalles_compra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesNotaCreditoProveedor',
            fields=[
                ('id_detalle_nc_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Detalle de NC de Proveedor',
                'verbose_name_plural': 'Detalles de NC de Proveedores',
                'db_table': 'detalles_nota_credito_proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotasCreditoProveedor',
            fields=[
                ('id_nota_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nro_factura_compra', models.BigIntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Nota de Crédito de Proveedor',
                'verbose_name_plural': 'Notas de Crédito de Proveedores',
                'db_table': 'notas_credito_proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagosProveedores',
            fields=[
                ('id_pago_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'db_table': 'pagos_proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
    ]
