# Generated by Django 6.0.2 on 2026-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('contabilidad', '0001_initial'),
        ('core', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='id_documento',
            field=models.ForeignKey(blank=True, db_column='id_documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabilidad.documentostributarios'),
        ),
        migrations.AddField(
            model_name='aplicacionpagoscompras',
            name='id_compra',
            field=models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras'),
        ),
        migrations.AddField(
            model_name='detallescompra',
            name='id_compra',
            field=models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras'),
        ),
        migrations.AddField(
            model_name='detallescompra',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos'),
        ),
        migrations.AddField(
            model_name='detallesnotacreditoproveedor',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productos'),
        ),
        migrations.AddField(
            model_name='notascreditoproveedor',
            name='id_compra_original',
            field=models.ForeignKey(blank=True, db_column='id_compra_original', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras'),
        ),
        migrations.AddField(
            model_name='detallesnotacreditoproveedor',
            name='id_nota_proveedor',
            field=models.ForeignKey(db_column='id_nota_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.notascreditoproveedor'),
        ),
        migrations.AddField(
            model_name='pagosproveedores',
            name='id_medio_pago',
            field=models.ForeignKey(db_column='id_medio_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='core.mediospago'),
        ),
        migrations.AddField(
            model_name='aplicacionpagoscompras',
            name='id_pago_proveedor',
            field=models.ForeignKey(db_column='id_pago_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.pagosproveedores'),
        ),
        migrations.AddField(
            model_name='notascreditoproveedor',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.proveedores'),
        ),
        migrations.AddField(
            model_name='compras',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.proveedores'),
        ),
        migrations.AlterUniqueTogether(
            name='detallescompra',
            unique_together={('id_compra', 'id_producto')},
        ),
    ]
