# Generated by Django 6.0.2 on 2026-03-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='id_documento',
            field=models.ForeignKey(blank=True, db_column='id_documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabilidad.documentostributarios'),
        ),
        migrations.AddField(
            model_name='aplicacionpagoscompras',
            name='id_compra',
            field=models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras'),
        ),
        migrations.AddField(
            model_name='detallescompra',
            name='id_compra',
            field=models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras'),
        ),
    ]
