# Generated by Django 4.2 on 2026-05-14 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoproveedor',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_proveedores_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='medio_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_proveedores', to='core.mediopago'),
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='notacreditoproveedor',
            name='compra_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='notacreditoproveedor',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_proveedor_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notacreditoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='detallenotacreditoproveedor',
            name='nota_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.notacreditoproveedor'),
        ),
        migrations.AddField(
            model_name='detallenotacreditoproveedor',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_nc_proveedor', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='cuentacorrienteproveedor',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='cuentacorrienteproveedor',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_proveedor_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentacorrienteproveedor',
            name='nota_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta', to='compras.notacreditoproveedor'),
        ),
        migrations.AddField(
            model_name='cuentacorrienteproveedor',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta', to='compras.pagoproveedor'),
        ),
        migrations.AddField(
            model_name='cuentacorrienteproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cuenta', to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compra',
            name='medio_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='core.mediopago'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='aplicacionpagocompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_pago', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='aplicacionpagocompra',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='compras.pagoproveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='detallecompra',
            unique_together={('compra', 'producto')},
        ),
        migrations.AddIndex(
            model_name='cuentacorrienteproveedor',
            index=models.Index(fields=['proveedor', 'fecha'], name='idx_cc_prov_fecha'),
        ),
        migrations.AddIndex(
            model_name='cuentacorrienteproveedor',
            index=models.Index(fields=['proveedor', 'tipo'], name='idx_cc_prov_tipo'),
        ),
        migrations.AddIndex(
            model_name='cuentacorrienteproveedor',
            index=models.Index(fields=['compra'], name='idx_cc_prov_compra'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['proveedor', 'fecha'], name='idx_compra_prov_fecha'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['estado_pago', 'fecha'], name='idx_compra_estado_fecha'),
        ),
    ]
