# Generated by Django 4.2 on 2026-05-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado_entrega',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida')], default='PENDIENTE', help_text='Estado de recepcion de la mercaderia', max_length=10),
        ),
    ]
