# Generated by Django 5.2.12 on 2026-03-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_rename_activo_to_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
