# Generated by Django 5.2.12 on 2026-03-19 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_proveedores_fecha_registro'),
        ('core', '0008_rename_activo_to_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='id_medio_pago',
            field=models.ForeignKey(blank=True, db_column='id_medio_pago', help_text='Forma de pago utilizada (efectivo, transferencia, etc.)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.mediospago'),
        ),
        migrations.AddField(
            model_name='compras',
            name='tipo_pago',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Crédito', 'Crédito')], default='Contado', help_text='Indica si la compra es al contado o a crédito', max_length=10),
        ),
    ]
