# Generated by Django 5.2.12 on 2026-03-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_compras_id_medio_pago_compras_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='estado_pago',
            field=models.CharField(default='Pendiente', help_text='Estado del pago: Pendiente, Parcial, Pagado', max_length=10),
        ),
        migrations.AlterField(
            model_name='compras',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto total de la compra (calculado automáticamente)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='compras',
            name='saldo_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo pendiente de pago', max_digits=12, null=True),
        ),
    ]
