# Generated by Django 4.2 on 2026-06-25 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_pgtrgm_gin_indexes'),
        ('compras', '0005_add_parcial_estado_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=0, default=0, help_text='Último precio de compra registrado (Gs.)', max_digits=12)),
                ('fecha_ultima_compra', models.DateTimeField(blank=True, help_text='Fecha de la última compra confirmada', null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_producto', to='productos.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_proveedor', to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Producto de Proveedor',
                'verbose_name_plural': 'Productos de Proveedor',
                'ordering': ['producto__descripcion'],
            },
        ),
        migrations.AddIndex(
            model_name='productoproveedor',
            index=models.Index(fields=['proveedor'], name='idx_pp_proveedor'),
        ),
        migrations.AddIndex(
            model_name='productoproveedor',
            index=models.Index(fields=['producto'], name='idx_pp_producto'),
        ),
        migrations.AlterUniqueTogether(
            name='productoproveedor',
            unique_together={('proveedor', 'producto')},
        ),
    ]
