# Generated by Django 6.0.2 on 2026-04-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_compras_estado_pago_alter_compras_monto_total_and_more'),
        ('contabilidad', '0011_condicion_venta'),
        ('core', '0011_configuraciones_adicionales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'managed': True, 'ordering': ['-fecha'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AddIndex(
            model_name='compras',
            index=models.Index(fields=['fecha', 'id_proveedor'], name='idx_compras_fecha_prov'),
        ),
        migrations.AddIndex(
            model_name='compras',
            index=models.Index(fields=['estado_pago', 'fecha'], name='idx_compras_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='compras',
            index=models.Index(fields=['nro_factura'], name='idx_compras_nro_factura'),
        ),
        migrations.AddIndex(
            model_name='compras',
            index=models.Index(fields=['id_proveedor', 'fecha'], name='idx_compras_prov_fecha'),
        ),
        migrations.AddIndex(
            model_name='compras',
            index=models.Index(fields=['fecha'], name='idx_compras_fecha'),
        ),
    ]
