# Generated by Django 5.2.16 on 2026-07-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_backfill_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditoproveedor',
            name='tipo_nc',
            field=models.CharField(choices=[('AJUSTE_PRECIO', 'Ajuste de precio'), ('DEVOLUCION', 'Devolución de mercadería')], default='AJUSTE_PRECIO', help_text='Tipo de nota de crédito', max_length=20),
        ),
    ]
