# Generated by Django 6.0.2 on 2026-05-07 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_compras_options_compras_idx_compras_fecha_prov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescompra',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, help_text='Cantidad de unidades compradas', max_digits=8),
        ),
        migrations.AlterField(
            model_name='detallescompra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Costo por unidad del producto', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallescompra',
            name='id_compra',
            field=models.ForeignKey(db_column='id_compra', help_text='Compra a la que pertenece este detalle', on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compras'),
        ),
        migrations.AlterField(
            model_name='detallescompra',
            name='monto_iva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de IVA aplicado al producto', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallescompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Subtotal (cantidad × costo_unitario)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad donde opera el proveedor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección física del proveedor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='email',
            field=models.CharField(blank=True, help_text='Email de contacto', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='estado',
            field=models.BooleanField(default=True, help_text='True=Activo, False=Inactivo'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del proveedor en el sistema'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='razon_social',
            field=models.CharField(help_text='Razón social o nombre comercial del proveedor', max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='ruc',
            field=models.CharField(help_text='RUC del proveedor (único)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True),
        ),
    ]
