# Generated by Django 5.2.16 on 2026-07-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_notacreditoproveedor_tipo_nc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacionpagocompra',
            options={'ordering': ['id'], 'verbose_name': 'Aplicación de Pago', 'verbose_name_plural': 'Aplicaciones de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='detallenotacreditoproveedor',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de NC de Proveedor', 'verbose_name_plural': 'Detalles de NC de Proveedores'},
        ),
    ]
