# Generated by Django 5.2.16 on 2026-08-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_aplicacionpagocompra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10),
        ),
    ]
