# Generated by Django 5.2.16 on 2026-09-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_alter_compra_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado_entrega',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida')], default='PENDIENTE', help_text='Estado de recepcion de la mercaderia', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='estado',
            field=models.CharField(choices=[('CONCILIADO', 'Conciliado')], default='CONCILIADO', max_length=15),
        ),
    ]
