# Generated by Django 5.2.16 on 2026-09-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_rename_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacionpagocompra',
            options={'ordering': ['id_aplicacion_pago_compra'], 'verbose_name': 'Aplicación de Pago', 'verbose_name_plural': 'Aplicaciones de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='cuentacorrienteproveedor',
            options={'ordering': ['-fecha', '-id_movimiento_ccp'], 'verbose_name': 'Movimiento de Cuenta Corriente Proveedor', 'verbose_name_plural': 'Cuentas Corrientes de Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='detallenotacreditoproveedor',
            options={'ordering': ['id_detalle_ncp'], 'verbose_name': 'Detalle de NC de Proveedor', 'verbose_name_plural': 'Detalles de NC de Proveedores'},
        ),
        migrations.AlterField(
            model_name='aplicacionpagocompra',
            name='id_aplicacion_pago_compra',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_compra',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuentacorrienteproveedor',
            name='id_movimiento_ccp',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='id_detalle_compra',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallenotacreditoproveedor',
            name='id_detalle_ncp',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='id_detalle_oc',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notacreditoproveedor',
            name='id_nc_proveedor',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='id_orden_compra',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='id_pago_proveedor',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoproveedor',
            name='id_producto_proveedor',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
