# Generated by Django 5.2.16 on 2026-09-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_proveedor_ciudad_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoproveedor',
            name='preferido',
            field=models.BooleanField(default=False, help_text='Proveedor preferido para este producto (uno solo por producto).'),
        ),
    ]
